# Install script for directory: /home/chris/crimson/petsc/vtk/vtk-v5.8.0/Graphics

# Set the install prefix
if(NOT DEFINED CMAKE_INSTALL_PREFIX)
  set(CMAKE_INSTALL_PREFIX "/home/chris/crimson/vtk-install")
endif()
string(REGEX REPLACE "/$" "" CMAKE_INSTALL_PREFIX "${CMAKE_INSTALL_PREFIX}")

# Set the install configuration name.
if(NOT DEFINED CMAKE_INSTALL_CONFIG_NAME)
  if(BUILD_TYPE)
    string(REGEX REPLACE "^[^A-Za-z0-9_]+" ""
           CMAKE_INSTALL_CONFIG_NAME "${BUILD_TYPE}")
  else()
    set(CMAKE_INSTALL_CONFIG_NAME "Debug")
  endif()
  message(STATUS "Install configuration: \"${CMAKE_INSTALL_CONFIG_NAME}\"")
endif()

# Set the component getting installed.
if(NOT CMAKE_INSTALL_COMPONENT)
  if(COMPONENT)
    message(STATUS "Install component: \"${COMPONENT}\"")
    set(CMAKE_INSTALL_COMPONENT "${COMPONENT}")
  else()
    set(CMAKE_INSTALL_COMPONENT)
  endif()
endif()

# Install shared libraries without execute permission?
if(NOT DEFINED CMAKE_INSTALL_SO_NO_EXE)
  set(CMAKE_INSTALL_SO_NO_EXE "0")
endif()

# Is this installation the result of a crosscompile?
if(NOT DEFINED CMAKE_CROSSCOMPILING)
  set(CMAKE_CROSSCOMPILING "FALSE")
endif()

if("x${CMAKE_INSTALL_COMPONENT}x" STREQUAL "xDevelopmentx" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/lib/vtk-5.8" TYPE STATIC_LIBRARY FILES "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/bin/libvtkGraphics.a")
endif()

if("x${CMAKE_INSTALL_COMPONENT}x" STREQUAL "xDevelopmentx" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/vtk-5.8" TYPE FILE FILES
    "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/Graphics/vtkAnnotationLink.h"
    "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/Graphics/vtkAppendCompositeDataLeaves.h"
    "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/Graphics/vtkAppendFilter.h"
    "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/Graphics/vtkAppendPolyData.h"
    "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/Graphics/vtkAppendSelection.h"
    "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/Graphics/vtkApproximatingSubdivisionFilter.h"
    "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/Graphics/vtkArcSource.h"
    "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/Graphics/vtkAreaContourSpectrumFilter.h"
    "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/Graphics/vtkArrayCalculator.h"
    "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/Graphics/vtkArrowSource.h"
    "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/Graphics/vtkAssignAttribute.h"
    "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/Graphics/vtkAttributeDataToFieldDataFilter.h"
    "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/Graphics/vtkAxes.h"
    "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/Graphics/vtkBandedPolyDataContourFilter.h"
    "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/Graphics/vtkBlankStructuredGrid.h"
    "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/Graphics/vtkBlankStructuredGridWithImage.h"
    "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/Graphics/vtkBlockIdScalars.h"
    "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/Graphics/vtkBoxClipDataSet.h"
    "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/Graphics/vtkBrownianPoints.h"
    "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/Graphics/vtkButterflySubdivisionFilter.h"
    "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/Graphics/vtkButtonSource.h"
    "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/Graphics/vtkCellCenters.h"
    "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/Graphics/vtkCellDataToPointData.h"
    "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/Graphics/vtkCellDerivatives.h"
    "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/Graphics/vtkCellLocatorInterpolatedVelocityField.h"
    "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/Graphics/vtkCellQuality.h"
    "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/Graphics/vtkCleanPolyData.h"
    "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/Graphics/vtkClipClosedSurface.h"
    "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/Graphics/vtkClipConvexPolyData.h"
    "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/Graphics/vtkClipDataSet.h"
    "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/Graphics/vtkClipHyperOctree.h"
    "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/Graphics/vtkClipPolyData.h"
    "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/Graphics/vtkClipVolume.h"
    "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/Graphics/vtkCoincidentPoints.h"
    "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/Graphics/vtkCompositeDataGeometryFilter.h"
    "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/Graphics/vtkCompositeDataProbeFilter.h"
    "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/Graphics/vtkConeSource.h"
    "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/Graphics/vtkConnectivityFilter.h"
    "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/Graphics/vtkContourFilter.h"
    "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/Graphics/vtkContourGrid.h"
    "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/Graphics/vtkConvertSelection.h"
    "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/Graphics/vtkCubeSource.h"
    "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/Graphics/vtkCursor2D.h"
    "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/Graphics/vtkCursor3D.h"
    "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/Graphics/vtkCurvatures.h"
    "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/Graphics/vtkCutter.h"
    "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/Graphics/vtkCylinderSource.h"
    "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/Graphics/vtkDashedStreamLine.h"
    "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/Graphics/vtkDataObjectGenerator.h"
    "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/Graphics/vtkDataObjectToDataSetFilter.h"
    "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/Graphics/vtkDataSetEdgeSubdivisionCriterion.h"
    "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/Graphics/vtkDataSetGradient.h"
    "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/Graphics/vtkDataSetGradientPrecompute.h"
    "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/Graphics/vtkDataSetSurfaceFilter.h"
    "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/Graphics/vtkDataSetToDataObjectFilter.h"
    "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/Graphics/vtkDataSetTriangleFilter.h"
    "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/Graphics/vtkDecimatePolylineFilter.h"
    "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/Graphics/vtkDecimatePro.h"
    "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/Graphics/vtkDelaunay2D.h"
    "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/Graphics/vtkDelaunay3D.h"
    "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/Graphics/vtkDensifyPolyData.h"
    "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/Graphics/vtkDicer.h"
    "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/Graphics/vtkDijkstraGraphGeodesicPath.h"
    "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/Graphics/vtkDijkstraImageGeodesicPath.h"
    "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/Graphics/vtkDiscreteMarchingCubes.h"
    "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/Graphics/vtkDiskSource.h"
    "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/Graphics/vtkEdgePoints.h"
    "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/Graphics/vtkEdgeSubdivisionCriterion.h"
    "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/Graphics/vtkElevationFilter.h"
    "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/Graphics/vtkEllipticalButtonSource.h"
    "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/Graphics/vtkExtractArraysOverTime.h"
    "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/Graphics/vtkExtractBlock.h"
    "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/Graphics/vtkExtractCells.h"
    "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/Graphics/vtkExtractDataOverTime.h"
    "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/Graphics/vtkExtractDataSets.h"
    "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/Graphics/vtkExtractEdges.h"
    "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/Graphics/vtkExtractGeometry.h"
    "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/Graphics/vtkExtractGrid.h"
    "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/Graphics/vtkExtractLevel.h"
    "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/Graphics/vtkExtractPolyDataGeometry.h"
    "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/Graphics/vtkExtractRectilinearGrid.h"
    "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/Graphics/vtkExtractSelectedBlock.h"
    "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/Graphics/vtkExtractSelectedFrustum.h"
    "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/Graphics/vtkExtractSelectedIds.h"
    "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/Graphics/vtkExtractSelectedLocations.h"
    "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/Graphics/vtkExtractSelectedPolyDataIds.h"
    "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/Graphics/vtkExtractSelectedRows.h"
    "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/Graphics/vtkExtractSelectedThresholds.h"
    "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/Graphics/vtkExtractSelectionBase.h"
    "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/Graphics/vtkExtractSelection.h"
    "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/Graphics/vtkExtractTemporalFieldData.h"
    "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/Graphics/vtkExtractTensorComponents.h"
    "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/Graphics/vtkExtractUnstructuredGrid.h"
    "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/Graphics/vtkExtractVectorComponents.h"
    "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/Graphics/vtkFeatureEdges.h"
    "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/Graphics/vtkFieldDataToAttributeDataFilter.h"
    "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/Graphics/vtkFillHolesFilter.h"
    "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/Graphics/vtkFrustumSource.h"
    "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/Graphics/vtkGeodesicPath.h"
    "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/Graphics/vtkGeometryFilter.h"
    "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/Graphics/vtkGlyph2D.h"
    "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/Graphics/vtkGlyph3D.h"
    "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/Graphics/vtkGlyphSource2D.h"
    "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/Graphics/vtkGradientFilter.h"
    "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/Graphics/vtkGraphGeodesicPath.h"
    "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/Graphics/vtkGraphLayoutFilter.h"
    "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/Graphics/vtkGraphToPoints.h"
    "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/Graphics/vtkGraphToPolyData.h"
    "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/Graphics/vtkGridSynchronizedTemplates3D.h"
    "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/Graphics/vtkHedgeHog.h"
    "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/Graphics/vtkHierarchicalDataExtractDataSets.h"
    "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/Graphics/vtkHierarchicalDataExtractLevel.h"
    "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/Graphics/vtkHierarchicalDataLevelFilter.h"
    "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/Graphics/vtkHierarchicalDataSetGeometryFilter.h"
    "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/Graphics/vtkHull.h"
    "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/Graphics/vtkHyperOctreeClipCutPointsGrabber.h"
    "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/Graphics/vtkHyperOctreeContourFilter.h"
    "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/Graphics/vtkHyperOctreeCutter.h"
    "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/Graphics/vtkHyperOctreeDepth.h"
    "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/Graphics/vtkHyperOctreeDualGridContourFilter.h"
    "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/Graphics/vtkHyperOctreeFractalSource.h"
    "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/Graphics/vtkHyperOctreeLimiter.h"
    "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/Graphics/vtkHyperOctreeSampleFunction.h"
    "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/Graphics/vtkHyperOctreeSurfaceFilter.h"
    "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/Graphics/vtkHyperOctreeToUniformGridFilter.h"
    "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/Graphics/vtkHyperStreamline.h"
    "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/Graphics/vtkIconGlyphFilter.h"
    "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/Graphics/vtkIdFilter.h"
    "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/Graphics/vtkImageDataGeometryFilter.h"
    "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/Graphics/vtkImageMarchingCubes.h"
    "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/Graphics/vtkImplicitTextureCoords.h"
    "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/Graphics/vtkInterpolateDataSetAttributes.h"
    "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/Graphics/vtkInterpolatingSubdivisionFilter.h"
    "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/Graphics/vtkKdTreeSelector.h"
    "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/Graphics/vtkLevelIdScalars.h"
    "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/Graphics/vtkLinearExtrusionFilter.h"
    "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/Graphics/vtkLinearSubdivisionFilter.h"
    "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/Graphics/vtkLineSource.h"
    "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/Graphics/vtkLinkEdgels.h"
    "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/Graphics/vtkLoopSubdivisionFilter.h"
    "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/Graphics/vtkMarchingContourFilter.h"
    "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/Graphics/vtkMarchingCubes.h"
    "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/Graphics/vtkMarchingSquares.h"
    "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/Graphics/vtkMaskFields.h"
    "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/Graphics/vtkMaskPoints.h"
    "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/Graphics/vtkMaskPolyData.h"
    "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/Graphics/vtkMassProperties.h"
    "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/Graphics/vtkMatrixMathFilter.h"
    "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/Graphics/vtkMergeCells.h"
    "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/Graphics/vtkMergeDataObjectFilter.h"
    "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/Graphics/vtkMergeFields.h"
    "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/Graphics/vtkMergeFilter.h"
    "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/Graphics/vtkMeshQuality.h"
    "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/Graphics/vtkModelMetadata.h"
    "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/Graphics/vtkModifiedBSPTree.h"
    "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/Graphics/vtkMultiBlockDataGroupFilter.h"
    "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/Graphics/vtkMultiBlockMergeFilter.h"
    "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/Graphics/vtkMultiThreshold.h"
    "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/Graphics/vtkOBBDicer.h"
    "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/Graphics/vtkOBBTree.h"
    "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/Graphics/vtkOutlineCornerFilter.h"
    "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/Graphics/vtkOutlineCornerSource.h"
    "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/Graphics/vtkOutlineFilter.h"
    "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/Graphics/vtkOutlineSource.h"
    "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/Graphics/vtkParametricFunctionSource.h"
    "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/Graphics/vtkPlaneSource.h"
    "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/Graphics/vtkPlatonicSolidSource.h"
    "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/Graphics/vtkPointDataToCellData.h"
    "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/Graphics/vtkPointSource.h"
    "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/Graphics/vtkPolyDataConnectivityFilter.h"
    "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/Graphics/vtkPolyDataNormals.h"
    "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/Graphics/vtkPolyDataPointSampler.h"
    "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/Graphics/vtkPolyDataStreamer.h"
    "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/Graphics/vtkPolyDataToReebGraphFilter.h"
    "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/Graphics/vtkProbeFilter.h"
    "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/Graphics/vtkProbePolyhedron.h"
    "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/Graphics/vtkProbeSelectedLocations.h"
    "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/Graphics/vtkProgrammableAttributeDataFilter.h"
    "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/Graphics/vtkProgrammableDataObjectSource.h"
    "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/Graphics/vtkProgrammableFilter.h"
    "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/Graphics/vtkProgrammableGlyphFilter.h"
    "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/Graphics/vtkProgrammableSource.h"
    "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/Graphics/vtkProjectedTexture.h"
    "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/Graphics/vtkQuadraturePointInterpolator.h"
    "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/Graphics/vtkQuadraturePointsGenerator.h"
    "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/Graphics/vtkQuadratureSchemeDictionaryGenerator.h"
    "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/Graphics/vtkQuadricClustering.h"
    "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/Graphics/vtkQuadricDecimation.h"
    "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/Graphics/vtkQuantizePolyDataPoints.h"
    "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/Graphics/vtkRandomAttributeGenerator.h"
    "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/Graphics/vtkRearrangeFields.h"
    "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/Graphics/vtkRectangularButtonSource.h"
    "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/Graphics/vtkRectilinearGridClip.h"
    "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/Graphics/vtkRectilinearGridGeometryFilter.h"
    "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/Graphics/vtkRectilinearGridToTetrahedra.h"
    "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/Graphics/vtkRectilinearSynchronizedTemplates.h"
    "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/Graphics/vtkRecursiveDividingCubes.h"
    "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/Graphics/vtkReebGraphSimplificationFilter.h"
    "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/Graphics/vtkReebGraphSurfaceSkeletonFilter.h"
    "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/Graphics/vtkReebGraphVolumeSkeletonFilter.h"
    "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/Graphics/vtkReflectionFilter.h"
    "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/Graphics/vtkRegularPolygonSource.h"
    "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/Graphics/vtkReverseSense.h"
    "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/Graphics/vtkRibbonFilter.h"
    "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/Graphics/vtkRotationalExtrusionFilter.h"
    "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/Graphics/vtkRotationFilter.h"
    "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/Graphics/vtkRuledSurfaceFilter.h"
    "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/Graphics/vtkSectorSource.h"
    "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/Graphics/vtkSelectEnclosedPoints.h"
    "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/Graphics/vtkSelectionSource.h"
    "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/Graphics/vtkSelectPolyData.h"
    "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/Graphics/vtkShrinkFilter.h"
    "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/Graphics/vtkShrinkPolyData.h"
    "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/Graphics/vtkSimpleElevationFilter.h"
    "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/Graphics/vtkSliceCubes.h"
    "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/Graphics/vtkSmoothPolyDataFilter.h"
    "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/Graphics/vtkSpatialRepresentationFilter.h"
    "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/Graphics/vtkSpherePuzzleArrows.h"
    "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/Graphics/vtkSpherePuzzle.h"
    "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/Graphics/vtkSphereSource.h"
    "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/Graphics/vtkSplineFilter.h"
    "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/Graphics/vtkSplitField.h"
    "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/Graphics/vtkStreamer.h"
    "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/Graphics/vtkStreamingTessellator.h"
    "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/Graphics/vtkStreamLine.h"
    "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/Graphics/vtkStreamPoints.h"
    "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/Graphics/vtkStreamTracer.h"
    "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/Graphics/vtkStripper.h"
    "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/Graphics/vtkStructuredGridClip.h"
    "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/Graphics/vtkStructuredGridGeometryFilter.h"
    "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/Graphics/vtkStructuredGridOutlineFilter.h"
    "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/Graphics/vtkStructuredPointsGeometryFilter.h"
    "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/Graphics/vtkSubdivideTetra.h"
    "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/Graphics/vtkSubPixelPositionEdgels.h"
    "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/Graphics/vtkSuperquadricSource.h"
    "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/Graphics/vtkSynchronizedTemplates2D.h"
    "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/Graphics/vtkSynchronizedTemplates3D.h"
    "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/Graphics/vtkSynchronizedTemplatesCutter3D.h"
    "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/Graphics/vtkTableBasedClipDataSet.h"
    "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/Graphics/vtkTableToPolyData.h"
    "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/Graphics/vtkTableToStructuredGrid.h"
    "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/Graphics/vtkTemporalPathLineFilter.h"
    "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/Graphics/vtkTemporalStatistics.h"
    "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/Graphics/vtkTensorGlyph.h"
    "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/Graphics/vtkTessellatorFilter.h"
    "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/Graphics/vtkTessellatedBoxSource.h"
    "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/Graphics/vtkTextSource.h"
    "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/Graphics/vtkTexturedSphereSource.h"
    "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/Graphics/vtkTextureMapToCylinder.h"
    "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/Graphics/vtkTextureMapToPlane.h"
    "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/Graphics/vtkTextureMapToSphere.h"
    "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/Graphics/vtkThreshold.h"
    "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/Graphics/vtkThresholdPoints.h"
    "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/Graphics/vtkThresholdTextureCoords.h"
    "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/Graphics/vtkTimeSourceExample.h"
    "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/Graphics/vtkTransformCoordinateSystems.h"
    "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/Graphics/vtkTransformFilter.h"
    "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/Graphics/vtkTransformPolyDataFilter.h"
    "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/Graphics/vtkTransformTextureCoords.h"
    "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/Graphics/vtkTriangleFilter.h"
    "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/Graphics/vtkTriangularTCoords.h"
    "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/Graphics/vtkTubeFilter.h"
    "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/Graphics/vtkUncertaintyTubeFilter.h"
    "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/Graphics/vtkUnstructuredGridGeometryFilter.h"
    "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/Graphics/vtkUnstructuredGridToReebGraphFilter.h"
    "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/Graphics/vtkVectorDot.h"
    "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/Graphics/vtkVectorNorm.h"
    "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/Graphics/vtkVertexGlyphFilter.h"
    "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/Graphics/vtkVolumeContourSpectrumFilter.h"
    "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/Graphics/vtkVoxelContoursToSurfaceFilter.h"
    "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/Graphics/vtkWarpLens.h"
    "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/Graphics/vtkWarpScalar.h"
    "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/Graphics/vtkWarpTo.h"
    "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/Graphics/vtkWarpVector.h"
    "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/Graphics/vtkWindowedSincPolyDataFilter.h"
    "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/Graphics/vtkYoungsMaterialInterface.h"
    )
endif()

if("x${CMAKE_INSTALL_COMPONENT}x" STREQUAL "xDevelopmentx" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/lib/vtk-5.8" TYPE FILE FILES "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/Utilities/InstallOnly/vtkGraphicsKit.cmake")
endif()

