#include "vtkGraphicsInstantiator.h"
  
extern vtkObject* vtkInstantiatorvtkAnnotationLinkNew();
extern vtkObject* vtkInstantiatorvtkAppendCompositeDataLeavesNew();
extern vtkObject* vtkInstantiatorvtkAppendFilterNew();
extern vtkObject* vtkInstantiatorvtkAppendPolyDataNew();
extern vtkObject* vtkInstantiatorvtkAppendSelectionNew();
extern vtkObject* vtkInstantiatorvtkArcSourceNew();
extern vtkObject* vtkInstantiatorvtkAreaContourSpectrumFilterNew();
extern vtkObject* vtkInstantiatorvtkArrayCalculatorNew();
extern vtkObject* vtkInstantiatorvtkArrowSourceNew();
extern vtkObject* vtkInstantiatorvtkAssignAttributeNew();
extern vtkObject* vtkInstantiatorvtkAttributeDataToFieldDataFilterNew();
extern vtkObject* vtkInstantiatorvtkAxesNew();
extern vtkObject* vtkInstantiatorvtkBandedPolyDataContourFilterNew();
extern vtkObject* vtkInstantiatorvtkBlankStructuredGridNew();
extern vtkObject* vtkInstantiatorvtkBlankStructuredGridWithImageNew();
extern vtkObject* vtkInstantiatorvtkBlockIdScalarsNew();
extern vtkObject* vtkInstantiatorvtkBoxClipDataSetNew();
extern vtkObject* vtkInstantiatorvtkBrownianPointsNew();
extern vtkObject* vtkInstantiatorvtkButterflySubdivisionFilterNew();
extern vtkObject* vtkInstantiatorvtkCellCentersNew();
extern vtkObject* vtkInstantiatorvtkCellDataToPointDataNew();
extern vtkObject* vtkInstantiatorvtkCellDerivativesNew();
extern vtkObject* vtkInstantiatorvtkCellLocatorInterpolatedVelocityFieldNew();
extern vtkObject* vtkInstantiatorvtkCellQualityNew();
extern vtkObject* vtkInstantiatorvtkCleanPolyDataNew();
extern vtkObject* vtkInstantiatorvtkClipClosedSurfaceNew();
extern vtkObject* vtkInstantiatorvtkClipConvexPolyDataNew();
extern vtkObject* vtkInstantiatorvtkClipDataSetNew();
extern vtkObject* vtkInstantiatorvtkClipHyperOctreeNew();
extern vtkObject* vtkInstantiatorvtkClipPolyDataNew();
extern vtkObject* vtkInstantiatorvtkClipVolumeNew();
extern vtkObject* vtkInstantiatorvtkCoincidentPointsNew();
extern vtkObject* vtkInstantiatorvtkCompositeDataGeometryFilterNew();
extern vtkObject* vtkInstantiatorvtkCompositeDataProbeFilterNew();
extern vtkObject* vtkInstantiatorvtkConeSourceNew();
extern vtkObject* vtkInstantiatorvtkConnectivityFilterNew();
extern vtkObject* vtkInstantiatorvtkContourFilterNew();
extern vtkObject* vtkInstantiatorvtkContourGridNew();
extern vtkObject* vtkInstantiatorvtkConvertSelectionNew();
extern vtkObject* vtkInstantiatorvtkCubeSourceNew();
extern vtkObject* vtkInstantiatorvtkCursor2DNew();
extern vtkObject* vtkInstantiatorvtkCursor3DNew();
extern vtkObject* vtkInstantiatorvtkCurvaturesNew();
extern vtkObject* vtkInstantiatorvtkCutterNew();
extern vtkObject* vtkInstantiatorvtkCylinderSourceNew();
extern vtkObject* vtkInstantiatorvtkDashedStreamLineNew();
extern vtkObject* vtkInstantiatorvtkDataObjectGeneratorNew();
extern vtkObject* vtkInstantiatorvtkDataObjectToDataSetFilterNew();
extern vtkObject* vtkInstantiatorvtkDataSetEdgeSubdivisionCriterionNew();
extern vtkObject* vtkInstantiatorvtkDataSetGradientNew();
extern vtkObject* vtkInstantiatorvtkDataSetGradientPrecomputeNew();
extern vtkObject* vtkInstantiatorvtkDataSetSurfaceFilterNew();
extern vtkObject* vtkInstantiatorvtkDataSetToDataObjectFilterNew();
extern vtkObject* vtkInstantiatorvtkDataSetTriangleFilterNew();
extern vtkObject* vtkInstantiatorvtkDecimatePolylineFilterNew();
extern vtkObject* vtkInstantiatorvtkDecimateProNew();
extern vtkObject* vtkInstantiatorvtkDelaunay2DNew();
extern vtkObject* vtkInstantiatorvtkDelaunay3DNew();
extern vtkObject* vtkInstantiatorvtkDensifyPolyDataNew();
extern vtkObject* vtkInstantiatorvtkDijkstraGraphGeodesicPathNew();
extern vtkObject* vtkInstantiatorvtkDijkstraImageGeodesicPathNew();
extern vtkObject* vtkInstantiatorvtkDiscreteMarchingCubesNew();
extern vtkObject* vtkInstantiatorvtkDiskSourceNew();
extern vtkObject* vtkInstantiatorvtkEdgePointsNew();
extern vtkObject* vtkInstantiatorvtkElevationFilterNew();
extern vtkObject* vtkInstantiatorvtkEllipticalButtonSourceNew();
extern vtkObject* vtkInstantiatorvtkExtractArraysOverTimeNew();
extern vtkObject* vtkInstantiatorvtkExtractBlockNew();
extern vtkObject* vtkInstantiatorvtkExtractCellsNew();
extern vtkObject* vtkInstantiatorvtkExtractDataOverTimeNew();
extern vtkObject* vtkInstantiatorvtkExtractDataSetsNew();
extern vtkObject* vtkInstantiatorvtkExtractEdgesNew();
extern vtkObject* vtkInstantiatorvtkExtractGeometryNew();
extern vtkObject* vtkInstantiatorvtkExtractGridNew();
extern vtkObject* vtkInstantiatorvtkExtractLevelNew();
extern vtkObject* vtkInstantiatorvtkExtractPolyDataGeometryNew();
extern vtkObject* vtkInstantiatorvtkExtractRectilinearGridNew();
extern vtkObject* vtkInstantiatorvtkExtractSelectedBlockNew();
extern vtkObject* vtkInstantiatorvtkExtractSelectedFrustumNew();
extern vtkObject* vtkInstantiatorvtkExtractSelectedIdsNew();
extern vtkObject* vtkInstantiatorvtkExtractSelectedLocationsNew();
extern vtkObject* vtkInstantiatorvtkExtractSelectedPolyDataIdsNew();
extern vtkObject* vtkInstantiatorvtkExtractSelectedRowsNew();
extern vtkObject* vtkInstantiatorvtkExtractSelectedThresholdsNew();
extern vtkObject* vtkInstantiatorvtkExtractSelectionNew();
extern vtkObject* vtkInstantiatorvtkExtractTemporalFieldDataNew();
extern vtkObject* vtkInstantiatorvtkExtractTensorComponentsNew();
extern vtkObject* vtkInstantiatorvtkExtractUnstructuredGridNew();
extern vtkObject* vtkInstantiatorvtkExtractVectorComponentsNew();
extern vtkObject* vtkInstantiatorvtkFeatureEdgesNew();
extern vtkObject* vtkInstantiatorvtkFieldDataToAttributeDataFilterNew();
extern vtkObject* vtkInstantiatorvtkFillHolesFilterNew();
extern vtkObject* vtkInstantiatorvtkFrustumSourceNew();
extern vtkObject* vtkInstantiatorvtkGeometryFilterNew();
extern vtkObject* vtkInstantiatorvtkGlyph2DNew();
extern vtkObject* vtkInstantiatorvtkGlyph3DNew();
extern vtkObject* vtkInstantiatorvtkGlyphSource2DNew();
extern vtkObject* vtkInstantiatorvtkGradientFilterNew();
extern vtkObject* vtkInstantiatorvtkGraphLayoutFilterNew();
extern vtkObject* vtkInstantiatorvtkGraphToPointsNew();
extern vtkObject* vtkInstantiatorvtkGraphToPolyDataNew();
extern vtkObject* vtkInstantiatorvtkGridSynchronizedTemplates3DNew();
extern vtkObject* vtkInstantiatorvtkHedgeHogNew();
extern vtkObject* vtkInstantiatorvtkHierarchicalDataExtractDataSetsNew();
extern vtkObject* vtkInstantiatorvtkHierarchicalDataExtractLevelNew();
extern vtkObject* vtkInstantiatorvtkHierarchicalDataLevelFilterNew();
extern vtkObject* vtkInstantiatorvtkHierarchicalDataSetGeometryFilterNew();
extern vtkObject* vtkInstantiatorvtkHullNew();
extern vtkObject* vtkInstantiatorvtkHyperOctreeClipCutPointsGrabberNew();
extern vtkObject* vtkInstantiatorvtkHyperOctreeContourFilterNew();
extern vtkObject* vtkInstantiatorvtkHyperOctreeCutterNew();
extern vtkObject* vtkInstantiatorvtkHyperOctreeDepthNew();
extern vtkObject* vtkInstantiatorvtkHyperOctreeDualGridContourFilterNew();
extern vtkObject* vtkInstantiatorvtkHyperOctreeFractalSourceNew();
extern vtkObject* vtkInstantiatorvtkHyperOctreeLimiterNew();
extern vtkObject* vtkInstantiatorvtkHyperOctreeSampleFunctionNew();
extern vtkObject* vtkInstantiatorvtkHyperOctreeSurfaceFilterNew();
extern vtkObject* vtkInstantiatorvtkHyperOctreeToUniformGridFilterNew();
extern vtkObject* vtkInstantiatorvtkHyperStreamlineNew();
extern vtkObject* vtkInstantiatorvtkIconGlyphFilterNew();
extern vtkObject* vtkInstantiatorvtkIdFilterNew();
extern vtkObject* vtkInstantiatorvtkImageDataGeometryFilterNew();
extern vtkObject* vtkInstantiatorvtkImageMarchingCubesNew();
extern vtkObject* vtkInstantiatorvtkImplicitTextureCoordsNew();
extern vtkObject* vtkInstantiatorvtkInterpolateDataSetAttributesNew();
extern vtkObject* vtkInstantiatorvtkKdTreeSelectorNew();
extern vtkObject* vtkInstantiatorvtkLevelIdScalarsNew();
extern vtkObject* vtkInstantiatorvtkLinearExtrusionFilterNew();
extern vtkObject* vtkInstantiatorvtkLinearSubdivisionFilterNew();
extern vtkObject* vtkInstantiatorvtkLineSourceNew();
extern vtkObject* vtkInstantiatorvtkLinkEdgelsNew();
extern vtkObject* vtkInstantiatorvtkLoopSubdivisionFilterNew();
extern vtkObject* vtkInstantiatorvtkMarchingContourFilterNew();
extern vtkObject* vtkInstantiatorvtkMarchingCubesNew();
extern vtkObject* vtkInstantiatorvtkMarchingSquaresNew();
extern vtkObject* vtkInstantiatorvtkMaskFieldsNew();
extern vtkObject* vtkInstantiatorvtkMaskPointsNew();
extern vtkObject* vtkInstantiatorvtkMaskPolyDataNew();
extern vtkObject* vtkInstantiatorvtkMassPropertiesNew();
extern vtkObject* vtkInstantiatorvtkMatrixMathFilterNew();
extern vtkObject* vtkInstantiatorvtkMergeCellsNew();
extern vtkObject* vtkInstantiatorvtkMergeDataObjectFilterNew();
extern vtkObject* vtkInstantiatorvtkMergeFieldsNew();
extern vtkObject* vtkInstantiatorvtkMergeFilterNew();
extern vtkObject* vtkInstantiatorvtkMeshQualityNew();
extern vtkObject* vtkInstantiatorvtkModelMetadataNew();
extern vtkObject* vtkInstantiatorvtkModifiedBSPTreeNew();
extern vtkObject* vtkInstantiatorvtkMultiBlockDataGroupFilterNew();
extern vtkObject* vtkInstantiatorvtkMultiBlockMergeFilterNew();
extern vtkObject* vtkInstantiatorvtkMultiThresholdNew();
extern vtkObject* vtkInstantiatorvtkOBBDicerNew();
extern vtkObject* vtkInstantiatorvtkOBBTreeNew();
extern vtkObject* vtkInstantiatorvtkOutlineCornerFilterNew();
extern vtkObject* vtkInstantiatorvtkOutlineCornerSourceNew();
extern vtkObject* vtkInstantiatorvtkOutlineFilterNew();
extern vtkObject* vtkInstantiatorvtkOutlineSourceNew();
extern vtkObject* vtkInstantiatorvtkParametricFunctionSourceNew();
extern vtkObject* vtkInstantiatorvtkPlaneSourceNew();
extern vtkObject* vtkInstantiatorvtkPlatonicSolidSourceNew();
extern vtkObject* vtkInstantiatorvtkPointDataToCellDataNew();
extern vtkObject* vtkInstantiatorvtkPointSourceNew();
extern vtkObject* vtkInstantiatorvtkPolyDataConnectivityFilterNew();
extern vtkObject* vtkInstantiatorvtkPolyDataNormalsNew();
extern vtkObject* vtkInstantiatorvtkPolyDataPointSamplerNew();
extern vtkObject* vtkInstantiatorvtkPolyDataStreamerNew();
extern vtkObject* vtkInstantiatorvtkPolyDataToReebGraphFilterNew();
extern vtkObject* vtkInstantiatorvtkProbeFilterNew();
extern vtkObject* vtkInstantiatorvtkProbePolyhedronNew();
extern vtkObject* vtkInstantiatorvtkProbeSelectedLocationsNew();
extern vtkObject* vtkInstantiatorvtkProgrammableAttributeDataFilterNew();
extern vtkObject* vtkInstantiatorvtkProgrammableDataObjectSourceNew();
extern vtkObject* vtkInstantiatorvtkProgrammableFilterNew();
extern vtkObject* vtkInstantiatorvtkProgrammableGlyphFilterNew();
extern vtkObject* vtkInstantiatorvtkProgrammableSourceNew();
extern vtkObject* vtkInstantiatorvtkProjectedTextureNew();
extern vtkObject* vtkInstantiatorvtkQuadraturePointInterpolatorNew();
extern vtkObject* vtkInstantiatorvtkQuadraturePointsGeneratorNew();
extern vtkObject* vtkInstantiatorvtkQuadratureSchemeDictionaryGeneratorNew();
extern vtkObject* vtkInstantiatorvtkQuadricClusteringNew();
extern vtkObject* vtkInstantiatorvtkQuadricDecimationNew();
extern vtkObject* vtkInstantiatorvtkQuantizePolyDataPointsNew();
extern vtkObject* vtkInstantiatorvtkRandomAttributeGeneratorNew();
extern vtkObject* vtkInstantiatorvtkRearrangeFieldsNew();
extern vtkObject* vtkInstantiatorvtkRectangularButtonSourceNew();
extern vtkObject* vtkInstantiatorvtkRectilinearGridClipNew();
extern vtkObject* vtkInstantiatorvtkRectilinearGridGeometryFilterNew();
extern vtkObject* vtkInstantiatorvtkRectilinearGridToTetrahedraNew();
extern vtkObject* vtkInstantiatorvtkRectilinearSynchronizedTemplatesNew();
extern vtkObject* vtkInstantiatorvtkRecursiveDividingCubesNew();
extern vtkObject* vtkInstantiatorvtkReebGraphSimplificationFilterNew();
extern vtkObject* vtkInstantiatorvtkReebGraphSurfaceSkeletonFilterNew();
extern vtkObject* vtkInstantiatorvtkReebGraphVolumeSkeletonFilterNew();
extern vtkObject* vtkInstantiatorvtkReflectionFilterNew();
extern vtkObject* vtkInstantiatorvtkRegularPolygonSourceNew();
extern vtkObject* vtkInstantiatorvtkReverseSenseNew();
extern vtkObject* vtkInstantiatorvtkRibbonFilterNew();
extern vtkObject* vtkInstantiatorvtkRotationalExtrusionFilterNew();
extern vtkObject* vtkInstantiatorvtkRotationFilterNew();
extern vtkObject* vtkInstantiatorvtkRuledSurfaceFilterNew();
extern vtkObject* vtkInstantiatorvtkSectorSourceNew();
extern vtkObject* vtkInstantiatorvtkSelectEnclosedPointsNew();
extern vtkObject* vtkInstantiatorvtkSelectionSourceNew();
extern vtkObject* vtkInstantiatorvtkSelectPolyDataNew();
extern vtkObject* vtkInstantiatorvtkShrinkFilterNew();
extern vtkObject* vtkInstantiatorvtkShrinkPolyDataNew();
extern vtkObject* vtkInstantiatorvtkSimpleElevationFilterNew();
extern vtkObject* vtkInstantiatorvtkSliceCubesNew();
extern vtkObject* vtkInstantiatorvtkSmoothPolyDataFilterNew();
extern vtkObject* vtkInstantiatorvtkSpatialRepresentationFilterNew();
extern vtkObject* vtkInstantiatorvtkSpherePuzzleArrowsNew();
extern vtkObject* vtkInstantiatorvtkSpherePuzzleNew();
extern vtkObject* vtkInstantiatorvtkSphereSourceNew();
extern vtkObject* vtkInstantiatorvtkSplineFilterNew();
extern vtkObject* vtkInstantiatorvtkSplitFieldNew();
extern vtkObject* vtkInstantiatorvtkStreamingTessellatorNew();
extern vtkObject* vtkInstantiatorvtkStreamLineNew();
extern vtkObject* vtkInstantiatorvtkStreamPointsNew();
extern vtkObject* vtkInstantiatorvtkStreamTracerNew();
extern vtkObject* vtkInstantiatorvtkStripperNew();
extern vtkObject* vtkInstantiatorvtkStructuredGridClipNew();
extern vtkObject* vtkInstantiatorvtkStructuredGridGeometryFilterNew();
extern vtkObject* vtkInstantiatorvtkStructuredGridOutlineFilterNew();
extern vtkObject* vtkInstantiatorvtkStructuredPointsGeometryFilterNew();
extern vtkObject* vtkInstantiatorvtkSubdivideTetraNew();
extern vtkObject* vtkInstantiatorvtkSubPixelPositionEdgelsNew();
extern vtkObject* vtkInstantiatorvtkSuperquadricSourceNew();
extern vtkObject* vtkInstantiatorvtkSynchronizedTemplates2DNew();
extern vtkObject* vtkInstantiatorvtkSynchronizedTemplates3DNew();
extern vtkObject* vtkInstantiatorvtkSynchronizedTemplatesCutter3DNew();
extern vtkObject* vtkInstantiatorvtkTableBasedClipDataSetNew();
extern vtkObject* vtkInstantiatorvtkTableToPolyDataNew();
extern vtkObject* vtkInstantiatorvtkTableToStructuredGridNew();
extern vtkObject* vtkInstantiatorvtkTemporalPathLineFilterNew();
extern vtkObject* vtkInstantiatorvtkTemporalStatisticsNew();
extern vtkObject* vtkInstantiatorvtkTensorGlyphNew();
extern vtkObject* vtkInstantiatorvtkTessellatorFilterNew();
extern vtkObject* vtkInstantiatorvtkTessellatedBoxSourceNew();
extern vtkObject* vtkInstantiatorvtkTextSourceNew();
extern vtkObject* vtkInstantiatorvtkTexturedSphereSourceNew();
extern vtkObject* vtkInstantiatorvtkTextureMapToCylinderNew();
extern vtkObject* vtkInstantiatorvtkTextureMapToPlaneNew();
extern vtkObject* vtkInstantiatorvtkTextureMapToSphereNew();
extern vtkObject* vtkInstantiatorvtkThresholdNew();
extern vtkObject* vtkInstantiatorvtkThresholdPointsNew();
extern vtkObject* vtkInstantiatorvtkThresholdTextureCoordsNew();
extern vtkObject* vtkInstantiatorvtkTimeSourceExampleNew();
extern vtkObject* vtkInstantiatorvtkTransformCoordinateSystemsNew();
extern vtkObject* vtkInstantiatorvtkTransformFilterNew();
extern vtkObject* vtkInstantiatorvtkTransformPolyDataFilterNew();
extern vtkObject* vtkInstantiatorvtkTransformTextureCoordsNew();
extern vtkObject* vtkInstantiatorvtkTriangleFilterNew();
extern vtkObject* vtkInstantiatorvtkTriangularTCoordsNew();
extern vtkObject* vtkInstantiatorvtkTubeFilterNew();
extern vtkObject* vtkInstantiatorvtkUncertaintyTubeFilterNew();
extern vtkObject* vtkInstantiatorvtkUnstructuredGridGeometryFilterNew();
extern vtkObject* vtkInstantiatorvtkUnstructuredGridToReebGraphFilterNew();
extern vtkObject* vtkInstantiatorvtkVectorDotNew();
extern vtkObject* vtkInstantiatorvtkVectorNormNew();
extern vtkObject* vtkInstantiatorvtkVertexGlyphFilterNew();
extern vtkObject* vtkInstantiatorvtkVolumeContourSpectrumFilterNew();
extern vtkObject* vtkInstantiatorvtkVoxelContoursToSurfaceFilterNew();
extern vtkObject* vtkInstantiatorvtkWarpLensNew();
extern vtkObject* vtkInstantiatorvtkWarpScalarNew();
extern vtkObject* vtkInstantiatorvtkWarpToNew();
extern vtkObject* vtkInstantiatorvtkWarpVectorNew();
extern vtkObject* vtkInstantiatorvtkWindowedSincPolyDataFilterNew();
extern vtkObject* vtkInstantiatorvtkYoungsMaterialInterfaceNew();


  
void vtkGraphicsInstantiator::ClassInitialize()
{
  
  vtkInstantiator::RegisterInstantiator("vtkAnnotationLink", vtkInstantiatorvtkAnnotationLinkNew);
  vtkInstantiator::RegisterInstantiator("vtkAppendCompositeDataLeaves", vtkInstantiatorvtkAppendCompositeDataLeavesNew);
  vtkInstantiator::RegisterInstantiator("vtkAppendFilter", vtkInstantiatorvtkAppendFilterNew);
  vtkInstantiator::RegisterInstantiator("vtkAppendPolyData", vtkInstantiatorvtkAppendPolyDataNew);
  vtkInstantiator::RegisterInstantiator("vtkAppendSelection", vtkInstantiatorvtkAppendSelectionNew);
  vtkInstantiator::RegisterInstantiator("vtkArcSource", vtkInstantiatorvtkArcSourceNew);
  vtkInstantiator::RegisterInstantiator("vtkAreaContourSpectrumFilter", vtkInstantiatorvtkAreaContourSpectrumFilterNew);
  vtkInstantiator::RegisterInstantiator("vtkArrayCalculator", vtkInstantiatorvtkArrayCalculatorNew);
  vtkInstantiator::RegisterInstantiator("vtkArrowSource", vtkInstantiatorvtkArrowSourceNew);
  vtkInstantiator::RegisterInstantiator("vtkAssignAttribute", vtkInstantiatorvtkAssignAttributeNew);
  vtkInstantiator::RegisterInstantiator("vtkAttributeDataToFieldDataFilter", vtkInstantiatorvtkAttributeDataToFieldDataFilterNew);
  vtkInstantiator::RegisterInstantiator("vtkAxes", vtkInstantiatorvtkAxesNew);
  vtkInstantiator::RegisterInstantiator("vtkBandedPolyDataContourFilter", vtkInstantiatorvtkBandedPolyDataContourFilterNew);
  vtkInstantiator::RegisterInstantiator("vtkBlankStructuredGrid", vtkInstantiatorvtkBlankStructuredGridNew);
  vtkInstantiator::RegisterInstantiator("vtkBlankStructuredGridWithImage", vtkInstantiatorvtkBlankStructuredGridWithImageNew);
  vtkInstantiator::RegisterInstantiator("vtkBlockIdScalars", vtkInstantiatorvtkBlockIdScalarsNew);
  vtkInstantiator::RegisterInstantiator("vtkBoxClipDataSet", vtkInstantiatorvtkBoxClipDataSetNew);
  vtkInstantiator::RegisterInstantiator("vtkBrownianPoints", vtkInstantiatorvtkBrownianPointsNew);
  vtkInstantiator::RegisterInstantiator("vtkButterflySubdivisionFilter", vtkInstantiatorvtkButterflySubdivisionFilterNew);
  vtkInstantiator::RegisterInstantiator("vtkCellCenters", vtkInstantiatorvtkCellCentersNew);
  vtkInstantiator::RegisterInstantiator("vtkCellDataToPointData", vtkInstantiatorvtkCellDataToPointDataNew);
  vtkInstantiator::RegisterInstantiator("vtkCellDerivatives", vtkInstantiatorvtkCellDerivativesNew);
  vtkInstantiator::RegisterInstantiator("vtkCellLocatorInterpolatedVelocityField", vtkInstantiatorvtkCellLocatorInterpolatedVelocityFieldNew);
  vtkInstantiator::RegisterInstantiator("vtkCellQuality", vtkInstantiatorvtkCellQualityNew);
  vtkInstantiator::RegisterInstantiator("vtkCleanPolyData", vtkInstantiatorvtkCleanPolyDataNew);
  vtkInstantiator::RegisterInstantiator("vtkClipClosedSurface", vtkInstantiatorvtkClipClosedSurfaceNew);
  vtkInstantiator::RegisterInstantiator("vtkClipConvexPolyData", vtkInstantiatorvtkClipConvexPolyDataNew);
  vtkInstantiator::RegisterInstantiator("vtkClipDataSet", vtkInstantiatorvtkClipDataSetNew);
  vtkInstantiator::RegisterInstantiator("vtkClipHyperOctree", vtkInstantiatorvtkClipHyperOctreeNew);
  vtkInstantiator::RegisterInstantiator("vtkClipPolyData", vtkInstantiatorvtkClipPolyDataNew);
  vtkInstantiator::RegisterInstantiator("vtkClipVolume", vtkInstantiatorvtkClipVolumeNew);
  vtkInstantiator::RegisterInstantiator("vtkCoincidentPoints", vtkInstantiatorvtkCoincidentPointsNew);
  vtkInstantiator::RegisterInstantiator("vtkCompositeDataGeometryFilter", vtkInstantiatorvtkCompositeDataGeometryFilterNew);
  vtkInstantiator::RegisterInstantiator("vtkCompositeDataProbeFilter", vtkInstantiatorvtkCompositeDataProbeFilterNew);
  vtkInstantiator::RegisterInstantiator("vtkConeSource", vtkInstantiatorvtkConeSourceNew);
  vtkInstantiator::RegisterInstantiator("vtkConnectivityFilter", vtkInstantiatorvtkConnectivityFilterNew);
  vtkInstantiator::RegisterInstantiator("vtkContourFilter", vtkInstantiatorvtkContourFilterNew);
  vtkInstantiator::RegisterInstantiator("vtkContourGrid", vtkInstantiatorvtkContourGridNew);
  vtkInstantiator::RegisterInstantiator("vtkConvertSelection", vtkInstantiatorvtkConvertSelectionNew);
  vtkInstantiator::RegisterInstantiator("vtkCubeSource", vtkInstantiatorvtkCubeSourceNew);
  vtkInstantiator::RegisterInstantiator("vtkCursor2D", vtkInstantiatorvtkCursor2DNew);
  vtkInstantiator::RegisterInstantiator("vtkCursor3D", vtkInstantiatorvtkCursor3DNew);
  vtkInstantiator::RegisterInstantiator("vtkCurvatures", vtkInstantiatorvtkCurvaturesNew);
  vtkInstantiator::RegisterInstantiator("vtkCutter", vtkInstantiatorvtkCutterNew);
  vtkInstantiator::RegisterInstantiator("vtkCylinderSource", vtkInstantiatorvtkCylinderSourceNew);
  vtkInstantiator::RegisterInstantiator("vtkDashedStreamLine", vtkInstantiatorvtkDashedStreamLineNew);
  vtkInstantiator::RegisterInstantiator("vtkDataObjectGenerator", vtkInstantiatorvtkDataObjectGeneratorNew);
  vtkInstantiator::RegisterInstantiator("vtkDataObjectToDataSetFilter", vtkInstantiatorvtkDataObjectToDataSetFilterNew);
  vtkInstantiator::RegisterInstantiator("vtkDataSetEdgeSubdivisionCriterion", vtkInstantiatorvtkDataSetEdgeSubdivisionCriterionNew);
  vtkInstantiator::RegisterInstantiator("vtkDataSetGradient", vtkInstantiatorvtkDataSetGradientNew);
  vtkInstantiator::RegisterInstantiator("vtkDataSetGradientPrecompute", vtkInstantiatorvtkDataSetGradientPrecomputeNew);
  vtkInstantiator::RegisterInstantiator("vtkDataSetSurfaceFilter", vtkInstantiatorvtkDataSetSurfaceFilterNew);
  vtkInstantiator::RegisterInstantiator("vtkDataSetToDataObjectFilter", vtkInstantiatorvtkDataSetToDataObjectFilterNew);
  vtkInstantiator::RegisterInstantiator("vtkDataSetTriangleFilter", vtkInstantiatorvtkDataSetTriangleFilterNew);
  vtkInstantiator::RegisterInstantiator("vtkDecimatePolylineFilter", vtkInstantiatorvtkDecimatePolylineFilterNew);
  vtkInstantiator::RegisterInstantiator("vtkDecimatePro", vtkInstantiatorvtkDecimateProNew);
  vtkInstantiator::RegisterInstantiator("vtkDelaunay2D", vtkInstantiatorvtkDelaunay2DNew);
  vtkInstantiator::RegisterInstantiator("vtkDelaunay3D", vtkInstantiatorvtkDelaunay3DNew);
  vtkInstantiator::RegisterInstantiator("vtkDensifyPolyData", vtkInstantiatorvtkDensifyPolyDataNew);
  vtkInstantiator::RegisterInstantiator("vtkDijkstraGraphGeodesicPath", vtkInstantiatorvtkDijkstraGraphGeodesicPathNew);
  vtkInstantiator::RegisterInstantiator("vtkDijkstraImageGeodesicPath", vtkInstantiatorvtkDijkstraImageGeodesicPathNew);
  vtkInstantiator::RegisterInstantiator("vtkDiscreteMarchingCubes", vtkInstantiatorvtkDiscreteMarchingCubesNew);
  vtkInstantiator::RegisterInstantiator("vtkDiskSource", vtkInstantiatorvtkDiskSourceNew);
  vtkInstantiator::RegisterInstantiator("vtkEdgePoints", vtkInstantiatorvtkEdgePointsNew);
  vtkInstantiator::RegisterInstantiator("vtkElevationFilter", vtkInstantiatorvtkElevationFilterNew);
  vtkInstantiator::RegisterInstantiator("vtkEllipticalButtonSource", vtkInstantiatorvtkEllipticalButtonSourceNew);
  vtkInstantiator::RegisterInstantiator("vtkExtractArraysOverTime", vtkInstantiatorvtkExtractArraysOverTimeNew);
  vtkInstantiator::RegisterInstantiator("vtkExtractBlock", vtkInstantiatorvtkExtractBlockNew);
  vtkInstantiator::RegisterInstantiator("vtkExtractCells", vtkInstantiatorvtkExtractCellsNew);
  vtkInstantiator::RegisterInstantiator("vtkExtractDataOverTime", vtkInstantiatorvtkExtractDataOverTimeNew);
  vtkInstantiator::RegisterInstantiator("vtkExtractDataSets", vtkInstantiatorvtkExtractDataSetsNew);
  vtkInstantiator::RegisterInstantiator("vtkExtractEdges", vtkInstantiatorvtkExtractEdgesNew);
  vtkInstantiator::RegisterInstantiator("vtkExtractGeometry", vtkInstantiatorvtkExtractGeometryNew);
  vtkInstantiator::RegisterInstantiator("vtkExtractGrid", vtkInstantiatorvtkExtractGridNew);
  vtkInstantiator::RegisterInstantiator("vtkExtractLevel", vtkInstantiatorvtkExtractLevelNew);
  vtkInstantiator::RegisterInstantiator("vtkExtractPolyDataGeometry", vtkInstantiatorvtkExtractPolyDataGeometryNew);
  vtkInstantiator::RegisterInstantiator("vtkExtractRectilinearGrid", vtkInstantiatorvtkExtractRectilinearGridNew);
  vtkInstantiator::RegisterInstantiator("vtkExtractSelectedBlock", vtkInstantiatorvtkExtractSelectedBlockNew);
  vtkInstantiator::RegisterInstantiator("vtkExtractSelectedFrustum", vtkInstantiatorvtkExtractSelectedFrustumNew);
  vtkInstantiator::RegisterInstantiator("vtkExtractSelectedIds", vtkInstantiatorvtkExtractSelectedIdsNew);
  vtkInstantiator::RegisterInstantiator("vtkExtractSelectedLocations", vtkInstantiatorvtkExtractSelectedLocationsNew);
  vtkInstantiator::RegisterInstantiator("vtkExtractSelectedPolyDataIds", vtkInstantiatorvtkExtractSelectedPolyDataIdsNew);
  vtkInstantiator::RegisterInstantiator("vtkExtractSelectedRows", vtkInstantiatorvtkExtractSelectedRowsNew);
  vtkInstantiator::RegisterInstantiator("vtkExtractSelectedThresholds", vtkInstantiatorvtkExtractSelectedThresholdsNew);
  vtkInstantiator::RegisterInstantiator("vtkExtractSelection", vtkInstantiatorvtkExtractSelectionNew);
  vtkInstantiator::RegisterInstantiator("vtkExtractTemporalFieldData", vtkInstantiatorvtkExtractTemporalFieldDataNew);
  vtkInstantiator::RegisterInstantiator("vtkExtractTensorComponents", vtkInstantiatorvtkExtractTensorComponentsNew);
  vtkInstantiator::RegisterInstantiator("vtkExtractUnstructuredGrid", vtkInstantiatorvtkExtractUnstructuredGridNew);
  vtkInstantiator::RegisterInstantiator("vtkExtractVectorComponents", vtkInstantiatorvtkExtractVectorComponentsNew);
  vtkInstantiator::RegisterInstantiator("vtkFeatureEdges", vtkInstantiatorvtkFeatureEdgesNew);
  vtkInstantiator::RegisterInstantiator("vtkFieldDataToAttributeDataFilter", vtkInstantiatorvtkFieldDataToAttributeDataFilterNew);
  vtkInstantiator::RegisterInstantiator("vtkFillHolesFilter", vtkInstantiatorvtkFillHolesFilterNew);
  vtkInstantiator::RegisterInstantiator("vtkFrustumSource", vtkInstantiatorvtkFrustumSourceNew);
  vtkInstantiator::RegisterInstantiator("vtkGeometryFilter", vtkInstantiatorvtkGeometryFilterNew);
  vtkInstantiator::RegisterInstantiator("vtkGlyph2D", vtkInstantiatorvtkGlyph2DNew);
  vtkInstantiator::RegisterInstantiator("vtkGlyph3D", vtkInstantiatorvtkGlyph3DNew);
  vtkInstantiator::RegisterInstantiator("vtkGlyphSource2D", vtkInstantiatorvtkGlyphSource2DNew);
  vtkInstantiator::RegisterInstantiator("vtkGradientFilter", vtkInstantiatorvtkGradientFilterNew);
  vtkInstantiator::RegisterInstantiator("vtkGraphLayoutFilter", vtkInstantiatorvtkGraphLayoutFilterNew);
  vtkInstantiator::RegisterInstantiator("vtkGraphToPoints", vtkInstantiatorvtkGraphToPointsNew);
  vtkInstantiator::RegisterInstantiator("vtkGraphToPolyData", vtkInstantiatorvtkGraphToPolyDataNew);
  vtkInstantiator::RegisterInstantiator("vtkGridSynchronizedTemplates3D", vtkInstantiatorvtkGridSynchronizedTemplates3DNew);
  vtkInstantiator::RegisterInstantiator("vtkHedgeHog", vtkInstantiatorvtkHedgeHogNew);
  vtkInstantiator::RegisterInstantiator("vtkHierarchicalDataExtractDataSets", vtkInstantiatorvtkHierarchicalDataExtractDataSetsNew);
  vtkInstantiator::RegisterInstantiator("vtkHierarchicalDataExtractLevel", vtkInstantiatorvtkHierarchicalDataExtractLevelNew);
  vtkInstantiator::RegisterInstantiator("vtkHierarchicalDataLevelFilter", vtkInstantiatorvtkHierarchicalDataLevelFilterNew);
  vtkInstantiator::RegisterInstantiator("vtkHierarchicalDataSetGeometryFilter", vtkInstantiatorvtkHierarchicalDataSetGeometryFilterNew);
  vtkInstantiator::RegisterInstantiator("vtkHull", vtkInstantiatorvtkHullNew);
  vtkInstantiator::RegisterInstantiator("vtkHyperOctreeClipCutPointsGrabber", vtkInstantiatorvtkHyperOctreeClipCutPointsGrabberNew);
  vtkInstantiator::RegisterInstantiator("vtkHyperOctreeContourFilter", vtkInstantiatorvtkHyperOctreeContourFilterNew);
  vtkInstantiator::RegisterInstantiator("vtkHyperOctreeCutter", vtkInstantiatorvtkHyperOctreeCutterNew);
  vtkInstantiator::RegisterInstantiator("vtkHyperOctreeDepth", vtkInstantiatorvtkHyperOctreeDepthNew);
  vtkInstantiator::RegisterInstantiator("vtkHyperOctreeDualGridContourFilter", vtkInstantiatorvtkHyperOctreeDualGridContourFilterNew);
  vtkInstantiator::RegisterInstantiator("vtkHyperOctreeFractalSource", vtkInstantiatorvtkHyperOctreeFractalSourceNew);
  vtkInstantiator::RegisterInstantiator("vtkHyperOctreeLimiter", vtkInstantiatorvtkHyperOctreeLimiterNew);
  vtkInstantiator::RegisterInstantiator("vtkHyperOctreeSampleFunction", vtkInstantiatorvtkHyperOctreeSampleFunctionNew);
  vtkInstantiator::RegisterInstantiator("vtkHyperOctreeSurfaceFilter", vtkInstantiatorvtkHyperOctreeSurfaceFilterNew);
  vtkInstantiator::RegisterInstantiator("vtkHyperOctreeToUniformGridFilter", vtkInstantiatorvtkHyperOctreeToUniformGridFilterNew);
  vtkInstantiator::RegisterInstantiator("vtkHyperStreamline", vtkInstantiatorvtkHyperStreamlineNew);
  vtkInstantiator::RegisterInstantiator("vtkIconGlyphFilter", vtkInstantiatorvtkIconGlyphFilterNew);
  vtkInstantiator::RegisterInstantiator("vtkIdFilter", vtkInstantiatorvtkIdFilterNew);
  vtkInstantiator::RegisterInstantiator("vtkImageDataGeometryFilter", vtkInstantiatorvtkImageDataGeometryFilterNew);
  vtkInstantiator::RegisterInstantiator("vtkImageMarchingCubes", vtkInstantiatorvtkImageMarchingCubesNew);
  vtkInstantiator::RegisterInstantiator("vtkImplicitTextureCoords", vtkInstantiatorvtkImplicitTextureCoordsNew);
  vtkInstantiator::RegisterInstantiator("vtkInterpolateDataSetAttributes", vtkInstantiatorvtkInterpolateDataSetAttributesNew);
  vtkInstantiator::RegisterInstantiator("vtkKdTreeSelector", vtkInstantiatorvtkKdTreeSelectorNew);
  vtkInstantiator::RegisterInstantiator("vtkLevelIdScalars", vtkInstantiatorvtkLevelIdScalarsNew);
  vtkInstantiator::RegisterInstantiator("vtkLinearExtrusionFilter", vtkInstantiatorvtkLinearExtrusionFilterNew);
  vtkInstantiator::RegisterInstantiator("vtkLinearSubdivisionFilter", vtkInstantiatorvtkLinearSubdivisionFilterNew);
  vtkInstantiator::RegisterInstantiator("vtkLineSource", vtkInstantiatorvtkLineSourceNew);
  vtkInstantiator::RegisterInstantiator("vtkLinkEdgels", vtkInstantiatorvtkLinkEdgelsNew);
  vtkInstantiator::RegisterInstantiator("vtkLoopSubdivisionFilter", vtkInstantiatorvtkLoopSubdivisionFilterNew);
  vtkInstantiator::RegisterInstantiator("vtkMarchingContourFilter", vtkInstantiatorvtkMarchingContourFilterNew);
  vtkInstantiator::RegisterInstantiator("vtkMarchingCubes", vtkInstantiatorvtkMarchingCubesNew);
  vtkInstantiator::RegisterInstantiator("vtkMarchingSquares", vtkInstantiatorvtkMarchingSquaresNew);
  vtkInstantiator::RegisterInstantiator("vtkMaskFields", vtkInstantiatorvtkMaskFieldsNew);
  vtkInstantiator::RegisterInstantiator("vtkMaskPoints", vtkInstantiatorvtkMaskPointsNew);
  vtkInstantiator::RegisterInstantiator("vtkMaskPolyData", vtkInstantiatorvtkMaskPolyDataNew);
  vtkInstantiator::RegisterInstantiator("vtkMassProperties", vtkInstantiatorvtkMassPropertiesNew);
  vtkInstantiator::RegisterInstantiator("vtkMatrixMathFilter", vtkInstantiatorvtkMatrixMathFilterNew);
  vtkInstantiator::RegisterInstantiator("vtkMergeCells", vtkInstantiatorvtkMergeCellsNew);
  vtkInstantiator::RegisterInstantiator("vtkMergeDataObjectFilter", vtkInstantiatorvtkMergeDataObjectFilterNew);
  vtkInstantiator::RegisterInstantiator("vtkMergeFields", vtkInstantiatorvtkMergeFieldsNew);
  vtkInstantiator::RegisterInstantiator("vtkMergeFilter", vtkInstantiatorvtkMergeFilterNew);
  vtkInstantiator::RegisterInstantiator("vtkMeshQuality", vtkInstantiatorvtkMeshQualityNew);
  vtkInstantiator::RegisterInstantiator("vtkModelMetadata", vtkInstantiatorvtkModelMetadataNew);
  vtkInstantiator::RegisterInstantiator("vtkModifiedBSPTree", vtkInstantiatorvtkModifiedBSPTreeNew);
  vtkInstantiator::RegisterInstantiator("vtkMultiBlockDataGroupFilter", vtkInstantiatorvtkMultiBlockDataGroupFilterNew);
  vtkInstantiator::RegisterInstantiator("vtkMultiBlockMergeFilter", vtkInstantiatorvtkMultiBlockMergeFilterNew);
  vtkInstantiator::RegisterInstantiator("vtkMultiThreshold", vtkInstantiatorvtkMultiThresholdNew);
  vtkInstantiator::RegisterInstantiator("vtkOBBDicer", vtkInstantiatorvtkOBBDicerNew);
  vtkInstantiator::RegisterInstantiator("vtkOBBTree", vtkInstantiatorvtkOBBTreeNew);
  vtkInstantiator::RegisterInstantiator("vtkOutlineCornerFilter", vtkInstantiatorvtkOutlineCornerFilterNew);
  vtkInstantiator::RegisterInstantiator("vtkOutlineCornerSource", vtkInstantiatorvtkOutlineCornerSourceNew);
  vtkInstantiator::RegisterInstantiator("vtkOutlineFilter", vtkInstantiatorvtkOutlineFilterNew);
  vtkInstantiator::RegisterInstantiator("vtkOutlineSource", vtkInstantiatorvtkOutlineSourceNew);
  vtkInstantiator::RegisterInstantiator("vtkParametricFunctionSource", vtkInstantiatorvtkParametricFunctionSourceNew);
  vtkInstantiator::RegisterInstantiator("vtkPlaneSource", vtkInstantiatorvtkPlaneSourceNew);
  vtkInstantiator::RegisterInstantiator("vtkPlatonicSolidSource", vtkInstantiatorvtkPlatonicSolidSourceNew);
  vtkInstantiator::RegisterInstantiator("vtkPointDataToCellData", vtkInstantiatorvtkPointDataToCellDataNew);
  vtkInstantiator::RegisterInstantiator("vtkPointSource", vtkInstantiatorvtkPointSourceNew);
  vtkInstantiator::RegisterInstantiator("vtkPolyDataConnectivityFilter", vtkInstantiatorvtkPolyDataConnectivityFilterNew);
  vtkInstantiator::RegisterInstantiator("vtkPolyDataNormals", vtkInstantiatorvtkPolyDataNormalsNew);
  vtkInstantiator::RegisterInstantiator("vtkPolyDataPointSampler", vtkInstantiatorvtkPolyDataPointSamplerNew);
  vtkInstantiator::RegisterInstantiator("vtkPolyDataStreamer", vtkInstantiatorvtkPolyDataStreamerNew);
  vtkInstantiator::RegisterInstantiator("vtkPolyDataToReebGraphFilter", vtkInstantiatorvtkPolyDataToReebGraphFilterNew);
  vtkInstantiator::RegisterInstantiator("vtkProbeFilter", vtkInstantiatorvtkProbeFilterNew);
  vtkInstantiator::RegisterInstantiator("vtkProbePolyhedron", vtkInstantiatorvtkProbePolyhedronNew);
  vtkInstantiator::RegisterInstantiator("vtkProbeSelectedLocations", vtkInstantiatorvtkProbeSelectedLocationsNew);
  vtkInstantiator::RegisterInstantiator("vtkProgrammableAttributeDataFilter", vtkInstantiatorvtkProgrammableAttributeDataFilterNew);
  vtkInstantiator::RegisterInstantiator("vtkProgrammableDataObjectSource", vtkInstantiatorvtkProgrammableDataObjectSourceNew);
  vtkInstantiator::RegisterInstantiator("vtkProgrammableFilter", vtkInstantiatorvtkProgrammableFilterNew);
  vtkInstantiator::RegisterInstantiator("vtkProgrammableGlyphFilter", vtkInstantiatorvtkProgrammableGlyphFilterNew);
  vtkInstantiator::RegisterInstantiator("vtkProgrammableSource", vtkInstantiatorvtkProgrammableSourceNew);
  vtkInstantiator::RegisterInstantiator("vtkProjectedTexture", vtkInstantiatorvtkProjectedTextureNew);
  vtkInstantiator::RegisterInstantiator("vtkQuadraturePointInterpolator", vtkInstantiatorvtkQuadraturePointInterpolatorNew);
  vtkInstantiator::RegisterInstantiator("vtkQuadraturePointsGenerator", vtkInstantiatorvtkQuadraturePointsGeneratorNew);
  vtkInstantiator::RegisterInstantiator("vtkQuadratureSchemeDictionaryGenerator", vtkInstantiatorvtkQuadratureSchemeDictionaryGeneratorNew);
  vtkInstantiator::RegisterInstantiator("vtkQuadricClustering", vtkInstantiatorvtkQuadricClusteringNew);
  vtkInstantiator::RegisterInstantiator("vtkQuadricDecimation", vtkInstantiatorvtkQuadricDecimationNew);
  vtkInstantiator::RegisterInstantiator("vtkQuantizePolyDataPoints", vtkInstantiatorvtkQuantizePolyDataPointsNew);
  vtkInstantiator::RegisterInstantiator("vtkRandomAttributeGenerator", vtkInstantiatorvtkRandomAttributeGeneratorNew);
  vtkInstantiator::RegisterInstantiator("vtkRearrangeFields", vtkInstantiatorvtkRearrangeFieldsNew);
  vtkInstantiator::RegisterInstantiator("vtkRectangularButtonSource", vtkInstantiatorvtkRectangularButtonSourceNew);
  vtkInstantiator::RegisterInstantiator("vtkRectilinearGridClip", vtkInstantiatorvtkRectilinearGridClipNew);
  vtkInstantiator::RegisterInstantiator("vtkRectilinearGridGeometryFilter", vtkInstantiatorvtkRectilinearGridGeometryFilterNew);
  vtkInstantiator::RegisterInstantiator("vtkRectilinearGridToTetrahedra", vtkInstantiatorvtkRectilinearGridToTetrahedraNew);
  vtkInstantiator::RegisterInstantiator("vtkRectilinearSynchronizedTemplates", vtkInstantiatorvtkRectilinearSynchronizedTemplatesNew);
  vtkInstantiator::RegisterInstantiator("vtkRecursiveDividingCubes", vtkInstantiatorvtkRecursiveDividingCubesNew);
  vtkInstantiator::RegisterInstantiator("vtkReebGraphSimplificationFilter", vtkInstantiatorvtkReebGraphSimplificationFilterNew);
  vtkInstantiator::RegisterInstantiator("vtkReebGraphSurfaceSkeletonFilter", vtkInstantiatorvtkReebGraphSurfaceSkeletonFilterNew);
  vtkInstantiator::RegisterInstantiator("vtkReebGraphVolumeSkeletonFilter", vtkInstantiatorvtkReebGraphVolumeSkeletonFilterNew);
  vtkInstantiator::RegisterInstantiator("vtkReflectionFilter", vtkInstantiatorvtkReflectionFilterNew);
  vtkInstantiator::RegisterInstantiator("vtkRegularPolygonSource", vtkInstantiatorvtkRegularPolygonSourceNew);
  vtkInstantiator::RegisterInstantiator("vtkReverseSense", vtkInstantiatorvtkReverseSenseNew);
  vtkInstantiator::RegisterInstantiator("vtkRibbonFilter", vtkInstantiatorvtkRibbonFilterNew);
  vtkInstantiator::RegisterInstantiator("vtkRotationalExtrusionFilter", vtkInstantiatorvtkRotationalExtrusionFilterNew);
  vtkInstantiator::RegisterInstantiator("vtkRotationFilter", vtkInstantiatorvtkRotationFilterNew);
  vtkInstantiator::RegisterInstantiator("vtkRuledSurfaceFilter", vtkInstantiatorvtkRuledSurfaceFilterNew);
  vtkInstantiator::RegisterInstantiator("vtkSectorSource", vtkInstantiatorvtkSectorSourceNew);
  vtkInstantiator::RegisterInstantiator("vtkSelectEnclosedPoints", vtkInstantiatorvtkSelectEnclosedPointsNew);
  vtkInstantiator::RegisterInstantiator("vtkSelectionSource", vtkInstantiatorvtkSelectionSourceNew);
  vtkInstantiator::RegisterInstantiator("vtkSelectPolyData", vtkInstantiatorvtkSelectPolyDataNew);
  vtkInstantiator::RegisterInstantiator("vtkShrinkFilter", vtkInstantiatorvtkShrinkFilterNew);
  vtkInstantiator::RegisterInstantiator("vtkShrinkPolyData", vtkInstantiatorvtkShrinkPolyDataNew);
  vtkInstantiator::RegisterInstantiator("vtkSimpleElevationFilter", vtkInstantiatorvtkSimpleElevationFilterNew);
  vtkInstantiator::RegisterInstantiator("vtkSliceCubes", vtkInstantiatorvtkSliceCubesNew);
  vtkInstantiator::RegisterInstantiator("vtkSmoothPolyDataFilter", vtkInstantiatorvtkSmoothPolyDataFilterNew);
  vtkInstantiator::RegisterInstantiator("vtkSpatialRepresentationFilter", vtkInstantiatorvtkSpatialRepresentationFilterNew);
  vtkInstantiator::RegisterInstantiator("vtkSpherePuzzleArrows", vtkInstantiatorvtkSpherePuzzleArrowsNew);
  vtkInstantiator::RegisterInstantiator("vtkSpherePuzzle", vtkInstantiatorvtkSpherePuzzleNew);
  vtkInstantiator::RegisterInstantiator("vtkSphereSource", vtkInstantiatorvtkSphereSourceNew);
  vtkInstantiator::RegisterInstantiator("vtkSplineFilter", vtkInstantiatorvtkSplineFilterNew);
  vtkInstantiator::RegisterInstantiator("vtkSplitField", vtkInstantiatorvtkSplitFieldNew);
  vtkInstantiator::RegisterInstantiator("vtkStreamingTessellator", vtkInstantiatorvtkStreamingTessellatorNew);
  vtkInstantiator::RegisterInstantiator("vtkStreamLine", vtkInstantiatorvtkStreamLineNew);
  vtkInstantiator::RegisterInstantiator("vtkStreamPoints", vtkInstantiatorvtkStreamPointsNew);
  vtkInstantiator::RegisterInstantiator("vtkStreamTracer", vtkInstantiatorvtkStreamTracerNew);
  vtkInstantiator::RegisterInstantiator("vtkStripper", vtkInstantiatorvtkStripperNew);
  vtkInstantiator::RegisterInstantiator("vtkStructuredGridClip", vtkInstantiatorvtkStructuredGridClipNew);
  vtkInstantiator::RegisterInstantiator("vtkStructuredGridGeometryFilter", vtkInstantiatorvtkStructuredGridGeometryFilterNew);
  vtkInstantiator::RegisterInstantiator("vtkStructuredGridOutlineFilter", vtkInstantiatorvtkStructuredGridOutlineFilterNew);
  vtkInstantiator::RegisterInstantiator("vtkStructuredPointsGeometryFilter", vtkInstantiatorvtkStructuredPointsGeometryFilterNew);
  vtkInstantiator::RegisterInstantiator("vtkSubdivideTetra", vtkInstantiatorvtkSubdivideTetraNew);
  vtkInstantiator::RegisterInstantiator("vtkSubPixelPositionEdgels", vtkInstantiatorvtkSubPixelPositionEdgelsNew);
  vtkInstantiator::RegisterInstantiator("vtkSuperquadricSource", vtkInstantiatorvtkSuperquadricSourceNew);
  vtkInstantiator::RegisterInstantiator("vtkSynchronizedTemplates2D", vtkInstantiatorvtkSynchronizedTemplates2DNew);
  vtkInstantiator::RegisterInstantiator("vtkSynchronizedTemplates3D", vtkInstantiatorvtkSynchronizedTemplates3DNew);
  vtkInstantiator::RegisterInstantiator("vtkSynchronizedTemplatesCutter3D", vtkInstantiatorvtkSynchronizedTemplatesCutter3DNew);
  vtkInstantiator::RegisterInstantiator("vtkTableBasedClipDataSet", vtkInstantiatorvtkTableBasedClipDataSetNew);
  vtkInstantiator::RegisterInstantiator("vtkTableToPolyData", vtkInstantiatorvtkTableToPolyDataNew);
  vtkInstantiator::RegisterInstantiator("vtkTableToStructuredGrid", vtkInstantiatorvtkTableToStructuredGridNew);
  vtkInstantiator::RegisterInstantiator("vtkTemporalPathLineFilter", vtkInstantiatorvtkTemporalPathLineFilterNew);
  vtkInstantiator::RegisterInstantiator("vtkTemporalStatistics", vtkInstantiatorvtkTemporalStatisticsNew);
  vtkInstantiator::RegisterInstantiator("vtkTensorGlyph", vtkInstantiatorvtkTensorGlyphNew);
  vtkInstantiator::RegisterInstantiator("vtkTessellatorFilter", vtkInstantiatorvtkTessellatorFilterNew);
  vtkInstantiator::RegisterInstantiator("vtkTessellatedBoxSource", vtkInstantiatorvtkTessellatedBoxSourceNew);
  vtkInstantiator::RegisterInstantiator("vtkTextSource", vtkInstantiatorvtkTextSourceNew);
  vtkInstantiator::RegisterInstantiator("vtkTexturedSphereSource", vtkInstantiatorvtkTexturedSphereSourceNew);
  vtkInstantiator::RegisterInstantiator("vtkTextureMapToCylinder", vtkInstantiatorvtkTextureMapToCylinderNew);
  vtkInstantiator::RegisterInstantiator("vtkTextureMapToPlane", vtkInstantiatorvtkTextureMapToPlaneNew);
  vtkInstantiator::RegisterInstantiator("vtkTextureMapToSphere", vtkInstantiatorvtkTextureMapToSphereNew);
  vtkInstantiator::RegisterInstantiator("vtkThreshold", vtkInstantiatorvtkThresholdNew);
  vtkInstantiator::RegisterInstantiator("vtkThresholdPoints", vtkInstantiatorvtkThresholdPointsNew);
  vtkInstantiator::RegisterInstantiator("vtkThresholdTextureCoords", vtkInstantiatorvtkThresholdTextureCoordsNew);
  vtkInstantiator::RegisterInstantiator("vtkTimeSourceExample", vtkInstantiatorvtkTimeSourceExampleNew);
  vtkInstantiator::RegisterInstantiator("vtkTransformCoordinateSystems", vtkInstantiatorvtkTransformCoordinateSystemsNew);
  vtkInstantiator::RegisterInstantiator("vtkTransformFilter", vtkInstantiatorvtkTransformFilterNew);
  vtkInstantiator::RegisterInstantiator("vtkTransformPolyDataFilter", vtkInstantiatorvtkTransformPolyDataFilterNew);
  vtkInstantiator::RegisterInstantiator("vtkTransformTextureCoords", vtkInstantiatorvtkTransformTextureCoordsNew);
  vtkInstantiator::RegisterInstantiator("vtkTriangleFilter", vtkInstantiatorvtkTriangleFilterNew);
  vtkInstantiator::RegisterInstantiator("vtkTriangularTCoords", vtkInstantiatorvtkTriangularTCoordsNew);
  vtkInstantiator::RegisterInstantiator("vtkTubeFilter", vtkInstantiatorvtkTubeFilterNew);
  vtkInstantiator::RegisterInstantiator("vtkUncertaintyTubeFilter", vtkInstantiatorvtkUncertaintyTubeFilterNew);
  vtkInstantiator::RegisterInstantiator("vtkUnstructuredGridGeometryFilter", vtkInstantiatorvtkUnstructuredGridGeometryFilterNew);
  vtkInstantiator::RegisterInstantiator("vtkUnstructuredGridToReebGraphFilter", vtkInstantiatorvtkUnstructuredGridToReebGraphFilterNew);
  vtkInstantiator::RegisterInstantiator("vtkVectorDot", vtkInstantiatorvtkVectorDotNew);
  vtkInstantiator::RegisterInstantiator("vtkVectorNorm", vtkInstantiatorvtkVectorNormNew);
  vtkInstantiator::RegisterInstantiator("vtkVertexGlyphFilter", vtkInstantiatorvtkVertexGlyphFilterNew);
  vtkInstantiator::RegisterInstantiator("vtkVolumeContourSpectrumFilter", vtkInstantiatorvtkVolumeContourSpectrumFilterNew);
  vtkInstantiator::RegisterInstantiator("vtkVoxelContoursToSurfaceFilter", vtkInstantiatorvtkVoxelContoursToSurfaceFilterNew);
  vtkInstantiator::RegisterInstantiator("vtkWarpLens", vtkInstantiatorvtkWarpLensNew);
  vtkInstantiator::RegisterInstantiator("vtkWarpScalar", vtkInstantiatorvtkWarpScalarNew);
  vtkInstantiator::RegisterInstantiator("vtkWarpTo", vtkInstantiatorvtkWarpToNew);
  vtkInstantiator::RegisterInstantiator("vtkWarpVector", vtkInstantiatorvtkWarpVectorNew);
  vtkInstantiator::RegisterInstantiator("vtkWindowedSincPolyDataFilter", vtkInstantiatorvtkWindowedSincPolyDataFilterNew);
  vtkInstantiator::RegisterInstantiator("vtkYoungsMaterialInterface", vtkInstantiatorvtkYoungsMaterialInterfaceNew);

  
}
          
void vtkGraphicsInstantiator::ClassFinalize()
{ 

  vtkInstantiator::UnRegisterInstantiator("vtkAnnotationLink", vtkInstantiatorvtkAnnotationLinkNew);
  vtkInstantiator::UnRegisterInstantiator("vtkAppendCompositeDataLeaves", vtkInstantiatorvtkAppendCompositeDataLeavesNew);
  vtkInstantiator::UnRegisterInstantiator("vtkAppendFilter", vtkInstantiatorvtkAppendFilterNew);
  vtkInstantiator::UnRegisterInstantiator("vtkAppendPolyData", vtkInstantiatorvtkAppendPolyDataNew);
  vtkInstantiator::UnRegisterInstantiator("vtkAppendSelection", vtkInstantiatorvtkAppendSelectionNew);
  vtkInstantiator::UnRegisterInstantiator("vtkArcSource", vtkInstantiatorvtkArcSourceNew);
  vtkInstantiator::UnRegisterInstantiator("vtkAreaContourSpectrumFilter", vtkInstantiatorvtkAreaContourSpectrumFilterNew);
  vtkInstantiator::UnRegisterInstantiator("vtkArrayCalculator", vtkInstantiatorvtkArrayCalculatorNew);
  vtkInstantiator::UnRegisterInstantiator("vtkArrowSource", vtkInstantiatorvtkArrowSourceNew);
  vtkInstantiator::UnRegisterInstantiator("vtkAssignAttribute", vtkInstantiatorvtkAssignAttributeNew);
  vtkInstantiator::UnRegisterInstantiator("vtkAttributeDataToFieldDataFilter", vtkInstantiatorvtkAttributeDataToFieldDataFilterNew);
  vtkInstantiator::UnRegisterInstantiator("vtkAxes", vtkInstantiatorvtkAxesNew);
  vtkInstantiator::UnRegisterInstantiator("vtkBandedPolyDataContourFilter", vtkInstantiatorvtkBandedPolyDataContourFilterNew);
  vtkInstantiator::UnRegisterInstantiator("vtkBlankStructuredGrid", vtkInstantiatorvtkBlankStructuredGridNew);
  vtkInstantiator::UnRegisterInstantiator("vtkBlankStructuredGridWithImage", vtkInstantiatorvtkBlankStructuredGridWithImageNew);
  vtkInstantiator::UnRegisterInstantiator("vtkBlockIdScalars", vtkInstantiatorvtkBlockIdScalarsNew);
  vtkInstantiator::UnRegisterInstantiator("vtkBoxClipDataSet", vtkInstantiatorvtkBoxClipDataSetNew);
  vtkInstantiator::UnRegisterInstantiator("vtkBrownianPoints", vtkInstantiatorvtkBrownianPointsNew);
  vtkInstantiator::UnRegisterInstantiator("vtkButterflySubdivisionFilter", vtkInstantiatorvtkButterflySubdivisionFilterNew);
  vtkInstantiator::UnRegisterInstantiator("vtkCellCenters", vtkInstantiatorvtkCellCentersNew);
  vtkInstantiator::UnRegisterInstantiator("vtkCellDataToPointData", vtkInstantiatorvtkCellDataToPointDataNew);
  vtkInstantiator::UnRegisterInstantiator("vtkCellDerivatives", vtkInstantiatorvtkCellDerivativesNew);
  vtkInstantiator::UnRegisterInstantiator("vtkCellLocatorInterpolatedVelocityField", vtkInstantiatorvtkCellLocatorInterpolatedVelocityFieldNew);
  vtkInstantiator::UnRegisterInstantiator("vtkCellQuality", vtkInstantiatorvtkCellQualityNew);
  vtkInstantiator::UnRegisterInstantiator("vtkCleanPolyData", vtkInstantiatorvtkCleanPolyDataNew);
  vtkInstantiator::UnRegisterInstantiator("vtkClipClosedSurface", vtkInstantiatorvtkClipClosedSurfaceNew);
  vtkInstantiator::UnRegisterInstantiator("vtkClipConvexPolyData", vtkInstantiatorvtkClipConvexPolyDataNew);
  vtkInstantiator::UnRegisterInstantiator("vtkClipDataSet", vtkInstantiatorvtkClipDataSetNew);
  vtkInstantiator::UnRegisterInstantiator("vtkClipHyperOctree", vtkInstantiatorvtkClipHyperOctreeNew);
  vtkInstantiator::UnRegisterInstantiator("vtkClipPolyData", vtkInstantiatorvtkClipPolyDataNew);
  vtkInstantiator::UnRegisterInstantiator("vtkClipVolume", vtkInstantiatorvtkClipVolumeNew);
  vtkInstantiator::UnRegisterInstantiator("vtkCoincidentPoints", vtkInstantiatorvtkCoincidentPointsNew);
  vtkInstantiator::UnRegisterInstantiator("vtkCompositeDataGeometryFilter", vtkInstantiatorvtkCompositeDataGeometryFilterNew);
  vtkInstantiator::UnRegisterInstantiator("vtkCompositeDataProbeFilter", vtkInstantiatorvtkCompositeDataProbeFilterNew);
  vtkInstantiator::UnRegisterInstantiator("vtkConeSource", vtkInstantiatorvtkConeSourceNew);
  vtkInstantiator::UnRegisterInstantiator("vtkConnectivityFilter", vtkInstantiatorvtkConnectivityFilterNew);
  vtkInstantiator::UnRegisterInstantiator("vtkContourFilter", vtkInstantiatorvtkContourFilterNew);
  vtkInstantiator::UnRegisterInstantiator("vtkContourGrid", vtkInstantiatorvtkContourGridNew);
  vtkInstantiator::UnRegisterInstantiator("vtkConvertSelection", vtkInstantiatorvtkConvertSelectionNew);
  vtkInstantiator::UnRegisterInstantiator("vtkCubeSource", vtkInstantiatorvtkCubeSourceNew);
  vtkInstantiator::UnRegisterInstantiator("vtkCursor2D", vtkInstantiatorvtkCursor2DNew);
  vtkInstantiator::UnRegisterInstantiator("vtkCursor3D", vtkInstantiatorvtkCursor3DNew);
  vtkInstantiator::UnRegisterInstantiator("vtkCurvatures", vtkInstantiatorvtkCurvaturesNew);
  vtkInstantiator::UnRegisterInstantiator("vtkCutter", vtkInstantiatorvtkCutterNew);
  vtkInstantiator::UnRegisterInstantiator("vtkCylinderSource", vtkInstantiatorvtkCylinderSourceNew);
  vtkInstantiator::UnRegisterInstantiator("vtkDashedStreamLine", vtkInstantiatorvtkDashedStreamLineNew);
  vtkInstantiator::UnRegisterInstantiator("vtkDataObjectGenerator", vtkInstantiatorvtkDataObjectGeneratorNew);
  vtkInstantiator::UnRegisterInstantiator("vtkDataObjectToDataSetFilter", vtkInstantiatorvtkDataObjectToDataSetFilterNew);
  vtkInstantiator::UnRegisterInstantiator("vtkDataSetEdgeSubdivisionCriterion", vtkInstantiatorvtkDataSetEdgeSubdivisionCriterionNew);
  vtkInstantiator::UnRegisterInstantiator("vtkDataSetGradient", vtkInstantiatorvtkDataSetGradientNew);
  vtkInstantiator::UnRegisterInstantiator("vtkDataSetGradientPrecompute", vtkInstantiatorvtkDataSetGradientPrecomputeNew);
  vtkInstantiator::UnRegisterInstantiator("vtkDataSetSurfaceFilter", vtkInstantiatorvtkDataSetSurfaceFilterNew);
  vtkInstantiator::UnRegisterInstantiator("vtkDataSetToDataObjectFilter", vtkInstantiatorvtkDataSetToDataObjectFilterNew);
  vtkInstantiator::UnRegisterInstantiator("vtkDataSetTriangleFilter", vtkInstantiatorvtkDataSetTriangleFilterNew);
  vtkInstantiator::UnRegisterInstantiator("vtkDecimatePolylineFilter", vtkInstantiatorvtkDecimatePolylineFilterNew);
  vtkInstantiator::UnRegisterInstantiator("vtkDecimatePro", vtkInstantiatorvtkDecimateProNew);
  vtkInstantiator::UnRegisterInstantiator("vtkDelaunay2D", vtkInstantiatorvtkDelaunay2DNew);
  vtkInstantiator::UnRegisterInstantiator("vtkDelaunay3D", vtkInstantiatorvtkDelaunay3DNew);
  vtkInstantiator::UnRegisterInstantiator("vtkDensifyPolyData", vtkInstantiatorvtkDensifyPolyDataNew);
  vtkInstantiator::UnRegisterInstantiator("vtkDijkstraGraphGeodesicPath", vtkInstantiatorvtkDijkstraGraphGeodesicPathNew);
  vtkInstantiator::UnRegisterInstantiator("vtkDijkstraImageGeodesicPath", vtkInstantiatorvtkDijkstraImageGeodesicPathNew);
  vtkInstantiator::UnRegisterInstantiator("vtkDiscreteMarchingCubes", vtkInstantiatorvtkDiscreteMarchingCubesNew);
  vtkInstantiator::UnRegisterInstantiator("vtkDiskSource", vtkInstantiatorvtkDiskSourceNew);
  vtkInstantiator::UnRegisterInstantiator("vtkEdgePoints", vtkInstantiatorvtkEdgePointsNew);
  vtkInstantiator::UnRegisterInstantiator("vtkElevationFilter", vtkInstantiatorvtkElevationFilterNew);
  vtkInstantiator::UnRegisterInstantiator("vtkEllipticalButtonSource", vtkInstantiatorvtkEllipticalButtonSourceNew);
  vtkInstantiator::UnRegisterInstantiator("vtkExtractArraysOverTime", vtkInstantiatorvtkExtractArraysOverTimeNew);
  vtkInstantiator::UnRegisterInstantiator("vtkExtractBlock", vtkInstantiatorvtkExtractBlockNew);
  vtkInstantiator::UnRegisterInstantiator("vtkExtractCells", vtkInstantiatorvtkExtractCellsNew);
  vtkInstantiator::UnRegisterInstantiator("vtkExtractDataOverTime", vtkInstantiatorvtkExtractDataOverTimeNew);
  vtkInstantiator::UnRegisterInstantiator("vtkExtractDataSets", vtkInstantiatorvtkExtractDataSetsNew);
  vtkInstantiator::UnRegisterInstantiator("vtkExtractEdges", vtkInstantiatorvtkExtractEdgesNew);
  vtkInstantiator::UnRegisterInstantiator("vtkExtractGeometry", vtkInstantiatorvtkExtractGeometryNew);
  vtkInstantiator::UnRegisterInstantiator("vtkExtractGrid", vtkInstantiatorvtkExtractGridNew);
  vtkInstantiator::UnRegisterInstantiator("vtkExtractLevel", vtkInstantiatorvtkExtractLevelNew);
  vtkInstantiator::UnRegisterInstantiator("vtkExtractPolyDataGeometry", vtkInstantiatorvtkExtractPolyDataGeometryNew);
  vtkInstantiator::UnRegisterInstantiator("vtkExtractRectilinearGrid", vtkInstantiatorvtkExtractRectilinearGridNew);
  vtkInstantiator::UnRegisterInstantiator("vtkExtractSelectedBlock", vtkInstantiatorvtkExtractSelectedBlockNew);
  vtkInstantiator::UnRegisterInstantiator("vtkExtractSelectedFrustum", vtkInstantiatorvtkExtractSelectedFrustumNew);
  vtkInstantiator::UnRegisterInstantiator("vtkExtractSelectedIds", vtkInstantiatorvtkExtractSelectedIdsNew);
  vtkInstantiator::UnRegisterInstantiator("vtkExtractSelectedLocations", vtkInstantiatorvtkExtractSelectedLocationsNew);
  vtkInstantiator::UnRegisterInstantiator("vtkExtractSelectedPolyDataIds", vtkInstantiatorvtkExtractSelectedPolyDataIdsNew);
  vtkInstantiator::UnRegisterInstantiator("vtkExtractSelectedRows", vtkInstantiatorvtkExtractSelectedRowsNew);
  vtkInstantiator::UnRegisterInstantiator("vtkExtractSelectedThresholds", vtkInstantiatorvtkExtractSelectedThresholdsNew);
  vtkInstantiator::UnRegisterInstantiator("vtkExtractSelection", vtkInstantiatorvtkExtractSelectionNew);
  vtkInstantiator::UnRegisterInstantiator("vtkExtractTemporalFieldData", vtkInstantiatorvtkExtractTemporalFieldDataNew);
  vtkInstantiator::UnRegisterInstantiator("vtkExtractTensorComponents", vtkInstantiatorvtkExtractTensorComponentsNew);
  vtkInstantiator::UnRegisterInstantiator("vtkExtractUnstructuredGrid", vtkInstantiatorvtkExtractUnstructuredGridNew);
  vtkInstantiator::UnRegisterInstantiator("vtkExtractVectorComponents", vtkInstantiatorvtkExtractVectorComponentsNew);
  vtkInstantiator::UnRegisterInstantiator("vtkFeatureEdges", vtkInstantiatorvtkFeatureEdgesNew);
  vtkInstantiator::UnRegisterInstantiator("vtkFieldDataToAttributeDataFilter", vtkInstantiatorvtkFieldDataToAttributeDataFilterNew);
  vtkInstantiator::UnRegisterInstantiator("vtkFillHolesFilter", vtkInstantiatorvtkFillHolesFilterNew);
  vtkInstantiator::UnRegisterInstantiator("vtkFrustumSource", vtkInstantiatorvtkFrustumSourceNew);
  vtkInstantiator::UnRegisterInstantiator("vtkGeometryFilter", vtkInstantiatorvtkGeometryFilterNew);
  vtkInstantiator::UnRegisterInstantiator("vtkGlyph2D", vtkInstantiatorvtkGlyph2DNew);
  vtkInstantiator::UnRegisterInstantiator("vtkGlyph3D", vtkInstantiatorvtkGlyph3DNew);
  vtkInstantiator::UnRegisterInstantiator("vtkGlyphSource2D", vtkInstantiatorvtkGlyphSource2DNew);
  vtkInstantiator::UnRegisterInstantiator("vtkGradientFilter", vtkInstantiatorvtkGradientFilterNew);
  vtkInstantiator::UnRegisterInstantiator("vtkGraphLayoutFilter", vtkInstantiatorvtkGraphLayoutFilterNew);
  vtkInstantiator::UnRegisterInstantiator("vtkGraphToPoints", vtkInstantiatorvtkGraphToPointsNew);
  vtkInstantiator::UnRegisterInstantiator("vtkGraphToPolyData", vtkInstantiatorvtkGraphToPolyDataNew);
  vtkInstantiator::UnRegisterInstantiator("vtkGridSynchronizedTemplates3D", vtkInstantiatorvtkGridSynchronizedTemplates3DNew);
  vtkInstantiator::UnRegisterInstantiator("vtkHedgeHog", vtkInstantiatorvtkHedgeHogNew);
  vtkInstantiator::UnRegisterInstantiator("vtkHierarchicalDataExtractDataSets", vtkInstantiatorvtkHierarchicalDataExtractDataSetsNew);
  vtkInstantiator::UnRegisterInstantiator("vtkHierarchicalDataExtractLevel", vtkInstantiatorvtkHierarchicalDataExtractLevelNew);
  vtkInstantiator::UnRegisterInstantiator("vtkHierarchicalDataLevelFilter", vtkInstantiatorvtkHierarchicalDataLevelFilterNew);
  vtkInstantiator::UnRegisterInstantiator("vtkHierarchicalDataSetGeometryFilter", vtkInstantiatorvtkHierarchicalDataSetGeometryFilterNew);
  vtkInstantiator::UnRegisterInstantiator("vtkHull", vtkInstantiatorvtkHullNew);
  vtkInstantiator::UnRegisterInstantiator("vtkHyperOctreeClipCutPointsGrabber", vtkInstantiatorvtkHyperOctreeClipCutPointsGrabberNew);
  vtkInstantiator::UnRegisterInstantiator("vtkHyperOctreeContourFilter", vtkInstantiatorvtkHyperOctreeContourFilterNew);
  vtkInstantiator::UnRegisterInstantiator("vtkHyperOctreeCutter", vtkInstantiatorvtkHyperOctreeCutterNew);
  vtkInstantiator::UnRegisterInstantiator("vtkHyperOctreeDepth", vtkInstantiatorvtkHyperOctreeDepthNew);
  vtkInstantiator::UnRegisterInstantiator("vtkHyperOctreeDualGridContourFilter", vtkInstantiatorvtkHyperOctreeDualGridContourFilterNew);
  vtkInstantiator::UnRegisterInstantiator("vtkHyperOctreeFractalSource", vtkInstantiatorvtkHyperOctreeFractalSourceNew);
  vtkInstantiator::UnRegisterInstantiator("vtkHyperOctreeLimiter", vtkInstantiatorvtkHyperOctreeLimiterNew);
  vtkInstantiator::UnRegisterInstantiator("vtkHyperOctreeSampleFunction", vtkInstantiatorvtkHyperOctreeSampleFunctionNew);
  vtkInstantiator::UnRegisterInstantiator("vtkHyperOctreeSurfaceFilter", vtkInstantiatorvtkHyperOctreeSurfaceFilterNew);
  vtkInstantiator::UnRegisterInstantiator("vtkHyperOctreeToUniformGridFilter", vtkInstantiatorvtkHyperOctreeToUniformGridFilterNew);
  vtkInstantiator::UnRegisterInstantiator("vtkHyperStreamline", vtkInstantiatorvtkHyperStreamlineNew);
  vtkInstantiator::UnRegisterInstantiator("vtkIconGlyphFilter", vtkInstantiatorvtkIconGlyphFilterNew);
  vtkInstantiator::UnRegisterInstantiator("vtkIdFilter", vtkInstantiatorvtkIdFilterNew);
  vtkInstantiator::UnRegisterInstantiator("vtkImageDataGeometryFilter", vtkInstantiatorvtkImageDataGeometryFilterNew);
  vtkInstantiator::UnRegisterInstantiator("vtkImageMarchingCubes", vtkInstantiatorvtkImageMarchingCubesNew);
  vtkInstantiator::UnRegisterInstantiator("vtkImplicitTextureCoords", vtkInstantiatorvtkImplicitTextureCoordsNew);
  vtkInstantiator::UnRegisterInstantiator("vtkInterpolateDataSetAttributes", vtkInstantiatorvtkInterpolateDataSetAttributesNew);
  vtkInstantiator::UnRegisterInstantiator("vtkKdTreeSelector", vtkInstantiatorvtkKdTreeSelectorNew);
  vtkInstantiator::UnRegisterInstantiator("vtkLevelIdScalars", vtkInstantiatorvtkLevelIdScalarsNew);
  vtkInstantiator::UnRegisterInstantiator("vtkLinearExtrusionFilter", vtkInstantiatorvtkLinearExtrusionFilterNew);
  vtkInstantiator::UnRegisterInstantiator("vtkLinearSubdivisionFilter", vtkInstantiatorvtkLinearSubdivisionFilterNew);
  vtkInstantiator::UnRegisterInstantiator("vtkLineSource", vtkInstantiatorvtkLineSourceNew);
  vtkInstantiator::UnRegisterInstantiator("vtkLinkEdgels", vtkInstantiatorvtkLinkEdgelsNew);
  vtkInstantiator::UnRegisterInstantiator("vtkLoopSubdivisionFilter", vtkInstantiatorvtkLoopSubdivisionFilterNew);
  vtkInstantiator::UnRegisterInstantiator("vtkMarchingContourFilter", vtkInstantiatorvtkMarchingContourFilterNew);
  vtkInstantiator::UnRegisterInstantiator("vtkMarchingCubes", vtkInstantiatorvtkMarchingCubesNew);
  vtkInstantiator::UnRegisterInstantiator("vtkMarchingSquares", vtkInstantiatorvtkMarchingSquaresNew);
  vtkInstantiator::UnRegisterInstantiator("vtkMaskFields", vtkInstantiatorvtkMaskFieldsNew);
  vtkInstantiator::UnRegisterInstantiator("vtkMaskPoints", vtkInstantiatorvtkMaskPointsNew);
  vtkInstantiator::UnRegisterInstantiator("vtkMaskPolyData", vtkInstantiatorvtkMaskPolyDataNew);
  vtkInstantiator::UnRegisterInstantiator("vtkMassProperties", vtkInstantiatorvtkMassPropertiesNew);
  vtkInstantiator::UnRegisterInstantiator("vtkMatrixMathFilter", vtkInstantiatorvtkMatrixMathFilterNew);
  vtkInstantiator::UnRegisterInstantiator("vtkMergeCells", vtkInstantiatorvtkMergeCellsNew);
  vtkInstantiator::UnRegisterInstantiator("vtkMergeDataObjectFilter", vtkInstantiatorvtkMergeDataObjectFilterNew);
  vtkInstantiator::UnRegisterInstantiator("vtkMergeFields", vtkInstantiatorvtkMergeFieldsNew);
  vtkInstantiator::UnRegisterInstantiator("vtkMergeFilter", vtkInstantiatorvtkMergeFilterNew);
  vtkInstantiator::UnRegisterInstantiator("vtkMeshQuality", vtkInstantiatorvtkMeshQualityNew);
  vtkInstantiator::UnRegisterInstantiator("vtkModelMetadata", vtkInstantiatorvtkModelMetadataNew);
  vtkInstantiator::UnRegisterInstantiator("vtkModifiedBSPTree", vtkInstantiatorvtkModifiedBSPTreeNew);
  vtkInstantiator::UnRegisterInstantiator("vtkMultiBlockDataGroupFilter", vtkInstantiatorvtkMultiBlockDataGroupFilterNew);
  vtkInstantiator::UnRegisterInstantiator("vtkMultiBlockMergeFilter", vtkInstantiatorvtkMultiBlockMergeFilterNew);
  vtkInstantiator::UnRegisterInstantiator("vtkMultiThreshold", vtkInstantiatorvtkMultiThresholdNew);
  vtkInstantiator::UnRegisterInstantiator("vtkOBBDicer", vtkInstantiatorvtkOBBDicerNew);
  vtkInstantiator::UnRegisterInstantiator("vtkOBBTree", vtkInstantiatorvtkOBBTreeNew);
  vtkInstantiator::UnRegisterInstantiator("vtkOutlineCornerFilter", vtkInstantiatorvtkOutlineCornerFilterNew);
  vtkInstantiator::UnRegisterInstantiator("vtkOutlineCornerSource", vtkInstantiatorvtkOutlineCornerSourceNew);
  vtkInstantiator::UnRegisterInstantiator("vtkOutlineFilter", vtkInstantiatorvtkOutlineFilterNew);
  vtkInstantiator::UnRegisterInstantiator("vtkOutlineSource", vtkInstantiatorvtkOutlineSourceNew);
  vtkInstantiator::UnRegisterInstantiator("vtkParametricFunctionSource", vtkInstantiatorvtkParametricFunctionSourceNew);
  vtkInstantiator::UnRegisterInstantiator("vtkPlaneSource", vtkInstantiatorvtkPlaneSourceNew);
  vtkInstantiator::UnRegisterInstantiator("vtkPlatonicSolidSource", vtkInstantiatorvtkPlatonicSolidSourceNew);
  vtkInstantiator::UnRegisterInstantiator("vtkPointDataToCellData", vtkInstantiatorvtkPointDataToCellDataNew);
  vtkInstantiator::UnRegisterInstantiator("vtkPointSource", vtkInstantiatorvtkPointSourceNew);
  vtkInstantiator::UnRegisterInstantiator("vtkPolyDataConnectivityFilter", vtkInstantiatorvtkPolyDataConnectivityFilterNew);
  vtkInstantiator::UnRegisterInstantiator("vtkPolyDataNormals", vtkInstantiatorvtkPolyDataNormalsNew);
  vtkInstantiator::UnRegisterInstantiator("vtkPolyDataPointSampler", vtkInstantiatorvtkPolyDataPointSamplerNew);
  vtkInstantiator::UnRegisterInstantiator("vtkPolyDataStreamer", vtkInstantiatorvtkPolyDataStreamerNew);
  vtkInstantiator::UnRegisterInstantiator("vtkPolyDataToReebGraphFilter", vtkInstantiatorvtkPolyDataToReebGraphFilterNew);
  vtkInstantiator::UnRegisterInstantiator("vtkProbeFilter", vtkInstantiatorvtkProbeFilterNew);
  vtkInstantiator::UnRegisterInstantiator("vtkProbePolyhedron", vtkInstantiatorvtkProbePolyhedronNew);
  vtkInstantiator::UnRegisterInstantiator("vtkProbeSelectedLocations", vtkInstantiatorvtkProbeSelectedLocationsNew);
  vtkInstantiator::UnRegisterInstantiator("vtkProgrammableAttributeDataFilter", vtkInstantiatorvtkProgrammableAttributeDataFilterNew);
  vtkInstantiator::UnRegisterInstantiator("vtkProgrammableDataObjectSource", vtkInstantiatorvtkProgrammableDataObjectSourceNew);
  vtkInstantiator::UnRegisterInstantiator("vtkProgrammableFilter", vtkInstantiatorvtkProgrammableFilterNew);
  vtkInstantiator::UnRegisterInstantiator("vtkProgrammableGlyphFilter", vtkInstantiatorvtkProgrammableGlyphFilterNew);
  vtkInstantiator::UnRegisterInstantiator("vtkProgrammableSource", vtkInstantiatorvtkProgrammableSourceNew);
  vtkInstantiator::UnRegisterInstantiator("vtkProjectedTexture", vtkInstantiatorvtkProjectedTextureNew);
  vtkInstantiator::UnRegisterInstantiator("vtkQuadraturePointInterpolator", vtkInstantiatorvtkQuadraturePointInterpolatorNew);
  vtkInstantiator::UnRegisterInstantiator("vtkQuadraturePointsGenerator", vtkInstantiatorvtkQuadraturePointsGeneratorNew);
  vtkInstantiator::UnRegisterInstantiator("vtkQuadratureSchemeDictionaryGenerator", vtkInstantiatorvtkQuadratureSchemeDictionaryGeneratorNew);
  vtkInstantiator::UnRegisterInstantiator("vtkQuadricClustering", vtkInstantiatorvtkQuadricClusteringNew);
  vtkInstantiator::UnRegisterInstantiator("vtkQuadricDecimation", vtkInstantiatorvtkQuadricDecimationNew);
  vtkInstantiator::UnRegisterInstantiator("vtkQuantizePolyDataPoints", vtkInstantiatorvtkQuantizePolyDataPointsNew);
  vtkInstantiator::UnRegisterInstantiator("vtkRandomAttributeGenerator", vtkInstantiatorvtkRandomAttributeGeneratorNew);
  vtkInstantiator::UnRegisterInstantiator("vtkRearrangeFields", vtkInstantiatorvtkRearrangeFieldsNew);
  vtkInstantiator::UnRegisterInstantiator("vtkRectangularButtonSource", vtkInstantiatorvtkRectangularButtonSourceNew);
  vtkInstantiator::UnRegisterInstantiator("vtkRectilinearGridClip", vtkInstantiatorvtkRectilinearGridClipNew);
  vtkInstantiator::UnRegisterInstantiator("vtkRectilinearGridGeometryFilter", vtkInstantiatorvtkRectilinearGridGeometryFilterNew);
  vtkInstantiator::UnRegisterInstantiator("vtkRectilinearGridToTetrahedra", vtkInstantiatorvtkRectilinearGridToTetrahedraNew);
  vtkInstantiator::UnRegisterInstantiator("vtkRectilinearSynchronizedTemplates", vtkInstantiatorvtkRectilinearSynchronizedTemplatesNew);
  vtkInstantiator::UnRegisterInstantiator("vtkRecursiveDividingCubes", vtkInstantiatorvtkRecursiveDividingCubesNew);
  vtkInstantiator::UnRegisterInstantiator("vtkReebGraphSimplificationFilter", vtkInstantiatorvtkReebGraphSimplificationFilterNew);
  vtkInstantiator::UnRegisterInstantiator("vtkReebGraphSurfaceSkeletonFilter", vtkInstantiatorvtkReebGraphSurfaceSkeletonFilterNew);
  vtkInstantiator::UnRegisterInstantiator("vtkReebGraphVolumeSkeletonFilter", vtkInstantiatorvtkReebGraphVolumeSkeletonFilterNew);
  vtkInstantiator::UnRegisterInstantiator("vtkReflectionFilter", vtkInstantiatorvtkReflectionFilterNew);
  vtkInstantiator::UnRegisterInstantiator("vtkRegularPolygonSource", vtkInstantiatorvtkRegularPolygonSourceNew);
  vtkInstantiator::UnRegisterInstantiator("vtkReverseSense", vtkInstantiatorvtkReverseSenseNew);
  vtkInstantiator::UnRegisterInstantiator("vtkRibbonFilter", vtkInstantiatorvtkRibbonFilterNew);
  vtkInstantiator::UnRegisterInstantiator("vtkRotationalExtrusionFilter", vtkInstantiatorvtkRotationalExtrusionFilterNew);
  vtkInstantiator::UnRegisterInstantiator("vtkRotationFilter", vtkInstantiatorvtkRotationFilterNew);
  vtkInstantiator::UnRegisterInstantiator("vtkRuledSurfaceFilter", vtkInstantiatorvtkRuledSurfaceFilterNew);
  vtkInstantiator::UnRegisterInstantiator("vtkSectorSource", vtkInstantiatorvtkSectorSourceNew);
  vtkInstantiator::UnRegisterInstantiator("vtkSelectEnclosedPoints", vtkInstantiatorvtkSelectEnclosedPointsNew);
  vtkInstantiator::UnRegisterInstantiator("vtkSelectionSource", vtkInstantiatorvtkSelectionSourceNew);
  vtkInstantiator::UnRegisterInstantiator("vtkSelectPolyData", vtkInstantiatorvtkSelectPolyDataNew);
  vtkInstantiator::UnRegisterInstantiator("vtkShrinkFilter", vtkInstantiatorvtkShrinkFilterNew);
  vtkInstantiator::UnRegisterInstantiator("vtkShrinkPolyData", vtkInstantiatorvtkShrinkPolyDataNew);
  vtkInstantiator::UnRegisterInstantiator("vtkSimpleElevationFilter", vtkInstantiatorvtkSimpleElevationFilterNew);
  vtkInstantiator::UnRegisterInstantiator("vtkSliceCubes", vtkInstantiatorvtkSliceCubesNew);
  vtkInstantiator::UnRegisterInstantiator("vtkSmoothPolyDataFilter", vtkInstantiatorvtkSmoothPolyDataFilterNew);
  vtkInstantiator::UnRegisterInstantiator("vtkSpatialRepresentationFilter", vtkInstantiatorvtkSpatialRepresentationFilterNew);
  vtkInstantiator::UnRegisterInstantiator("vtkSpherePuzzleArrows", vtkInstantiatorvtkSpherePuzzleArrowsNew);
  vtkInstantiator::UnRegisterInstantiator("vtkSpherePuzzle", vtkInstantiatorvtkSpherePuzzleNew);
  vtkInstantiator::UnRegisterInstantiator("vtkSphereSource", vtkInstantiatorvtkSphereSourceNew);
  vtkInstantiator::UnRegisterInstantiator("vtkSplineFilter", vtkInstantiatorvtkSplineFilterNew);
  vtkInstantiator::UnRegisterInstantiator("vtkSplitField", vtkInstantiatorvtkSplitFieldNew);
  vtkInstantiator::UnRegisterInstantiator("vtkStreamingTessellator", vtkInstantiatorvtkStreamingTessellatorNew);
  vtkInstantiator::UnRegisterInstantiator("vtkStreamLine", vtkInstantiatorvtkStreamLineNew);
  vtkInstantiator::UnRegisterInstantiator("vtkStreamPoints", vtkInstantiatorvtkStreamPointsNew);
  vtkInstantiator::UnRegisterInstantiator("vtkStreamTracer", vtkInstantiatorvtkStreamTracerNew);
  vtkInstantiator::UnRegisterInstantiator("vtkStripper", vtkInstantiatorvtkStripperNew);
  vtkInstantiator::UnRegisterInstantiator("vtkStructuredGridClip", vtkInstantiatorvtkStructuredGridClipNew);
  vtkInstantiator::UnRegisterInstantiator("vtkStructuredGridGeometryFilter", vtkInstantiatorvtkStructuredGridGeometryFilterNew);
  vtkInstantiator::UnRegisterInstantiator("vtkStructuredGridOutlineFilter", vtkInstantiatorvtkStructuredGridOutlineFilterNew);
  vtkInstantiator::UnRegisterInstantiator("vtkStructuredPointsGeometryFilter", vtkInstantiatorvtkStructuredPointsGeometryFilterNew);
  vtkInstantiator::UnRegisterInstantiator("vtkSubdivideTetra", vtkInstantiatorvtkSubdivideTetraNew);
  vtkInstantiator::UnRegisterInstantiator("vtkSubPixelPositionEdgels", vtkInstantiatorvtkSubPixelPositionEdgelsNew);
  vtkInstantiator::UnRegisterInstantiator("vtkSuperquadricSource", vtkInstantiatorvtkSuperquadricSourceNew);
  vtkInstantiator::UnRegisterInstantiator("vtkSynchronizedTemplates2D", vtkInstantiatorvtkSynchronizedTemplates2DNew);
  vtkInstantiator::UnRegisterInstantiator("vtkSynchronizedTemplates3D", vtkInstantiatorvtkSynchronizedTemplates3DNew);
  vtkInstantiator::UnRegisterInstantiator("vtkSynchronizedTemplatesCutter3D", vtkInstantiatorvtkSynchronizedTemplatesCutter3DNew);
  vtkInstantiator::UnRegisterInstantiator("vtkTableBasedClipDataSet", vtkInstantiatorvtkTableBasedClipDataSetNew);
  vtkInstantiator::UnRegisterInstantiator("vtkTableToPolyData", vtkInstantiatorvtkTableToPolyDataNew);
  vtkInstantiator::UnRegisterInstantiator("vtkTableToStructuredGrid", vtkInstantiatorvtkTableToStructuredGridNew);
  vtkInstantiator::UnRegisterInstantiator("vtkTemporalPathLineFilter", vtkInstantiatorvtkTemporalPathLineFilterNew);
  vtkInstantiator::UnRegisterInstantiator("vtkTemporalStatistics", vtkInstantiatorvtkTemporalStatisticsNew);
  vtkInstantiator::UnRegisterInstantiator("vtkTensorGlyph", vtkInstantiatorvtkTensorGlyphNew);
  vtkInstantiator::UnRegisterInstantiator("vtkTessellatorFilter", vtkInstantiatorvtkTessellatorFilterNew);
  vtkInstantiator::UnRegisterInstantiator("vtkTessellatedBoxSource", vtkInstantiatorvtkTessellatedBoxSourceNew);
  vtkInstantiator::UnRegisterInstantiator("vtkTextSource", vtkInstantiatorvtkTextSourceNew);
  vtkInstantiator::UnRegisterInstantiator("vtkTexturedSphereSource", vtkInstantiatorvtkTexturedSphereSourceNew);
  vtkInstantiator::UnRegisterInstantiator("vtkTextureMapToCylinder", vtkInstantiatorvtkTextureMapToCylinderNew);
  vtkInstantiator::UnRegisterInstantiator("vtkTextureMapToPlane", vtkInstantiatorvtkTextureMapToPlaneNew);
  vtkInstantiator::UnRegisterInstantiator("vtkTextureMapToSphere", vtkInstantiatorvtkTextureMapToSphereNew);
  vtkInstantiator::UnRegisterInstantiator("vtkThreshold", vtkInstantiatorvtkThresholdNew);
  vtkInstantiator::UnRegisterInstantiator("vtkThresholdPoints", vtkInstantiatorvtkThresholdPointsNew);
  vtkInstantiator::UnRegisterInstantiator("vtkThresholdTextureCoords", vtkInstantiatorvtkThresholdTextureCoordsNew);
  vtkInstantiator::UnRegisterInstantiator("vtkTimeSourceExample", vtkInstantiatorvtkTimeSourceExampleNew);
  vtkInstantiator::UnRegisterInstantiator("vtkTransformCoordinateSystems", vtkInstantiatorvtkTransformCoordinateSystemsNew);
  vtkInstantiator::UnRegisterInstantiator("vtkTransformFilter", vtkInstantiatorvtkTransformFilterNew);
  vtkInstantiator::UnRegisterInstantiator("vtkTransformPolyDataFilter", vtkInstantiatorvtkTransformPolyDataFilterNew);
  vtkInstantiator::UnRegisterInstantiator("vtkTransformTextureCoords", vtkInstantiatorvtkTransformTextureCoordsNew);
  vtkInstantiator::UnRegisterInstantiator("vtkTriangleFilter", vtkInstantiatorvtkTriangleFilterNew);
  vtkInstantiator::UnRegisterInstantiator("vtkTriangularTCoords", vtkInstantiatorvtkTriangularTCoordsNew);
  vtkInstantiator::UnRegisterInstantiator("vtkTubeFilter", vtkInstantiatorvtkTubeFilterNew);
  vtkInstantiator::UnRegisterInstantiator("vtkUncertaintyTubeFilter", vtkInstantiatorvtkUncertaintyTubeFilterNew);
  vtkInstantiator::UnRegisterInstantiator("vtkUnstructuredGridGeometryFilter", vtkInstantiatorvtkUnstructuredGridGeometryFilterNew);
  vtkInstantiator::UnRegisterInstantiator("vtkUnstructuredGridToReebGraphFilter", vtkInstantiatorvtkUnstructuredGridToReebGraphFilterNew);
  vtkInstantiator::UnRegisterInstantiator("vtkVectorDot", vtkInstantiatorvtkVectorDotNew);
  vtkInstantiator::UnRegisterInstantiator("vtkVectorNorm", vtkInstantiatorvtkVectorNormNew);
  vtkInstantiator::UnRegisterInstantiator("vtkVertexGlyphFilter", vtkInstantiatorvtkVertexGlyphFilterNew);
  vtkInstantiator::UnRegisterInstantiator("vtkVolumeContourSpectrumFilter", vtkInstantiatorvtkVolumeContourSpectrumFilterNew);
  vtkInstantiator::UnRegisterInstantiator("vtkVoxelContoursToSurfaceFilter", vtkInstantiatorvtkVoxelContoursToSurfaceFilterNew);
  vtkInstantiator::UnRegisterInstantiator("vtkWarpLens", vtkInstantiatorvtkWarpLensNew);
  vtkInstantiator::UnRegisterInstantiator("vtkWarpScalar", vtkInstantiatorvtkWarpScalarNew);
  vtkInstantiator::UnRegisterInstantiator("vtkWarpTo", vtkInstantiatorvtkWarpToNew);
  vtkInstantiator::UnRegisterInstantiator("vtkWarpVector", vtkInstantiatorvtkWarpVectorNew);
  vtkInstantiator::UnRegisterInstantiator("vtkWindowedSincPolyDataFilter", vtkInstantiatorvtkWindowedSincPolyDataFilterNew);
  vtkInstantiator::UnRegisterInstantiator("vtkYoungsMaterialInterface", vtkInstantiatorvtkYoungsMaterialInterfaceNew);

  
}

vtkGraphicsInstantiator::vtkGraphicsInstantiator()
{
  if(++vtkGraphicsInstantiator::Count == 1)
    { 
    vtkGraphicsInstantiator::ClassInitialize(); 
    }
}

vtkGraphicsInstantiator::~vtkGraphicsInstantiator()
{
  if(--vtkGraphicsInstantiator::Count == 0)
    { 
    vtkGraphicsInstantiator::ClassFinalize(); 
    }
}

// Number of translation units that include this class's header.
// Purposely not initialized.  Default is static initialization to 0.
unsigned int vtkGraphicsInstantiator::Count;
