#include "vtkIOInstantiator.h"
  
extern vtkObject* vtkInstantiatorvtkASCIITextCodecNew();
extern vtkObject* vtkInstantiatorvtkAVSucdReaderNew();
extern vtkObject* vtkInstantiatorvtkBMPReaderNew();
extern vtkObject* vtkInstantiatorvtkBMPWriterNew();
extern vtkObject* vtkInstantiatorvtkBYUReaderNew();
extern vtkObject* vtkInstantiatorvtkBYUWriterNew();
extern vtkObject* vtkInstantiatorvtkBase64InputStreamNew();
extern vtkObject* vtkInstantiatorvtkBase64OutputStreamNew();
extern vtkObject* vtkInstantiatorvtkBase64UtilitiesNew();
extern vtkObject* vtkInstantiatorvtkCGMWriterNew();
extern vtkObject* vtkInstantiatorvtkChacoReaderNew();
extern vtkObject* vtkInstantiatorvtkCompositeDataReaderNew();
extern vtkObject* vtkInstantiatorvtkCompositeDataWriterNew();
extern vtkObject* vtkInstantiatorvtkDEMReaderNew();
extern vtkObject* vtkInstantiatorvtkDICOMImageReaderNew();
extern vtkObject* vtkInstantiatorvtkDataObjectReaderNew();
extern vtkObject* vtkInstantiatorvtkDataObjectWriterNew();
extern vtkObject* vtkInstantiatorvtkDataReaderNew();
extern vtkObject* vtkInstantiatorvtkDataSetReaderNew();
extern vtkObject* vtkInstantiatorvtkDataSetWriterNew();
extern vtkObject* vtkInstantiatorvtkDataWriterNew();
extern vtkObject* vtkInstantiatorvtkDelimitedTextWriterNew();
extern vtkObject* vtkInstantiatorvtkEnSight6BinaryReaderNew();
extern vtkObject* vtkInstantiatorvtkEnSight6ReaderNew();
extern vtkObject* vtkInstantiatorvtkEnSightGoldBinaryReaderNew();
extern vtkObject* vtkInstantiatorvtkEnSightGoldReaderNew();
extern vtkObject* vtkInstantiatorvtkEnSightMasterServerReaderNew();
extern vtkObject* vtkInstantiatorvtkFLUENTReaderNew();
extern vtkObject* vtkInstantiatorvtkFacetWriterNew();
extern vtkObject* vtkInstantiatorvtkGESignaReaderNew();
extern vtkObject* vtkInstantiatorvtkGAMBITReaderNew();
extern vtkObject* vtkInstantiatorvtkGaussianCubeReaderNew();
extern vtkObject* vtkInstantiatorvtkGenericDataObjectReaderNew();
extern vtkObject* vtkInstantiatorvtkGenericDataObjectWriterNew();
extern vtkObject* vtkInstantiatorvtkGenericEnSightReaderNew();
extern vtkObject* vtkInstantiatorvtkGlobFileNamesNew();
extern vtkObject* vtkInstantiatorvtkGraphReaderNew();
extern vtkObject* vtkInstantiatorvtkGraphWriterNew();
extern vtkObject* vtkInstantiatorvtkIVWriterNew();
extern vtkObject* vtkInstantiatorvtkImageReaderNew();
extern vtkObject* vtkInstantiatorvtkImageReader2New();
extern vtkObject* vtkInstantiatorvtkImageReader2CollectionNew();
extern vtkObject* vtkInstantiatorvtkImageReader2FactoryNew();
extern vtkObject* vtkInstantiatorvtkImageWriterNew();
extern vtkObject* vtkInstantiatorvtkInputStreamNew();
extern vtkObject* vtkInstantiatorvtkJavaScriptDataWriterNew();
extern vtkObject* vtkInstantiatorvtkJPEGReaderNew();
extern vtkObject* vtkInstantiatorvtkJPEGWriterNew();
extern vtkObject* vtkInstantiatorvtkMFIXReaderNew();
extern vtkObject* vtkInstantiatorvtkMaterialLibraryNew();
extern vtkObject* vtkInstantiatorvtkMCubesReaderNew();
extern vtkObject* vtkInstantiatorvtkMCubesWriterNew();
extern vtkObject* vtkInstantiatorvtkMedicalImagePropertiesNew();
extern vtkObject* vtkInstantiatorvtkMedicalImageReader2New();
extern vtkObject* vtkInstantiatorvtkMetaImageReaderNew();
extern vtkObject* vtkInstantiatorvtkMetaImageWriterNew();
extern vtkObject* vtkInstantiatorvtkMINCImageAttributesNew();
extern vtkObject* vtkInstantiatorvtkMINCImageReaderNew();
extern vtkObject* vtkInstantiatorvtkMINCImageWriterNew();
extern vtkObject* vtkInstantiatorvtkMPASReaderNew();
extern vtkObject* vtkInstantiatorvtkMultiBlockPLOT3DReaderNew();
extern vtkObject* vtkInstantiatorvtkNetCDFCFReaderNew();
extern vtkObject* vtkInstantiatorvtkNetCDFPOPReaderNew();
extern vtkObject* vtkInstantiatorvtkNetCDFReaderNew();
extern vtkObject* vtkInstantiatorvtkOBJReaderNew();
extern vtkObject* vtkInstantiatorvtkOpenFOAMReaderNew();
extern vtkObject* vtkInstantiatorvtkOutputStreamNew();
extern vtkObject* vtkInstantiatorvtkPDBReaderNew();
extern vtkObject* vtkInstantiatorvtkPLOT3DReaderNew();
extern vtkObject* vtkInstantiatorvtkPLYReaderNew();
extern vtkObject* vtkInstantiatorvtkPLYWriterNew();
extern vtkObject* vtkInstantiatorvtkPNGReaderNew();
extern vtkObject* vtkInstantiatorvtkPNGWriterNew();
extern vtkObject* vtkInstantiatorvtkPNMReaderNew();
extern vtkObject* vtkInstantiatorvtkPNMWriterNew();
extern vtkObject* vtkInstantiatorvtkParticleReaderNew();
extern vtkObject* vtkInstantiatorvtkPolyDataReaderNew();
extern vtkObject* vtkInstantiatorvtkPolyDataWriterNew();
extern vtkObject* vtkInstantiatorvtkPostScriptWriterNew();
extern vtkObject* vtkInstantiatorvtkProStarReaderNew();
extern vtkObject* vtkInstantiatorvtkRectilinearGridReaderNew();
extern vtkObject* vtkInstantiatorvtkRectilinearGridWriterNew();
extern vtkObject* vtkInstantiatorvtkRTXMLPolyDataReaderNew();
extern vtkObject* vtkInstantiatorvtkSESAMEReaderNew();
extern vtkObject* vtkInstantiatorvtkShaderCodeLibraryNew();
extern vtkObject* vtkInstantiatorvtkSLACParticleReaderNew();
extern vtkObject* vtkInstantiatorvtkSLACReaderNew();
extern vtkObject* vtkInstantiatorvtkSQLDatabaseSchemaNew();
extern vtkObject* vtkInstantiatorvtkSQLiteDatabaseNew();
extern vtkObject* vtkInstantiatorvtkSQLiteToTableReaderNew();
extern vtkObject* vtkInstantiatorvtkSQLiteQueryNew();
extern vtkObject* vtkInstantiatorvtkSLCReaderNew();
extern vtkObject* vtkInstantiatorvtkSTLReaderNew();
extern vtkObject* vtkInstantiatorvtkSTLWriterNew();
extern vtkObject* vtkInstantiatorvtkSimplePointsReaderNew();
extern vtkObject* vtkInstantiatorvtkSortFileNamesNew();
extern vtkObject* vtkInstantiatorvtkStructuredGridReaderNew();
extern vtkObject* vtkInstantiatorvtkStructuredGridWriterNew();
extern vtkObject* vtkInstantiatorvtkStructuredPointsReaderNew();
extern vtkObject* vtkInstantiatorvtkStructuredPointsWriterNew();
extern vtkObject* vtkInstantiatorvtkTableReaderNew();
extern vtkObject* vtkInstantiatorvtkTableWriterNew();
extern vtkObject* vtkInstantiatorvtkTableToSQLiteWriterNew();
extern vtkObject* vtkInstantiatorvtkTecplotReaderNew();
extern vtkObject* vtkInstantiatorvtkTIFFReaderNew();
extern vtkObject* vtkInstantiatorvtkTIFFWriterNew();
extern vtkObject* vtkInstantiatorvtkTreeReaderNew();
extern vtkObject* vtkInstantiatorvtkTreeWriterNew();
extern vtkObject* vtkInstantiatorvtkUGFacetReaderNew();
extern vtkObject* vtkInstantiatorvtkUnstructuredGridReaderNew();
extern vtkObject* vtkInstantiatorvtkUnstructuredGridWriterNew();
extern vtkObject* vtkInstantiatorvtkUTF8TextCodecNew();
extern vtkObject* vtkInstantiatorvtkUTF16TextCodecNew();
extern vtkObject* vtkInstantiatorvtkVolume16ReaderNew();
extern vtkObject* vtkInstantiatorvtkXMLDataParserNew();
extern vtkObject* vtkInstantiatorvtkXMLDataSetWriterNew();
extern vtkObject* vtkInstantiatorvtkXMLFileReadTesterNew();
extern vtkObject* vtkInstantiatorvtkXMLGenericDataObjectReaderNew();
extern vtkObject* vtkInstantiatorvtkXMLHierarchicalBoxDataReaderNew();
extern vtkObject* vtkInstantiatorvtkXMLHierarchicalDataReaderNew();
extern vtkObject* vtkInstantiatorvtkXMLImageDataReaderNew();
extern vtkObject* vtkInstantiatorvtkXMLImageDataWriterNew();
extern vtkObject* vtkInstantiatorvtkXMLHyperOctreeReaderNew();
extern vtkObject* vtkInstantiatorvtkXMLHyperOctreeWriterNew();
extern vtkObject* vtkInstantiatorvtkXMLMaterialNew();
extern vtkObject* vtkInstantiatorvtkXMLMaterialParserNew();
extern vtkObject* vtkInstantiatorvtkXMLMaterialReaderNew();
extern vtkObject* vtkInstantiatorvtkXMLMultiBlockDataReaderNew();
extern vtkObject* vtkInstantiatorvtkXMLMultiGroupDataReaderNew();
extern vtkObject* vtkInstantiatorvtkXMLMultiBlockDataWriterNew();
extern vtkObject* vtkInstantiatorvtkXMLHierarchicalBoxDataWriterNew();
extern vtkObject* vtkInstantiatorvtkXMLPDataSetWriterNew();
extern vtkObject* vtkInstantiatorvtkXMLPImageDataReaderNew();
extern vtkObject* vtkInstantiatorvtkXMLPImageDataWriterNew();
extern vtkObject* vtkInstantiatorvtkXMLPPolyDataReaderNew();
extern vtkObject* vtkInstantiatorvtkXMLPPolyDataWriterNew();
extern vtkObject* vtkInstantiatorvtkXMLPRectilinearGridReaderNew();
extern vtkObject* vtkInstantiatorvtkXMLPRectilinearGridWriterNew();
extern vtkObject* vtkInstantiatorvtkXMLPStructuredGridReaderNew();
extern vtkObject* vtkInstantiatorvtkXMLPStructuredGridWriterNew();
extern vtkObject* vtkInstantiatorvtkXMLPUnstructuredGridReaderNew();
extern vtkObject* vtkInstantiatorvtkXMLPUnstructuredGridWriterNew();
extern vtkObject* vtkInstantiatorvtkXMLParserNew();
extern vtkObject* vtkInstantiatorvtkXMLPolyDataReaderNew();
extern vtkObject* vtkInstantiatorvtkXMLPolyDataWriterNew();
extern vtkObject* vtkInstantiatorvtkXMLRectilinearGridReaderNew();
extern vtkObject* vtkInstantiatorvtkXMLRectilinearGridWriterNew();
extern vtkObject* vtkInstantiatorvtkXMLShaderNew();
extern vtkObject* vtkInstantiatorvtkXMLStructuredGridReaderNew();
extern vtkObject* vtkInstantiatorvtkXMLStructuredGridWriterNew();
extern vtkObject* vtkInstantiatorvtkXMLUnstructuredGridReaderNew();
extern vtkObject* vtkInstantiatorvtkXMLUnstructuredGridWriterNew();
extern vtkObject* vtkInstantiatorvtkXMLUtilitiesNew();
extern vtkObject* vtkInstantiatorvtkXYZMolReaderNew();
extern vtkObject* vtkInstantiatorvtkZLibDataCompressorNew();
extern vtkObject* vtkInstantiatorvtkRowQueryToTableNew();
extern vtkObject* vtkInstantiatorvtkArrayReaderNew();
extern vtkObject* vtkInstantiatorvtkArrayWriterNew();


  
void vtkIOInstantiator::ClassInitialize()
{
  
  vtkInstantiator::RegisterInstantiator("vtkASCIITextCodec", vtkInstantiatorvtkASCIITextCodecNew);
  vtkInstantiator::RegisterInstantiator("vtkAVSucdReader", vtkInstantiatorvtkAVSucdReaderNew);
  vtkInstantiator::RegisterInstantiator("vtkBMPReader", vtkInstantiatorvtkBMPReaderNew);
  vtkInstantiator::RegisterInstantiator("vtkBMPWriter", vtkInstantiatorvtkBMPWriterNew);
  vtkInstantiator::RegisterInstantiator("vtkBYUReader", vtkInstantiatorvtkBYUReaderNew);
  vtkInstantiator::RegisterInstantiator("vtkBYUWriter", vtkInstantiatorvtkBYUWriterNew);
  vtkInstantiator::RegisterInstantiator("vtkBase64InputStream", vtkInstantiatorvtkBase64InputStreamNew);
  vtkInstantiator::RegisterInstantiator("vtkBase64OutputStream", vtkInstantiatorvtkBase64OutputStreamNew);
  vtkInstantiator::RegisterInstantiator("vtkBase64Utilities", vtkInstantiatorvtkBase64UtilitiesNew);
  vtkInstantiator::RegisterInstantiator("vtkCGMWriter", vtkInstantiatorvtkCGMWriterNew);
  vtkInstantiator::RegisterInstantiator("vtkChacoReader", vtkInstantiatorvtkChacoReaderNew);
  vtkInstantiator::RegisterInstantiator("vtkCompositeDataReader", vtkInstantiatorvtkCompositeDataReaderNew);
  vtkInstantiator::RegisterInstantiator("vtkCompositeDataWriter", vtkInstantiatorvtkCompositeDataWriterNew);
  vtkInstantiator::RegisterInstantiator("vtkDEMReader", vtkInstantiatorvtkDEMReaderNew);
  vtkInstantiator::RegisterInstantiator("vtkDICOMImageReader", vtkInstantiatorvtkDICOMImageReaderNew);
  vtkInstantiator::RegisterInstantiator("vtkDataObjectReader", vtkInstantiatorvtkDataObjectReaderNew);
  vtkInstantiator::RegisterInstantiator("vtkDataObjectWriter", vtkInstantiatorvtkDataObjectWriterNew);
  vtkInstantiator::RegisterInstantiator("vtkDataReader", vtkInstantiatorvtkDataReaderNew);
  vtkInstantiator::RegisterInstantiator("vtkDataSetReader", vtkInstantiatorvtkDataSetReaderNew);
  vtkInstantiator::RegisterInstantiator("vtkDataSetWriter", vtkInstantiatorvtkDataSetWriterNew);
  vtkInstantiator::RegisterInstantiator("vtkDataWriter", vtkInstantiatorvtkDataWriterNew);
  vtkInstantiator::RegisterInstantiator("vtkDelimitedTextWriter", vtkInstantiatorvtkDelimitedTextWriterNew);
  vtkInstantiator::RegisterInstantiator("vtkEnSight6BinaryReader", vtkInstantiatorvtkEnSight6BinaryReaderNew);
  vtkInstantiator::RegisterInstantiator("vtkEnSight6Reader", vtkInstantiatorvtkEnSight6ReaderNew);
  vtkInstantiator::RegisterInstantiator("vtkEnSightGoldBinaryReader", vtkInstantiatorvtkEnSightGoldBinaryReaderNew);
  vtkInstantiator::RegisterInstantiator("vtkEnSightGoldReader", vtkInstantiatorvtkEnSightGoldReaderNew);
  vtkInstantiator::RegisterInstantiator("vtkEnSightMasterServerReader", vtkInstantiatorvtkEnSightMasterServerReaderNew);
  vtkInstantiator::RegisterInstantiator("vtkFLUENTReader", vtkInstantiatorvtkFLUENTReaderNew);
  vtkInstantiator::RegisterInstantiator("vtkFacetWriter", vtkInstantiatorvtkFacetWriterNew);
  vtkInstantiator::RegisterInstantiator("vtkGESignaReader", vtkInstantiatorvtkGESignaReaderNew);
  vtkInstantiator::RegisterInstantiator("vtkGAMBITReader", vtkInstantiatorvtkGAMBITReaderNew);
  vtkInstantiator::RegisterInstantiator("vtkGaussianCubeReader", vtkInstantiatorvtkGaussianCubeReaderNew);
  vtkInstantiator::RegisterInstantiator("vtkGenericDataObjectReader", vtkInstantiatorvtkGenericDataObjectReaderNew);
  vtkInstantiator::RegisterInstantiator("vtkGenericDataObjectWriter", vtkInstantiatorvtkGenericDataObjectWriterNew);
  vtkInstantiator::RegisterInstantiator("vtkGenericEnSightReader", vtkInstantiatorvtkGenericEnSightReaderNew);
  vtkInstantiator::RegisterInstantiator("vtkGlobFileNames", vtkInstantiatorvtkGlobFileNamesNew);
  vtkInstantiator::RegisterInstantiator("vtkGraphReader", vtkInstantiatorvtkGraphReaderNew);
  vtkInstantiator::RegisterInstantiator("vtkGraphWriter", vtkInstantiatorvtkGraphWriterNew);
  vtkInstantiator::RegisterInstantiator("vtkIVWriter", vtkInstantiatorvtkIVWriterNew);
  vtkInstantiator::RegisterInstantiator("vtkImageReader", vtkInstantiatorvtkImageReaderNew);
  vtkInstantiator::RegisterInstantiator("vtkImageReader2", vtkInstantiatorvtkImageReader2New);
  vtkInstantiator::RegisterInstantiator("vtkImageReader2Collection", vtkInstantiatorvtkImageReader2CollectionNew);
  vtkInstantiator::RegisterInstantiator("vtkImageReader2Factory", vtkInstantiatorvtkImageReader2FactoryNew);
  vtkInstantiator::RegisterInstantiator("vtkImageWriter", vtkInstantiatorvtkImageWriterNew);
  vtkInstantiator::RegisterInstantiator("vtkInputStream", vtkInstantiatorvtkInputStreamNew);
  vtkInstantiator::RegisterInstantiator("vtkJavaScriptDataWriter", vtkInstantiatorvtkJavaScriptDataWriterNew);
  vtkInstantiator::RegisterInstantiator("vtkJPEGReader", vtkInstantiatorvtkJPEGReaderNew);
  vtkInstantiator::RegisterInstantiator("vtkJPEGWriter", vtkInstantiatorvtkJPEGWriterNew);
  vtkInstantiator::RegisterInstantiator("vtkMFIXReader", vtkInstantiatorvtkMFIXReaderNew);
  vtkInstantiator::RegisterInstantiator("vtkMaterialLibrary", vtkInstantiatorvtkMaterialLibraryNew);
  vtkInstantiator::RegisterInstantiator("vtkMCubesReader", vtkInstantiatorvtkMCubesReaderNew);
  vtkInstantiator::RegisterInstantiator("vtkMCubesWriter", vtkInstantiatorvtkMCubesWriterNew);
  vtkInstantiator::RegisterInstantiator("vtkMedicalImageProperties", vtkInstantiatorvtkMedicalImagePropertiesNew);
  vtkInstantiator::RegisterInstantiator("vtkMedicalImageReader2", vtkInstantiatorvtkMedicalImageReader2New);
  vtkInstantiator::RegisterInstantiator("vtkMetaImageReader", vtkInstantiatorvtkMetaImageReaderNew);
  vtkInstantiator::RegisterInstantiator("vtkMetaImageWriter", vtkInstantiatorvtkMetaImageWriterNew);
  vtkInstantiator::RegisterInstantiator("vtkMINCImageAttributes", vtkInstantiatorvtkMINCImageAttributesNew);
  vtkInstantiator::RegisterInstantiator("vtkMINCImageReader", vtkInstantiatorvtkMINCImageReaderNew);
  vtkInstantiator::RegisterInstantiator("vtkMINCImageWriter", vtkInstantiatorvtkMINCImageWriterNew);
  vtkInstantiator::RegisterInstantiator("vtkMPASReader", vtkInstantiatorvtkMPASReaderNew);
  vtkInstantiator::RegisterInstantiator("vtkMultiBlockPLOT3DReader", vtkInstantiatorvtkMultiBlockPLOT3DReaderNew);
  vtkInstantiator::RegisterInstantiator("vtkNetCDFCFReader", vtkInstantiatorvtkNetCDFCFReaderNew);
  vtkInstantiator::RegisterInstantiator("vtkNetCDFPOPReader", vtkInstantiatorvtkNetCDFPOPReaderNew);
  vtkInstantiator::RegisterInstantiator("vtkNetCDFReader", vtkInstantiatorvtkNetCDFReaderNew);
  vtkInstantiator::RegisterInstantiator("vtkOBJReader", vtkInstantiatorvtkOBJReaderNew);
  vtkInstantiator::RegisterInstantiator("vtkOpenFOAMReader", vtkInstantiatorvtkOpenFOAMReaderNew);
  vtkInstantiator::RegisterInstantiator("vtkOutputStream", vtkInstantiatorvtkOutputStreamNew);
  vtkInstantiator::RegisterInstantiator("vtkPDBReader", vtkInstantiatorvtkPDBReaderNew);
  vtkInstantiator::RegisterInstantiator("vtkPLOT3DReader", vtkInstantiatorvtkPLOT3DReaderNew);
  vtkInstantiator::RegisterInstantiator("vtkPLYReader", vtkInstantiatorvtkPLYReaderNew);
  vtkInstantiator::RegisterInstantiator("vtkPLYWriter", vtkInstantiatorvtkPLYWriterNew);
  vtkInstantiator::RegisterInstantiator("vtkPNGReader", vtkInstantiatorvtkPNGReaderNew);
  vtkInstantiator::RegisterInstantiator("vtkPNGWriter", vtkInstantiatorvtkPNGWriterNew);
  vtkInstantiator::RegisterInstantiator("vtkPNMReader", vtkInstantiatorvtkPNMReaderNew);
  vtkInstantiator::RegisterInstantiator("vtkPNMWriter", vtkInstantiatorvtkPNMWriterNew);
  vtkInstantiator::RegisterInstantiator("vtkParticleReader", vtkInstantiatorvtkParticleReaderNew);
  vtkInstantiator::RegisterInstantiator("vtkPolyDataReader", vtkInstantiatorvtkPolyDataReaderNew);
  vtkInstantiator::RegisterInstantiator("vtkPolyDataWriter", vtkInstantiatorvtkPolyDataWriterNew);
  vtkInstantiator::RegisterInstantiator("vtkPostScriptWriter", vtkInstantiatorvtkPostScriptWriterNew);
  vtkInstantiator::RegisterInstantiator("vtkProStarReader", vtkInstantiatorvtkProStarReaderNew);
  vtkInstantiator::RegisterInstantiator("vtkRectilinearGridReader", vtkInstantiatorvtkRectilinearGridReaderNew);
  vtkInstantiator::RegisterInstantiator("vtkRectilinearGridWriter", vtkInstantiatorvtkRectilinearGridWriterNew);
  vtkInstantiator::RegisterInstantiator("vtkRTXMLPolyDataReader", vtkInstantiatorvtkRTXMLPolyDataReaderNew);
  vtkInstantiator::RegisterInstantiator("vtkSESAMEReader", vtkInstantiatorvtkSESAMEReaderNew);
  vtkInstantiator::RegisterInstantiator("vtkShaderCodeLibrary", vtkInstantiatorvtkShaderCodeLibraryNew);
  vtkInstantiator::RegisterInstantiator("vtkSLACParticleReader", vtkInstantiatorvtkSLACParticleReaderNew);
  vtkInstantiator::RegisterInstantiator("vtkSLACReader", vtkInstantiatorvtkSLACReaderNew);
  vtkInstantiator::RegisterInstantiator("vtkSQLDatabaseSchema", vtkInstantiatorvtkSQLDatabaseSchemaNew);
  vtkInstantiator::RegisterInstantiator("vtkSQLiteDatabase", vtkInstantiatorvtkSQLiteDatabaseNew);
  vtkInstantiator::RegisterInstantiator("vtkSQLiteToTableReader", vtkInstantiatorvtkSQLiteToTableReaderNew);
  vtkInstantiator::RegisterInstantiator("vtkSQLiteQuery", vtkInstantiatorvtkSQLiteQueryNew);
  vtkInstantiator::RegisterInstantiator("vtkSLCReader", vtkInstantiatorvtkSLCReaderNew);
  vtkInstantiator::RegisterInstantiator("vtkSTLReader", vtkInstantiatorvtkSTLReaderNew);
  vtkInstantiator::RegisterInstantiator("vtkSTLWriter", vtkInstantiatorvtkSTLWriterNew);
  vtkInstantiator::RegisterInstantiator("vtkSimplePointsReader", vtkInstantiatorvtkSimplePointsReaderNew);
  vtkInstantiator::RegisterInstantiator("vtkSortFileNames", vtkInstantiatorvtkSortFileNamesNew);
  vtkInstantiator::RegisterInstantiator("vtkStructuredGridReader", vtkInstantiatorvtkStructuredGridReaderNew);
  vtkInstantiator::RegisterInstantiator("vtkStructuredGridWriter", vtkInstantiatorvtkStructuredGridWriterNew);
  vtkInstantiator::RegisterInstantiator("vtkStructuredPointsReader", vtkInstantiatorvtkStructuredPointsReaderNew);
  vtkInstantiator::RegisterInstantiator("vtkStructuredPointsWriter", vtkInstantiatorvtkStructuredPointsWriterNew);
  vtkInstantiator::RegisterInstantiator("vtkTableReader", vtkInstantiatorvtkTableReaderNew);
  vtkInstantiator::RegisterInstantiator("vtkTableWriter", vtkInstantiatorvtkTableWriterNew);
  vtkInstantiator::RegisterInstantiator("vtkTableToSQLiteWriter", vtkInstantiatorvtkTableToSQLiteWriterNew);
  vtkInstantiator::RegisterInstantiator("vtkTecplotReader", vtkInstantiatorvtkTecplotReaderNew);
  vtkInstantiator::RegisterInstantiator("vtkTIFFReader", vtkInstantiatorvtkTIFFReaderNew);
  vtkInstantiator::RegisterInstantiator("vtkTIFFWriter", vtkInstantiatorvtkTIFFWriterNew);
  vtkInstantiator::RegisterInstantiator("vtkTreeReader", vtkInstantiatorvtkTreeReaderNew);
  vtkInstantiator::RegisterInstantiator("vtkTreeWriter", vtkInstantiatorvtkTreeWriterNew);
  vtkInstantiator::RegisterInstantiator("vtkUGFacetReader", vtkInstantiatorvtkUGFacetReaderNew);
  vtkInstantiator::RegisterInstantiator("vtkUnstructuredGridReader", vtkInstantiatorvtkUnstructuredGridReaderNew);
  vtkInstantiator::RegisterInstantiator("vtkUnstructuredGridWriter", vtkInstantiatorvtkUnstructuredGridWriterNew);
  vtkInstantiator::RegisterInstantiator("vtkUTF8TextCodec", vtkInstantiatorvtkUTF8TextCodecNew);
  vtkInstantiator::RegisterInstantiator("vtkUTF16TextCodec", vtkInstantiatorvtkUTF16TextCodecNew);
  vtkInstantiator::RegisterInstantiator("vtkVolume16Reader", vtkInstantiatorvtkVolume16ReaderNew);
  vtkInstantiator::RegisterInstantiator("vtkXMLDataParser", vtkInstantiatorvtkXMLDataParserNew);
  vtkInstantiator::RegisterInstantiator("vtkXMLDataSetWriter", vtkInstantiatorvtkXMLDataSetWriterNew);
  vtkInstantiator::RegisterInstantiator("vtkXMLFileReadTester", vtkInstantiatorvtkXMLFileReadTesterNew);
  vtkInstantiator::RegisterInstantiator("vtkXMLGenericDataObjectReader", vtkInstantiatorvtkXMLGenericDataObjectReaderNew);
  vtkInstantiator::RegisterInstantiator("vtkXMLHierarchicalBoxDataReader", vtkInstantiatorvtkXMLHierarchicalBoxDataReaderNew);
  vtkInstantiator::RegisterInstantiator("vtkXMLHierarchicalDataReader", vtkInstantiatorvtkXMLHierarchicalDataReaderNew);
  vtkInstantiator::RegisterInstantiator("vtkXMLImageDataReader", vtkInstantiatorvtkXMLImageDataReaderNew);
  vtkInstantiator::RegisterInstantiator("vtkXMLImageDataWriter", vtkInstantiatorvtkXMLImageDataWriterNew);
  vtkInstantiator::RegisterInstantiator("vtkXMLHyperOctreeReader", vtkInstantiatorvtkXMLHyperOctreeReaderNew);
  vtkInstantiator::RegisterInstantiator("vtkXMLHyperOctreeWriter", vtkInstantiatorvtkXMLHyperOctreeWriterNew);
  vtkInstantiator::RegisterInstantiator("vtkXMLMaterial", vtkInstantiatorvtkXMLMaterialNew);
  vtkInstantiator::RegisterInstantiator("vtkXMLMaterialParser", vtkInstantiatorvtkXMLMaterialParserNew);
  vtkInstantiator::RegisterInstantiator("vtkXMLMaterialReader", vtkInstantiatorvtkXMLMaterialReaderNew);
  vtkInstantiator::RegisterInstantiator("vtkXMLMultiBlockDataReader", vtkInstantiatorvtkXMLMultiBlockDataReaderNew);
  vtkInstantiator::RegisterInstantiator("vtkXMLMultiGroupDataReader", vtkInstantiatorvtkXMLMultiGroupDataReaderNew);
  vtkInstantiator::RegisterInstantiator("vtkXMLMultiBlockDataWriter", vtkInstantiatorvtkXMLMultiBlockDataWriterNew);
  vtkInstantiator::RegisterInstantiator("vtkXMLHierarchicalBoxDataWriter", vtkInstantiatorvtkXMLHierarchicalBoxDataWriterNew);
  vtkInstantiator::RegisterInstantiator("vtkXMLPDataSetWriter", vtkInstantiatorvtkXMLPDataSetWriterNew);
  vtkInstantiator::RegisterInstantiator("vtkXMLPImageDataReader", vtkInstantiatorvtkXMLPImageDataReaderNew);
  vtkInstantiator::RegisterInstantiator("vtkXMLPImageDataWriter", vtkInstantiatorvtkXMLPImageDataWriterNew);
  vtkInstantiator::RegisterInstantiator("vtkXMLPPolyDataReader", vtkInstantiatorvtkXMLPPolyDataReaderNew);
  vtkInstantiator::RegisterInstantiator("vtkXMLPPolyDataWriter", vtkInstantiatorvtkXMLPPolyDataWriterNew);
  vtkInstantiator::RegisterInstantiator("vtkXMLPRectilinearGridReader", vtkInstantiatorvtkXMLPRectilinearGridReaderNew);
  vtkInstantiator::RegisterInstantiator("vtkXMLPRectilinearGridWriter", vtkInstantiatorvtkXMLPRectilinearGridWriterNew);
  vtkInstantiator::RegisterInstantiator("vtkXMLPStructuredGridReader", vtkInstantiatorvtkXMLPStructuredGridReaderNew);
  vtkInstantiator::RegisterInstantiator("vtkXMLPStructuredGridWriter", vtkInstantiatorvtkXMLPStructuredGridWriterNew);
  vtkInstantiator::RegisterInstantiator("vtkXMLPUnstructuredGridReader", vtkInstantiatorvtkXMLPUnstructuredGridReaderNew);
  vtkInstantiator::RegisterInstantiator("vtkXMLPUnstructuredGridWriter", vtkInstantiatorvtkXMLPUnstructuredGridWriterNew);
  vtkInstantiator::RegisterInstantiator("vtkXMLParser", vtkInstantiatorvtkXMLParserNew);
  vtkInstantiator::RegisterInstantiator("vtkXMLPolyDataReader", vtkInstantiatorvtkXMLPolyDataReaderNew);
  vtkInstantiator::RegisterInstantiator("vtkXMLPolyDataWriter", vtkInstantiatorvtkXMLPolyDataWriterNew);
  vtkInstantiator::RegisterInstantiator("vtkXMLRectilinearGridReader", vtkInstantiatorvtkXMLRectilinearGridReaderNew);
  vtkInstantiator::RegisterInstantiator("vtkXMLRectilinearGridWriter", vtkInstantiatorvtkXMLRectilinearGridWriterNew);
  vtkInstantiator::RegisterInstantiator("vtkXMLShader", vtkInstantiatorvtkXMLShaderNew);
  vtkInstantiator::RegisterInstantiator("vtkXMLStructuredGridReader", vtkInstantiatorvtkXMLStructuredGridReaderNew);
  vtkInstantiator::RegisterInstantiator("vtkXMLStructuredGridWriter", vtkInstantiatorvtkXMLStructuredGridWriterNew);
  vtkInstantiator::RegisterInstantiator("vtkXMLUnstructuredGridReader", vtkInstantiatorvtkXMLUnstructuredGridReaderNew);
  vtkInstantiator::RegisterInstantiator("vtkXMLUnstructuredGridWriter", vtkInstantiatorvtkXMLUnstructuredGridWriterNew);
  vtkInstantiator::RegisterInstantiator("vtkXMLUtilities", vtkInstantiatorvtkXMLUtilitiesNew);
  vtkInstantiator::RegisterInstantiator("vtkXYZMolReader", vtkInstantiatorvtkXYZMolReaderNew);
  vtkInstantiator::RegisterInstantiator("vtkZLibDataCompressor", vtkInstantiatorvtkZLibDataCompressorNew);
  vtkInstantiator::RegisterInstantiator("vtkRowQueryToTable", vtkInstantiatorvtkRowQueryToTableNew);
  vtkInstantiator::RegisterInstantiator("vtkArrayReader", vtkInstantiatorvtkArrayReaderNew);
  vtkInstantiator::RegisterInstantiator("vtkArrayWriter", vtkInstantiatorvtkArrayWriterNew);

  
}
          
void vtkIOInstantiator::ClassFinalize()
{ 

  vtkInstantiator::UnRegisterInstantiator("vtkASCIITextCodec", vtkInstantiatorvtkASCIITextCodecNew);
  vtkInstantiator::UnRegisterInstantiator("vtkAVSucdReader", vtkInstantiatorvtkAVSucdReaderNew);
  vtkInstantiator::UnRegisterInstantiator("vtkBMPReader", vtkInstantiatorvtkBMPReaderNew);
  vtkInstantiator::UnRegisterInstantiator("vtkBMPWriter", vtkInstantiatorvtkBMPWriterNew);
  vtkInstantiator::UnRegisterInstantiator("vtkBYUReader", vtkInstantiatorvtkBYUReaderNew);
  vtkInstantiator::UnRegisterInstantiator("vtkBYUWriter", vtkInstantiatorvtkBYUWriterNew);
  vtkInstantiator::UnRegisterInstantiator("vtkBase64InputStream", vtkInstantiatorvtkBase64InputStreamNew);
  vtkInstantiator::UnRegisterInstantiator("vtkBase64OutputStream", vtkInstantiatorvtkBase64OutputStreamNew);
  vtkInstantiator::UnRegisterInstantiator("vtkBase64Utilities", vtkInstantiatorvtkBase64UtilitiesNew);
  vtkInstantiator::UnRegisterInstantiator("vtkCGMWriter", vtkInstantiatorvtkCGMWriterNew);
  vtkInstantiator::UnRegisterInstantiator("vtkChacoReader", vtkInstantiatorvtkChacoReaderNew);
  vtkInstantiator::UnRegisterInstantiator("vtkCompositeDataReader", vtkInstantiatorvtkCompositeDataReaderNew);
  vtkInstantiator::UnRegisterInstantiator("vtkCompositeDataWriter", vtkInstantiatorvtkCompositeDataWriterNew);
  vtkInstantiator::UnRegisterInstantiator("vtkDEMReader", vtkInstantiatorvtkDEMReaderNew);
  vtkInstantiator::UnRegisterInstantiator("vtkDICOMImageReader", vtkInstantiatorvtkDICOMImageReaderNew);
  vtkInstantiator::UnRegisterInstantiator("vtkDataObjectReader", vtkInstantiatorvtkDataObjectReaderNew);
  vtkInstantiator::UnRegisterInstantiator("vtkDataObjectWriter", vtkInstantiatorvtkDataObjectWriterNew);
  vtkInstantiator::UnRegisterInstantiator("vtkDataReader", vtkInstantiatorvtkDataReaderNew);
  vtkInstantiator::UnRegisterInstantiator("vtkDataSetReader", vtkInstantiatorvtkDataSetReaderNew);
  vtkInstantiator::UnRegisterInstantiator("vtkDataSetWriter", vtkInstantiatorvtkDataSetWriterNew);
  vtkInstantiator::UnRegisterInstantiator("vtkDataWriter", vtkInstantiatorvtkDataWriterNew);
  vtkInstantiator::UnRegisterInstantiator("vtkDelimitedTextWriter", vtkInstantiatorvtkDelimitedTextWriterNew);
  vtkInstantiator::UnRegisterInstantiator("vtkEnSight6BinaryReader", vtkInstantiatorvtkEnSight6BinaryReaderNew);
  vtkInstantiator::UnRegisterInstantiator("vtkEnSight6Reader", vtkInstantiatorvtkEnSight6ReaderNew);
  vtkInstantiator::UnRegisterInstantiator("vtkEnSightGoldBinaryReader", vtkInstantiatorvtkEnSightGoldBinaryReaderNew);
  vtkInstantiator::UnRegisterInstantiator("vtkEnSightGoldReader", vtkInstantiatorvtkEnSightGoldReaderNew);
  vtkInstantiator::UnRegisterInstantiator("vtkEnSightMasterServerReader", vtkInstantiatorvtkEnSightMasterServerReaderNew);
  vtkInstantiator::UnRegisterInstantiator("vtkFLUENTReader", vtkInstantiatorvtkFLUENTReaderNew);
  vtkInstantiator::UnRegisterInstantiator("vtkFacetWriter", vtkInstantiatorvtkFacetWriterNew);
  vtkInstantiator::UnRegisterInstantiator("vtkGESignaReader", vtkInstantiatorvtkGESignaReaderNew);
  vtkInstantiator::UnRegisterInstantiator("vtkGAMBITReader", vtkInstantiatorvtkGAMBITReaderNew);
  vtkInstantiator::UnRegisterInstantiator("vtkGaussianCubeReader", vtkInstantiatorvtkGaussianCubeReaderNew);
  vtkInstantiator::UnRegisterInstantiator("vtkGenericDataObjectReader", vtkInstantiatorvtkGenericDataObjectReaderNew);
  vtkInstantiator::UnRegisterInstantiator("vtkGenericDataObjectWriter", vtkInstantiatorvtkGenericDataObjectWriterNew);
  vtkInstantiator::UnRegisterInstantiator("vtkGenericEnSightReader", vtkInstantiatorvtkGenericEnSightReaderNew);
  vtkInstantiator::UnRegisterInstantiator("vtkGlobFileNames", vtkInstantiatorvtkGlobFileNamesNew);
  vtkInstantiator::UnRegisterInstantiator("vtkGraphReader", vtkInstantiatorvtkGraphReaderNew);
  vtkInstantiator::UnRegisterInstantiator("vtkGraphWriter", vtkInstantiatorvtkGraphWriterNew);
  vtkInstantiator::UnRegisterInstantiator("vtkIVWriter", vtkInstantiatorvtkIVWriterNew);
  vtkInstantiator::UnRegisterInstantiator("vtkImageReader", vtkInstantiatorvtkImageReaderNew);
  vtkInstantiator::UnRegisterInstantiator("vtkImageReader2", vtkInstantiatorvtkImageReader2New);
  vtkInstantiator::UnRegisterInstantiator("vtkImageReader2Collection", vtkInstantiatorvtkImageReader2CollectionNew);
  vtkInstantiator::UnRegisterInstantiator("vtkImageReader2Factory", vtkInstantiatorvtkImageReader2FactoryNew);
  vtkInstantiator::UnRegisterInstantiator("vtkImageWriter", vtkInstantiatorvtkImageWriterNew);
  vtkInstantiator::UnRegisterInstantiator("vtkInputStream", vtkInstantiatorvtkInputStreamNew);
  vtkInstantiator::UnRegisterInstantiator("vtkJavaScriptDataWriter", vtkInstantiatorvtkJavaScriptDataWriterNew);
  vtkInstantiator::UnRegisterInstantiator("vtkJPEGReader", vtkInstantiatorvtkJPEGReaderNew);
  vtkInstantiator::UnRegisterInstantiator("vtkJPEGWriter", vtkInstantiatorvtkJPEGWriterNew);
  vtkInstantiator::UnRegisterInstantiator("vtkMFIXReader", vtkInstantiatorvtkMFIXReaderNew);
  vtkInstantiator::UnRegisterInstantiator("vtkMaterialLibrary", vtkInstantiatorvtkMaterialLibraryNew);
  vtkInstantiator::UnRegisterInstantiator("vtkMCubesReader", vtkInstantiatorvtkMCubesReaderNew);
  vtkInstantiator::UnRegisterInstantiator("vtkMCubesWriter", vtkInstantiatorvtkMCubesWriterNew);
  vtkInstantiator::UnRegisterInstantiator("vtkMedicalImageProperties", vtkInstantiatorvtkMedicalImagePropertiesNew);
  vtkInstantiator::UnRegisterInstantiator("vtkMedicalImageReader2", vtkInstantiatorvtkMedicalImageReader2New);
  vtkInstantiator::UnRegisterInstantiator("vtkMetaImageReader", vtkInstantiatorvtkMetaImageReaderNew);
  vtkInstantiator::UnRegisterInstantiator("vtkMetaImageWriter", vtkInstantiatorvtkMetaImageWriterNew);
  vtkInstantiator::UnRegisterInstantiator("vtkMINCImageAttributes", vtkInstantiatorvtkMINCImageAttributesNew);
  vtkInstantiator::UnRegisterInstantiator("vtkMINCImageReader", vtkInstantiatorvtkMINCImageReaderNew);
  vtkInstantiator::UnRegisterInstantiator("vtkMINCImageWriter", vtkInstantiatorvtkMINCImageWriterNew);
  vtkInstantiator::UnRegisterInstantiator("vtkMPASReader", vtkInstantiatorvtkMPASReaderNew);
  vtkInstantiator::UnRegisterInstantiator("vtkMultiBlockPLOT3DReader", vtkInstantiatorvtkMultiBlockPLOT3DReaderNew);
  vtkInstantiator::UnRegisterInstantiator("vtkNetCDFCFReader", vtkInstantiatorvtkNetCDFCFReaderNew);
  vtkInstantiator::UnRegisterInstantiator("vtkNetCDFPOPReader", vtkInstantiatorvtkNetCDFPOPReaderNew);
  vtkInstantiator::UnRegisterInstantiator("vtkNetCDFReader", vtkInstantiatorvtkNetCDFReaderNew);
  vtkInstantiator::UnRegisterInstantiator("vtkOBJReader", vtkInstantiatorvtkOBJReaderNew);
  vtkInstantiator::UnRegisterInstantiator("vtkOpenFOAMReader", vtkInstantiatorvtkOpenFOAMReaderNew);
  vtkInstantiator::UnRegisterInstantiator("vtkOutputStream", vtkInstantiatorvtkOutputStreamNew);
  vtkInstantiator::UnRegisterInstantiator("vtkPDBReader", vtkInstantiatorvtkPDBReaderNew);
  vtkInstantiator::UnRegisterInstantiator("vtkPLOT3DReader", vtkInstantiatorvtkPLOT3DReaderNew);
  vtkInstantiator::UnRegisterInstantiator("vtkPLYReader", vtkInstantiatorvtkPLYReaderNew);
  vtkInstantiator::UnRegisterInstantiator("vtkPLYWriter", vtkInstantiatorvtkPLYWriterNew);
  vtkInstantiator::UnRegisterInstantiator("vtkPNGReader", vtkInstantiatorvtkPNGReaderNew);
  vtkInstantiator::UnRegisterInstantiator("vtkPNGWriter", vtkInstantiatorvtkPNGWriterNew);
  vtkInstantiator::UnRegisterInstantiator("vtkPNMReader", vtkInstantiatorvtkPNMReaderNew);
  vtkInstantiator::UnRegisterInstantiator("vtkPNMWriter", vtkInstantiatorvtkPNMWriterNew);
  vtkInstantiator::UnRegisterInstantiator("vtkParticleReader", vtkInstantiatorvtkParticleReaderNew);
  vtkInstantiator::UnRegisterInstantiator("vtkPolyDataReader", vtkInstantiatorvtkPolyDataReaderNew);
  vtkInstantiator::UnRegisterInstantiator("vtkPolyDataWriter", vtkInstantiatorvtkPolyDataWriterNew);
  vtkInstantiator::UnRegisterInstantiator("vtkPostScriptWriter", vtkInstantiatorvtkPostScriptWriterNew);
  vtkInstantiator::UnRegisterInstantiator("vtkProStarReader", vtkInstantiatorvtkProStarReaderNew);
  vtkInstantiator::UnRegisterInstantiator("vtkRectilinearGridReader", vtkInstantiatorvtkRectilinearGridReaderNew);
  vtkInstantiator::UnRegisterInstantiator("vtkRectilinearGridWriter", vtkInstantiatorvtkRectilinearGridWriterNew);
  vtkInstantiator::UnRegisterInstantiator("vtkRTXMLPolyDataReader", vtkInstantiatorvtkRTXMLPolyDataReaderNew);
  vtkInstantiator::UnRegisterInstantiator("vtkSESAMEReader", vtkInstantiatorvtkSESAMEReaderNew);
  vtkInstantiator::UnRegisterInstantiator("vtkShaderCodeLibrary", vtkInstantiatorvtkShaderCodeLibraryNew);
  vtkInstantiator::UnRegisterInstantiator("vtkSLACParticleReader", vtkInstantiatorvtkSLACParticleReaderNew);
  vtkInstantiator::UnRegisterInstantiator("vtkSLACReader", vtkInstantiatorvtkSLACReaderNew);
  vtkInstantiator::UnRegisterInstantiator("vtkSQLDatabaseSchema", vtkInstantiatorvtkSQLDatabaseSchemaNew);
  vtkInstantiator::UnRegisterInstantiator("vtkSQLiteDatabase", vtkInstantiatorvtkSQLiteDatabaseNew);
  vtkInstantiator::UnRegisterInstantiator("vtkSQLiteToTableReader", vtkInstantiatorvtkSQLiteToTableReaderNew);
  vtkInstantiator::UnRegisterInstantiator("vtkSQLiteQuery", vtkInstantiatorvtkSQLiteQueryNew);
  vtkInstantiator::UnRegisterInstantiator("vtkSLCReader", vtkInstantiatorvtkSLCReaderNew);
  vtkInstantiator::UnRegisterInstantiator("vtkSTLReader", vtkInstantiatorvtkSTLReaderNew);
  vtkInstantiator::UnRegisterInstantiator("vtkSTLWriter", vtkInstantiatorvtkSTLWriterNew);
  vtkInstantiator::UnRegisterInstantiator("vtkSimplePointsReader", vtkInstantiatorvtkSimplePointsReaderNew);
  vtkInstantiator::UnRegisterInstantiator("vtkSortFileNames", vtkInstantiatorvtkSortFileNamesNew);
  vtkInstantiator::UnRegisterInstantiator("vtkStructuredGridReader", vtkInstantiatorvtkStructuredGridReaderNew);
  vtkInstantiator::UnRegisterInstantiator("vtkStructuredGridWriter", vtkInstantiatorvtkStructuredGridWriterNew);
  vtkInstantiator::UnRegisterInstantiator("vtkStructuredPointsReader", vtkInstantiatorvtkStructuredPointsReaderNew);
  vtkInstantiator::UnRegisterInstantiator("vtkStructuredPointsWriter", vtkInstantiatorvtkStructuredPointsWriterNew);
  vtkInstantiator::UnRegisterInstantiator("vtkTableReader", vtkInstantiatorvtkTableReaderNew);
  vtkInstantiator::UnRegisterInstantiator("vtkTableWriter", vtkInstantiatorvtkTableWriterNew);
  vtkInstantiator::UnRegisterInstantiator("vtkTableToSQLiteWriter", vtkInstantiatorvtkTableToSQLiteWriterNew);
  vtkInstantiator::UnRegisterInstantiator("vtkTecplotReader", vtkInstantiatorvtkTecplotReaderNew);
  vtkInstantiator::UnRegisterInstantiator("vtkTIFFReader", vtkInstantiatorvtkTIFFReaderNew);
  vtkInstantiator::UnRegisterInstantiator("vtkTIFFWriter", vtkInstantiatorvtkTIFFWriterNew);
  vtkInstantiator::UnRegisterInstantiator("vtkTreeReader", vtkInstantiatorvtkTreeReaderNew);
  vtkInstantiator::UnRegisterInstantiator("vtkTreeWriter", vtkInstantiatorvtkTreeWriterNew);
  vtkInstantiator::UnRegisterInstantiator("vtkUGFacetReader", vtkInstantiatorvtkUGFacetReaderNew);
  vtkInstantiator::UnRegisterInstantiator("vtkUnstructuredGridReader", vtkInstantiatorvtkUnstructuredGridReaderNew);
  vtkInstantiator::UnRegisterInstantiator("vtkUnstructuredGridWriter", vtkInstantiatorvtkUnstructuredGridWriterNew);
  vtkInstantiator::UnRegisterInstantiator("vtkUTF8TextCodec", vtkInstantiatorvtkUTF8TextCodecNew);
  vtkInstantiator::UnRegisterInstantiator("vtkUTF16TextCodec", vtkInstantiatorvtkUTF16TextCodecNew);
  vtkInstantiator::UnRegisterInstantiator("vtkVolume16Reader", vtkInstantiatorvtkVolume16ReaderNew);
  vtkInstantiator::UnRegisterInstantiator("vtkXMLDataParser", vtkInstantiatorvtkXMLDataParserNew);
  vtkInstantiator::UnRegisterInstantiator("vtkXMLDataSetWriter", vtkInstantiatorvtkXMLDataSetWriterNew);
  vtkInstantiator::UnRegisterInstantiator("vtkXMLFileReadTester", vtkInstantiatorvtkXMLFileReadTesterNew);
  vtkInstantiator::UnRegisterInstantiator("vtkXMLGenericDataObjectReader", vtkInstantiatorvtkXMLGenericDataObjectReaderNew);
  vtkInstantiator::UnRegisterInstantiator("vtkXMLHierarchicalBoxDataReader", vtkInstantiatorvtkXMLHierarchicalBoxDataReaderNew);
  vtkInstantiator::UnRegisterInstantiator("vtkXMLHierarchicalDataReader", vtkInstantiatorvtkXMLHierarchicalDataReaderNew);
  vtkInstantiator::UnRegisterInstantiator("vtkXMLImageDataReader", vtkInstantiatorvtkXMLImageDataReaderNew);
  vtkInstantiator::UnRegisterInstantiator("vtkXMLImageDataWriter", vtkInstantiatorvtkXMLImageDataWriterNew);
  vtkInstantiator::UnRegisterInstantiator("vtkXMLHyperOctreeReader", vtkInstantiatorvtkXMLHyperOctreeReaderNew);
  vtkInstantiator::UnRegisterInstantiator("vtkXMLHyperOctreeWriter", vtkInstantiatorvtkXMLHyperOctreeWriterNew);
  vtkInstantiator::UnRegisterInstantiator("vtkXMLMaterial", vtkInstantiatorvtkXMLMaterialNew);
  vtkInstantiator::UnRegisterInstantiator("vtkXMLMaterialParser", vtkInstantiatorvtkXMLMaterialParserNew);
  vtkInstantiator::UnRegisterInstantiator("vtkXMLMaterialReader", vtkInstantiatorvtkXMLMaterialReaderNew);
  vtkInstantiator::UnRegisterInstantiator("vtkXMLMultiBlockDataReader", vtkInstantiatorvtkXMLMultiBlockDataReaderNew);
  vtkInstantiator::UnRegisterInstantiator("vtkXMLMultiGroupDataReader", vtkInstantiatorvtkXMLMultiGroupDataReaderNew);
  vtkInstantiator::UnRegisterInstantiator("vtkXMLMultiBlockDataWriter", vtkInstantiatorvtkXMLMultiBlockDataWriterNew);
  vtkInstantiator::UnRegisterInstantiator("vtkXMLHierarchicalBoxDataWriter", vtkInstantiatorvtkXMLHierarchicalBoxDataWriterNew);
  vtkInstantiator::UnRegisterInstantiator("vtkXMLPDataSetWriter", vtkInstantiatorvtkXMLPDataSetWriterNew);
  vtkInstantiator::UnRegisterInstantiator("vtkXMLPImageDataReader", vtkInstantiatorvtkXMLPImageDataReaderNew);
  vtkInstantiator::UnRegisterInstantiator("vtkXMLPImageDataWriter", vtkInstantiatorvtkXMLPImageDataWriterNew);
  vtkInstantiator::UnRegisterInstantiator("vtkXMLPPolyDataReader", vtkInstantiatorvtkXMLPPolyDataReaderNew);
  vtkInstantiator::UnRegisterInstantiator("vtkXMLPPolyDataWriter", vtkInstantiatorvtkXMLPPolyDataWriterNew);
  vtkInstantiator::UnRegisterInstantiator("vtkXMLPRectilinearGridReader", vtkInstantiatorvtkXMLPRectilinearGridReaderNew);
  vtkInstantiator::UnRegisterInstantiator("vtkXMLPRectilinearGridWriter", vtkInstantiatorvtkXMLPRectilinearGridWriterNew);
  vtkInstantiator::UnRegisterInstantiator("vtkXMLPStructuredGridReader", vtkInstantiatorvtkXMLPStructuredGridReaderNew);
  vtkInstantiator::UnRegisterInstantiator("vtkXMLPStructuredGridWriter", vtkInstantiatorvtkXMLPStructuredGridWriterNew);
  vtkInstantiator::UnRegisterInstantiator("vtkXMLPUnstructuredGridReader", vtkInstantiatorvtkXMLPUnstructuredGridReaderNew);
  vtkInstantiator::UnRegisterInstantiator("vtkXMLPUnstructuredGridWriter", vtkInstantiatorvtkXMLPUnstructuredGridWriterNew);
  vtkInstantiator::UnRegisterInstantiator("vtkXMLParser", vtkInstantiatorvtkXMLParserNew);
  vtkInstantiator::UnRegisterInstantiator("vtkXMLPolyDataReader", vtkInstantiatorvtkXMLPolyDataReaderNew);
  vtkInstantiator::UnRegisterInstantiator("vtkXMLPolyDataWriter", vtkInstantiatorvtkXMLPolyDataWriterNew);
  vtkInstantiator::UnRegisterInstantiator("vtkXMLRectilinearGridReader", vtkInstantiatorvtkXMLRectilinearGridReaderNew);
  vtkInstantiator::UnRegisterInstantiator("vtkXMLRectilinearGridWriter", vtkInstantiatorvtkXMLRectilinearGridWriterNew);
  vtkInstantiator::UnRegisterInstantiator("vtkXMLShader", vtkInstantiatorvtkXMLShaderNew);
  vtkInstantiator::UnRegisterInstantiator("vtkXMLStructuredGridReader", vtkInstantiatorvtkXMLStructuredGridReaderNew);
  vtkInstantiator::UnRegisterInstantiator("vtkXMLStructuredGridWriter", vtkInstantiatorvtkXMLStructuredGridWriterNew);
  vtkInstantiator::UnRegisterInstantiator("vtkXMLUnstructuredGridReader", vtkInstantiatorvtkXMLUnstructuredGridReaderNew);
  vtkInstantiator::UnRegisterInstantiator("vtkXMLUnstructuredGridWriter", vtkInstantiatorvtkXMLUnstructuredGridWriterNew);
  vtkInstantiator::UnRegisterInstantiator("vtkXMLUtilities", vtkInstantiatorvtkXMLUtilitiesNew);
  vtkInstantiator::UnRegisterInstantiator("vtkXYZMolReader", vtkInstantiatorvtkXYZMolReaderNew);
  vtkInstantiator::UnRegisterInstantiator("vtkZLibDataCompressor", vtkInstantiatorvtkZLibDataCompressorNew);
  vtkInstantiator::UnRegisterInstantiator("vtkRowQueryToTable", vtkInstantiatorvtkRowQueryToTableNew);
  vtkInstantiator::UnRegisterInstantiator("vtkArrayReader", vtkInstantiatorvtkArrayReaderNew);
  vtkInstantiator::UnRegisterInstantiator("vtkArrayWriter", vtkInstantiatorvtkArrayWriterNew);

  
}

vtkIOInstantiator::vtkIOInstantiator()
{
  if(++vtkIOInstantiator::Count == 1)
    { 
    vtkIOInstantiator::ClassInitialize(); 
    }
}

vtkIOInstantiator::~vtkIOInstantiator()
{
  if(--vtkIOInstantiator::Count == 0)
    { 
    vtkIOInstantiator::ClassFinalize(); 
    }
}

// Number of translation units that include this class's header.
// Purposely not initialized.  Default is static initialization to 0.
unsigned int vtkIOInstantiator::Count;
