#include "vtkImagingInstantiator.h"
  
extern vtkObject* vtkInstantiatorvtkBooleanTextureNew();
extern vtkObject* vtkInstantiatorvtkExtractVOINew();
extern vtkObject* vtkInstantiatorvtkFastSplatterNew();
extern vtkObject* vtkInstantiatorvtkGaussianSplatterNew();
extern vtkObject* vtkInstantiatorvtkImageAccumulateNew();
extern vtkObject* vtkInstantiatorvtkImageAnisotropicDiffusion2DNew();
extern vtkObject* vtkInstantiatorvtkImageAnisotropicDiffusion3DNew();
extern vtkObject* vtkInstantiatorvtkImageAppendNew();
extern vtkObject* vtkInstantiatorvtkImageAppendComponentsNew();
extern vtkObject* vtkInstantiatorvtkImageBlendNew();
extern vtkObject* vtkInstantiatorvtkImageButterworthHighPassNew();
extern vtkObject* vtkInstantiatorvtkImageButterworthLowPassNew();
extern vtkObject* vtkInstantiatorvtkImageCacheFilterNew();
extern vtkObject* vtkInstantiatorvtkImageCanvasSource2DNew();
extern vtkObject* vtkInstantiatorvtkImageCastNew();
extern vtkObject* vtkInstantiatorvtkImageChangeInformationNew();
extern vtkObject* vtkInstantiatorvtkImageCheckerboardNew();
extern vtkObject* vtkInstantiatorvtkImageCityBlockDistanceNew();
extern vtkObject* vtkInstantiatorvtkImageClipNew();
extern vtkObject* vtkInstantiatorvtkImageConnectorNew();
extern vtkObject* vtkInstantiatorvtkImageConstantPadNew();
extern vtkObject* vtkInstantiatorvtkImageContinuousDilate3DNew();
extern vtkObject* vtkInstantiatorvtkImageContinuousErode3DNew();
extern vtkObject* vtkInstantiatorvtkImageConvolveNew();
extern vtkObject* vtkInstantiatorvtkImageCorrelationNew();
extern vtkObject* vtkInstantiatorvtkImageCursor3DNew();
extern vtkObject* vtkInstantiatorvtkImageDataStreamerNew();
extern vtkObject* vtkInstantiatorvtkImageDifferenceNew();
extern vtkObject* vtkInstantiatorvtkImageDilateErode3DNew();
extern vtkObject* vtkInstantiatorvtkImageDivergenceNew();
extern vtkObject* vtkInstantiatorvtkImageDotProductNew();
extern vtkObject* vtkInstantiatorvtkImageEllipsoidSourceNew();
extern vtkObject* vtkInstantiatorvtkImageEuclideanDistanceNew();
extern vtkObject* vtkInstantiatorvtkImageEuclideanToPolarNew();
extern vtkObject* vtkInstantiatorvtkImageExportNew();
extern vtkObject* vtkInstantiatorvtkImageExtractComponentsNew();
extern vtkObject* vtkInstantiatorvtkImageFFTNew();
extern vtkObject* vtkInstantiatorvtkImageFlipNew();
extern vtkObject* vtkInstantiatorvtkImageFourierCenterNew();
extern vtkObject* vtkInstantiatorvtkImageGaussianSmoothNew();
extern vtkObject* vtkInstantiatorvtkImageGaussianSourceNew();
extern vtkObject* vtkInstantiatorvtkImageGradientNew();
extern vtkObject* vtkInstantiatorvtkImageGradientMagnitudeNew();
extern vtkObject* vtkInstantiatorvtkImageGridSourceNew();
extern vtkObject* vtkInstantiatorvtkImageHSIToRGBNew();
extern vtkObject* vtkInstantiatorvtkImageHSVToRGBNew();
extern vtkObject* vtkInstantiatorvtkImageHybridMedian2DNew();
extern vtkObject* vtkInstantiatorvtkImageIdealHighPassNew();
extern vtkObject* vtkInstantiatorvtkImageIdealLowPassNew();
extern vtkObject* vtkInstantiatorvtkImageImportNew();
extern vtkObject* vtkInstantiatorvtkImageImportExecutiveNew();
extern vtkObject* vtkInstantiatorvtkImageIslandRemoval2DNew();
extern vtkObject* vtkInstantiatorvtkImageLaplacianNew();
extern vtkObject* vtkInstantiatorvtkImageLogarithmicScaleNew();
extern vtkObject* vtkInstantiatorvtkImageLogicNew();
extern vtkObject* vtkInstantiatorvtkImageLuminanceNew();
extern vtkObject* vtkInstantiatorvtkImageMagnifyNew();
extern vtkObject* vtkInstantiatorvtkImageMagnitudeNew();
extern vtkObject* vtkInstantiatorvtkImageMandelbrotSourceNew();
extern vtkObject* vtkInstantiatorvtkImageMapToColorsNew();
extern vtkObject* vtkInstantiatorvtkImageMapToRGBANew();
extern vtkObject* vtkInstantiatorvtkImageMapToWindowLevelColorsNew();
extern vtkObject* vtkInstantiatorvtkImageMaskNew();
extern vtkObject* vtkInstantiatorvtkImageMaskBitsNew();
extern vtkObject* vtkInstantiatorvtkImageMathematicsNew();
extern vtkObject* vtkInstantiatorvtkImageMedian3DNew();
extern vtkObject* vtkInstantiatorvtkImageMirrorPadNew();
extern vtkObject* vtkInstantiatorvtkImageNoiseSourceNew();
extern vtkObject* vtkInstantiatorvtkImageNonMaximumSuppressionNew();
extern vtkObject* vtkInstantiatorvtkImageNormalizeNew();
extern vtkObject* vtkInstantiatorvtkImageOpenClose3DNew();
extern vtkObject* vtkInstantiatorvtkImagePermuteNew();
extern vtkObject* vtkInstantiatorvtkImageSlabNew();
extern vtkObject* vtkInstantiatorvtkImageQuantizeRGBToIndexNew();
extern vtkObject* vtkInstantiatorvtkImageRFFTNew();
extern vtkObject* vtkInstantiatorvtkImageRGBToHSINew();
extern vtkObject* vtkInstantiatorvtkImageRGBToHSVNew();
extern vtkObject* vtkInstantiatorvtkImageRange3DNew();
extern vtkObject* vtkInstantiatorvtkImageRectilinearWipeNew();
extern vtkObject* vtkInstantiatorvtkImageResampleNew();
extern vtkObject* vtkInstantiatorvtkImageResliceNew();
extern vtkObject* vtkInstantiatorvtkImageSeedConnectivityNew();
extern vtkObject* vtkInstantiatorvtkImageSeparableConvolutionNew();
extern vtkObject* vtkInstantiatorvtkImageShiftScaleNew();
extern vtkObject* vtkInstantiatorvtkImageShrink3DNew();
extern vtkObject* vtkInstantiatorvtkImageSinusoidSourceNew();
extern vtkObject* vtkInstantiatorvtkImageSkeleton2DNew();
extern vtkObject* vtkInstantiatorvtkImageSobel2DNew();
extern vtkObject* vtkInstantiatorvtkImageSobel3DNew();
extern vtkObject* vtkInstantiatorvtkImageStencilNew();
extern vtkObject* vtkInstantiatorvtkImageStencilToImageNew();
extern vtkObject* vtkInstantiatorvtkImageStencilAlgorithmNew();
extern vtkObject* vtkInstantiatorvtkImageStencilDataNew();
extern vtkObject* vtkInstantiatorvtkImageStencilSourceNew();
extern vtkObject* vtkInstantiatorvtkImageThresholdNew();
extern vtkObject* vtkInstantiatorvtkImageToImageStencilNew();
extern vtkObject* vtkInstantiatorvtkImageTranslateExtentNew();
extern vtkObject* vtkInstantiatorvtkImageVariance3DNew();
extern vtkObject* vtkInstantiatorvtkImageWrapPadNew();
extern vtkObject* vtkInstantiatorvtkImageWeightedSumNew();
extern vtkObject* vtkInstantiatorvtkImplicitFunctionToImageStencilNew();
extern vtkObject* vtkInstantiatorvtkLassoStencilSourceNew();
extern vtkObject* vtkInstantiatorvtkPointLoadNew();
extern vtkObject* vtkInstantiatorvtkROIStencilSourceNew();
extern vtkObject* vtkInstantiatorvtkRTAnalyticSourceNew();
extern vtkObject* vtkInstantiatorvtkSampleFunctionNew();
extern vtkObject* vtkInstantiatorvtkShepardMethodNew();
extern vtkObject* vtkInstantiatorvtkSimpleImageFilterExampleNew();
extern vtkObject* vtkInstantiatorvtkSurfaceReconstructionFilterNew();
extern vtkObject* vtkInstantiatorvtkTriangularTextureNew();
extern vtkObject* vtkInstantiatorvtkVoxelModellerNew();


  
void vtkImagingInstantiator::ClassInitialize()
{
  
  vtkInstantiator::RegisterInstantiator("vtkBooleanTexture", vtkInstantiatorvtkBooleanTextureNew);
  vtkInstantiator::RegisterInstantiator("vtkExtractVOI", vtkInstantiatorvtkExtractVOINew);
  vtkInstantiator::RegisterInstantiator("vtkFastSplatter", vtkInstantiatorvtkFastSplatterNew);
  vtkInstantiator::RegisterInstantiator("vtkGaussianSplatter", vtkInstantiatorvtkGaussianSplatterNew);
  vtkInstantiator::RegisterInstantiator("vtkImageAccumulate", vtkInstantiatorvtkImageAccumulateNew);
  vtkInstantiator::RegisterInstantiator("vtkImageAnisotropicDiffusion2D", vtkInstantiatorvtkImageAnisotropicDiffusion2DNew);
  vtkInstantiator::RegisterInstantiator("vtkImageAnisotropicDiffusion3D", vtkInstantiatorvtkImageAnisotropicDiffusion3DNew);
  vtkInstantiator::RegisterInstantiator("vtkImageAppend", vtkInstantiatorvtkImageAppendNew);
  vtkInstantiator::RegisterInstantiator("vtkImageAppendComponents", vtkInstantiatorvtkImageAppendComponentsNew);
  vtkInstantiator::RegisterInstantiator("vtkImageBlend", vtkInstantiatorvtkImageBlendNew);
  vtkInstantiator::RegisterInstantiator("vtkImageButterworthHighPass", vtkInstantiatorvtkImageButterworthHighPassNew);
  vtkInstantiator::RegisterInstantiator("vtkImageButterworthLowPass", vtkInstantiatorvtkImageButterworthLowPassNew);
  vtkInstantiator::RegisterInstantiator("vtkImageCacheFilter", vtkInstantiatorvtkImageCacheFilterNew);
  vtkInstantiator::RegisterInstantiator("vtkImageCanvasSource2D", vtkInstantiatorvtkImageCanvasSource2DNew);
  vtkInstantiator::RegisterInstantiator("vtkImageCast", vtkInstantiatorvtkImageCastNew);
  vtkInstantiator::RegisterInstantiator("vtkImageChangeInformation", vtkInstantiatorvtkImageChangeInformationNew);
  vtkInstantiator::RegisterInstantiator("vtkImageCheckerboard", vtkInstantiatorvtkImageCheckerboardNew);
  vtkInstantiator::RegisterInstantiator("vtkImageCityBlockDistance", vtkInstantiatorvtkImageCityBlockDistanceNew);
  vtkInstantiator::RegisterInstantiator("vtkImageClip", vtkInstantiatorvtkImageClipNew);
  vtkInstantiator::RegisterInstantiator("vtkImageConnector", vtkInstantiatorvtkImageConnectorNew);
  vtkInstantiator::RegisterInstantiator("vtkImageConstantPad", vtkInstantiatorvtkImageConstantPadNew);
  vtkInstantiator::RegisterInstantiator("vtkImageContinuousDilate3D", vtkInstantiatorvtkImageContinuousDilate3DNew);
  vtkInstantiator::RegisterInstantiator("vtkImageContinuousErode3D", vtkInstantiatorvtkImageContinuousErode3DNew);
  vtkInstantiator::RegisterInstantiator("vtkImageConvolve", vtkInstantiatorvtkImageConvolveNew);
  vtkInstantiator::RegisterInstantiator("vtkImageCorrelation", vtkInstantiatorvtkImageCorrelationNew);
  vtkInstantiator::RegisterInstantiator("vtkImageCursor3D", vtkInstantiatorvtkImageCursor3DNew);
  vtkInstantiator::RegisterInstantiator("vtkImageDataStreamer", vtkInstantiatorvtkImageDataStreamerNew);
  vtkInstantiator::RegisterInstantiator("vtkImageDifference", vtkInstantiatorvtkImageDifferenceNew);
  vtkInstantiator::RegisterInstantiator("vtkImageDilateErode3D", vtkInstantiatorvtkImageDilateErode3DNew);
  vtkInstantiator::RegisterInstantiator("vtkImageDivergence", vtkInstantiatorvtkImageDivergenceNew);
  vtkInstantiator::RegisterInstantiator("vtkImageDotProduct", vtkInstantiatorvtkImageDotProductNew);
  vtkInstantiator::RegisterInstantiator("vtkImageEllipsoidSource", vtkInstantiatorvtkImageEllipsoidSourceNew);
  vtkInstantiator::RegisterInstantiator("vtkImageEuclideanDistance", vtkInstantiatorvtkImageEuclideanDistanceNew);
  vtkInstantiator::RegisterInstantiator("vtkImageEuclideanToPolar", vtkInstantiatorvtkImageEuclideanToPolarNew);
  vtkInstantiator::RegisterInstantiator("vtkImageExport", vtkInstantiatorvtkImageExportNew);
  vtkInstantiator::RegisterInstantiator("vtkImageExtractComponents", vtkInstantiatorvtkImageExtractComponentsNew);
  vtkInstantiator::RegisterInstantiator("vtkImageFFT", vtkInstantiatorvtkImageFFTNew);
  vtkInstantiator::RegisterInstantiator("vtkImageFlip", vtkInstantiatorvtkImageFlipNew);
  vtkInstantiator::RegisterInstantiator("vtkImageFourierCenter", vtkInstantiatorvtkImageFourierCenterNew);
  vtkInstantiator::RegisterInstantiator("vtkImageGaussianSmooth", vtkInstantiatorvtkImageGaussianSmoothNew);
  vtkInstantiator::RegisterInstantiator("vtkImageGaussianSource", vtkInstantiatorvtkImageGaussianSourceNew);
  vtkInstantiator::RegisterInstantiator("vtkImageGradient", vtkInstantiatorvtkImageGradientNew);
  vtkInstantiator::RegisterInstantiator("vtkImageGradientMagnitude", vtkInstantiatorvtkImageGradientMagnitudeNew);
  vtkInstantiator::RegisterInstantiator("vtkImageGridSource", vtkInstantiatorvtkImageGridSourceNew);
  vtkInstantiator::RegisterInstantiator("vtkImageHSIToRGB", vtkInstantiatorvtkImageHSIToRGBNew);
  vtkInstantiator::RegisterInstantiator("vtkImageHSVToRGB", vtkInstantiatorvtkImageHSVToRGBNew);
  vtkInstantiator::RegisterInstantiator("vtkImageHybridMedian2D", vtkInstantiatorvtkImageHybridMedian2DNew);
  vtkInstantiator::RegisterInstantiator("vtkImageIdealHighPass", vtkInstantiatorvtkImageIdealHighPassNew);
  vtkInstantiator::RegisterInstantiator("vtkImageIdealLowPass", vtkInstantiatorvtkImageIdealLowPassNew);
  vtkInstantiator::RegisterInstantiator("vtkImageImport", vtkInstantiatorvtkImageImportNew);
  vtkInstantiator::RegisterInstantiator("vtkImageImportExecutive", vtkInstantiatorvtkImageImportExecutiveNew);
  vtkInstantiator::RegisterInstantiator("vtkImageIslandRemoval2D", vtkInstantiatorvtkImageIslandRemoval2DNew);
  vtkInstantiator::RegisterInstantiator("vtkImageLaplacian", vtkInstantiatorvtkImageLaplacianNew);
  vtkInstantiator::RegisterInstantiator("vtkImageLogarithmicScale", vtkInstantiatorvtkImageLogarithmicScaleNew);
  vtkInstantiator::RegisterInstantiator("vtkImageLogic", vtkInstantiatorvtkImageLogicNew);
  vtkInstantiator::RegisterInstantiator("vtkImageLuminance", vtkInstantiatorvtkImageLuminanceNew);
  vtkInstantiator::RegisterInstantiator("vtkImageMagnify", vtkInstantiatorvtkImageMagnifyNew);
  vtkInstantiator::RegisterInstantiator("vtkImageMagnitude", vtkInstantiatorvtkImageMagnitudeNew);
  vtkInstantiator::RegisterInstantiator("vtkImageMandelbrotSource", vtkInstantiatorvtkImageMandelbrotSourceNew);
  vtkInstantiator::RegisterInstantiator("vtkImageMapToColors", vtkInstantiatorvtkImageMapToColorsNew);
  vtkInstantiator::RegisterInstantiator("vtkImageMapToRGBA", vtkInstantiatorvtkImageMapToRGBANew);
  vtkInstantiator::RegisterInstantiator("vtkImageMapToWindowLevelColors", vtkInstantiatorvtkImageMapToWindowLevelColorsNew);
  vtkInstantiator::RegisterInstantiator("vtkImageMask", vtkInstantiatorvtkImageMaskNew);
  vtkInstantiator::RegisterInstantiator("vtkImageMaskBits", vtkInstantiatorvtkImageMaskBitsNew);
  vtkInstantiator::RegisterInstantiator("vtkImageMathematics", vtkInstantiatorvtkImageMathematicsNew);
  vtkInstantiator::RegisterInstantiator("vtkImageMedian3D", vtkInstantiatorvtkImageMedian3DNew);
  vtkInstantiator::RegisterInstantiator("vtkImageMirrorPad", vtkInstantiatorvtkImageMirrorPadNew);
  vtkInstantiator::RegisterInstantiator("vtkImageNoiseSource", vtkInstantiatorvtkImageNoiseSourceNew);
  vtkInstantiator::RegisterInstantiator("vtkImageNonMaximumSuppression", vtkInstantiatorvtkImageNonMaximumSuppressionNew);
  vtkInstantiator::RegisterInstantiator("vtkImageNormalize", vtkInstantiatorvtkImageNormalizeNew);
  vtkInstantiator::RegisterInstantiator("vtkImageOpenClose3D", vtkInstantiatorvtkImageOpenClose3DNew);
  vtkInstantiator::RegisterInstantiator("vtkImagePermute", vtkInstantiatorvtkImagePermuteNew);
  vtkInstantiator::RegisterInstantiator("vtkImageSlab", vtkInstantiatorvtkImageSlabNew);
  vtkInstantiator::RegisterInstantiator("vtkImageQuantizeRGBToIndex", vtkInstantiatorvtkImageQuantizeRGBToIndexNew);
  vtkInstantiator::RegisterInstantiator("vtkImageRFFT", vtkInstantiatorvtkImageRFFTNew);
  vtkInstantiator::RegisterInstantiator("vtkImageRGBToHSI", vtkInstantiatorvtkImageRGBToHSINew);
  vtkInstantiator::RegisterInstantiator("vtkImageRGBToHSV", vtkInstantiatorvtkImageRGBToHSVNew);
  vtkInstantiator::RegisterInstantiator("vtkImageRange3D", vtkInstantiatorvtkImageRange3DNew);
  vtkInstantiator::RegisterInstantiator("vtkImageRectilinearWipe", vtkInstantiatorvtkImageRectilinearWipeNew);
  vtkInstantiator::RegisterInstantiator("vtkImageResample", vtkInstantiatorvtkImageResampleNew);
  vtkInstantiator::RegisterInstantiator("vtkImageReslice", vtkInstantiatorvtkImageResliceNew);
  vtkInstantiator::RegisterInstantiator("vtkImageSeedConnectivity", vtkInstantiatorvtkImageSeedConnectivityNew);
  vtkInstantiator::RegisterInstantiator("vtkImageSeparableConvolution", vtkInstantiatorvtkImageSeparableConvolutionNew);
  vtkInstantiator::RegisterInstantiator("vtkImageShiftScale", vtkInstantiatorvtkImageShiftScaleNew);
  vtkInstantiator::RegisterInstantiator("vtkImageShrink3D", vtkInstantiatorvtkImageShrink3DNew);
  vtkInstantiator::RegisterInstantiator("vtkImageSinusoidSource", vtkInstantiatorvtkImageSinusoidSourceNew);
  vtkInstantiator::RegisterInstantiator("vtkImageSkeleton2D", vtkInstantiatorvtkImageSkeleton2DNew);
  vtkInstantiator::RegisterInstantiator("vtkImageSobel2D", vtkInstantiatorvtkImageSobel2DNew);
  vtkInstantiator::RegisterInstantiator("vtkImageSobel3D", vtkInstantiatorvtkImageSobel3DNew);
  vtkInstantiator::RegisterInstantiator("vtkImageStencil", vtkInstantiatorvtkImageStencilNew);
  vtkInstantiator::RegisterInstantiator("vtkImageStencilToImage", vtkInstantiatorvtkImageStencilToImageNew);
  vtkInstantiator::RegisterInstantiator("vtkImageStencilAlgorithm", vtkInstantiatorvtkImageStencilAlgorithmNew);
  vtkInstantiator::RegisterInstantiator("vtkImageStencilData", vtkInstantiatorvtkImageStencilDataNew);
  vtkInstantiator::RegisterInstantiator("vtkImageStencilSource", vtkInstantiatorvtkImageStencilSourceNew);
  vtkInstantiator::RegisterInstantiator("vtkImageThreshold", vtkInstantiatorvtkImageThresholdNew);
  vtkInstantiator::RegisterInstantiator("vtkImageToImageStencil", vtkInstantiatorvtkImageToImageStencilNew);
  vtkInstantiator::RegisterInstantiator("vtkImageTranslateExtent", vtkInstantiatorvtkImageTranslateExtentNew);
  vtkInstantiator::RegisterInstantiator("vtkImageVariance3D", vtkInstantiatorvtkImageVariance3DNew);
  vtkInstantiator::RegisterInstantiator("vtkImageWrapPad", vtkInstantiatorvtkImageWrapPadNew);
  vtkInstantiator::RegisterInstantiator("vtkImageWeightedSum", vtkInstantiatorvtkImageWeightedSumNew);
  vtkInstantiator::RegisterInstantiator("vtkImplicitFunctionToImageStencil", vtkInstantiatorvtkImplicitFunctionToImageStencilNew);
  vtkInstantiator::RegisterInstantiator("vtkLassoStencilSource", vtkInstantiatorvtkLassoStencilSourceNew);
  vtkInstantiator::RegisterInstantiator("vtkPointLoad", vtkInstantiatorvtkPointLoadNew);
  vtkInstantiator::RegisterInstantiator("vtkROIStencilSource", vtkInstantiatorvtkROIStencilSourceNew);
  vtkInstantiator::RegisterInstantiator("vtkRTAnalyticSource", vtkInstantiatorvtkRTAnalyticSourceNew);
  vtkInstantiator::RegisterInstantiator("vtkSampleFunction", vtkInstantiatorvtkSampleFunctionNew);
  vtkInstantiator::RegisterInstantiator("vtkShepardMethod", vtkInstantiatorvtkShepardMethodNew);
  vtkInstantiator::RegisterInstantiator("vtkSimpleImageFilterExample", vtkInstantiatorvtkSimpleImageFilterExampleNew);
  vtkInstantiator::RegisterInstantiator("vtkSurfaceReconstructionFilter", vtkInstantiatorvtkSurfaceReconstructionFilterNew);
  vtkInstantiator::RegisterInstantiator("vtkTriangularTexture", vtkInstantiatorvtkTriangularTextureNew);
  vtkInstantiator::RegisterInstantiator("vtkVoxelModeller", vtkInstantiatorvtkVoxelModellerNew);

  
}
          
void vtkImagingInstantiator::ClassFinalize()
{ 

  vtkInstantiator::UnRegisterInstantiator("vtkBooleanTexture", vtkInstantiatorvtkBooleanTextureNew);
  vtkInstantiator::UnRegisterInstantiator("vtkExtractVOI", vtkInstantiatorvtkExtractVOINew);
  vtkInstantiator::UnRegisterInstantiator("vtkFastSplatter", vtkInstantiatorvtkFastSplatterNew);
  vtkInstantiator::UnRegisterInstantiator("vtkGaussianSplatter", vtkInstantiatorvtkGaussianSplatterNew);
  vtkInstantiator::UnRegisterInstantiator("vtkImageAccumulate", vtkInstantiatorvtkImageAccumulateNew);
  vtkInstantiator::UnRegisterInstantiator("vtkImageAnisotropicDiffusion2D", vtkInstantiatorvtkImageAnisotropicDiffusion2DNew);
  vtkInstantiator::UnRegisterInstantiator("vtkImageAnisotropicDiffusion3D", vtkInstantiatorvtkImageAnisotropicDiffusion3DNew);
  vtkInstantiator::UnRegisterInstantiator("vtkImageAppend", vtkInstantiatorvtkImageAppendNew);
  vtkInstantiator::UnRegisterInstantiator("vtkImageAppendComponents", vtkInstantiatorvtkImageAppendComponentsNew);
  vtkInstantiator::UnRegisterInstantiator("vtkImageBlend", vtkInstantiatorvtkImageBlendNew);
  vtkInstantiator::UnRegisterInstantiator("vtkImageButterworthHighPass", vtkInstantiatorvtkImageButterworthHighPassNew);
  vtkInstantiator::UnRegisterInstantiator("vtkImageButterworthLowPass", vtkInstantiatorvtkImageButterworthLowPassNew);
  vtkInstantiator::UnRegisterInstantiator("vtkImageCacheFilter", vtkInstantiatorvtkImageCacheFilterNew);
  vtkInstantiator::UnRegisterInstantiator("vtkImageCanvasSource2D", vtkInstantiatorvtkImageCanvasSource2DNew);
  vtkInstantiator::UnRegisterInstantiator("vtkImageCast", vtkInstantiatorvtkImageCastNew);
  vtkInstantiator::UnRegisterInstantiator("vtkImageChangeInformation", vtkInstantiatorvtkImageChangeInformationNew);
  vtkInstantiator::UnRegisterInstantiator("vtkImageCheckerboard", vtkInstantiatorvtkImageCheckerboardNew);
  vtkInstantiator::UnRegisterInstantiator("vtkImageCityBlockDistance", vtkInstantiatorvtkImageCityBlockDistanceNew);
  vtkInstantiator::UnRegisterInstantiator("vtkImageClip", vtkInstantiatorvtkImageClipNew);
  vtkInstantiator::UnRegisterInstantiator("vtkImageConnector", vtkInstantiatorvtkImageConnectorNew);
  vtkInstantiator::UnRegisterInstantiator("vtkImageConstantPad", vtkInstantiatorvtkImageConstantPadNew);
  vtkInstantiator::UnRegisterInstantiator("vtkImageContinuousDilate3D", vtkInstantiatorvtkImageContinuousDilate3DNew);
  vtkInstantiator::UnRegisterInstantiator("vtkImageContinuousErode3D", vtkInstantiatorvtkImageContinuousErode3DNew);
  vtkInstantiator::UnRegisterInstantiator("vtkImageConvolve", vtkInstantiatorvtkImageConvolveNew);
  vtkInstantiator::UnRegisterInstantiator("vtkImageCorrelation", vtkInstantiatorvtkImageCorrelationNew);
  vtkInstantiator::UnRegisterInstantiator("vtkImageCursor3D", vtkInstantiatorvtkImageCursor3DNew);
  vtkInstantiator::UnRegisterInstantiator("vtkImageDataStreamer", vtkInstantiatorvtkImageDataStreamerNew);
  vtkInstantiator::UnRegisterInstantiator("vtkImageDifference", vtkInstantiatorvtkImageDifferenceNew);
  vtkInstantiator::UnRegisterInstantiator("vtkImageDilateErode3D", vtkInstantiatorvtkImageDilateErode3DNew);
  vtkInstantiator::UnRegisterInstantiator("vtkImageDivergence", vtkInstantiatorvtkImageDivergenceNew);
  vtkInstantiator::UnRegisterInstantiator("vtkImageDotProduct", vtkInstantiatorvtkImageDotProductNew);
  vtkInstantiator::UnRegisterInstantiator("vtkImageEllipsoidSource", vtkInstantiatorvtkImageEllipsoidSourceNew);
  vtkInstantiator::UnRegisterInstantiator("vtkImageEuclideanDistance", vtkInstantiatorvtkImageEuclideanDistanceNew);
  vtkInstantiator::UnRegisterInstantiator("vtkImageEuclideanToPolar", vtkInstantiatorvtkImageEuclideanToPolarNew);
  vtkInstantiator::UnRegisterInstantiator("vtkImageExport", vtkInstantiatorvtkImageExportNew);
  vtkInstantiator::UnRegisterInstantiator("vtkImageExtractComponents", vtkInstantiatorvtkImageExtractComponentsNew);
  vtkInstantiator::UnRegisterInstantiator("vtkImageFFT", vtkInstantiatorvtkImageFFTNew);
  vtkInstantiator::UnRegisterInstantiator("vtkImageFlip", vtkInstantiatorvtkImageFlipNew);
  vtkInstantiator::UnRegisterInstantiator("vtkImageFourierCenter", vtkInstantiatorvtkImageFourierCenterNew);
  vtkInstantiator::UnRegisterInstantiator("vtkImageGaussianSmooth", vtkInstantiatorvtkImageGaussianSmoothNew);
  vtkInstantiator::UnRegisterInstantiator("vtkImageGaussianSource", vtkInstantiatorvtkImageGaussianSourceNew);
  vtkInstantiator::UnRegisterInstantiator("vtkImageGradient", vtkInstantiatorvtkImageGradientNew);
  vtkInstantiator::UnRegisterInstantiator("vtkImageGradientMagnitude", vtkInstantiatorvtkImageGradientMagnitudeNew);
  vtkInstantiator::UnRegisterInstantiator("vtkImageGridSource", vtkInstantiatorvtkImageGridSourceNew);
  vtkInstantiator::UnRegisterInstantiator("vtkImageHSIToRGB", vtkInstantiatorvtkImageHSIToRGBNew);
  vtkInstantiator::UnRegisterInstantiator("vtkImageHSVToRGB", vtkInstantiatorvtkImageHSVToRGBNew);
  vtkInstantiator::UnRegisterInstantiator("vtkImageHybridMedian2D", vtkInstantiatorvtkImageHybridMedian2DNew);
  vtkInstantiator::UnRegisterInstantiator("vtkImageIdealHighPass", vtkInstantiatorvtkImageIdealHighPassNew);
  vtkInstantiator::UnRegisterInstantiator("vtkImageIdealLowPass", vtkInstantiatorvtkImageIdealLowPassNew);
  vtkInstantiator::UnRegisterInstantiator("vtkImageImport", vtkInstantiatorvtkImageImportNew);
  vtkInstantiator::UnRegisterInstantiator("vtkImageImportExecutive", vtkInstantiatorvtkImageImportExecutiveNew);
  vtkInstantiator::UnRegisterInstantiator("vtkImageIslandRemoval2D", vtkInstantiatorvtkImageIslandRemoval2DNew);
  vtkInstantiator::UnRegisterInstantiator("vtkImageLaplacian", vtkInstantiatorvtkImageLaplacianNew);
  vtkInstantiator::UnRegisterInstantiator("vtkImageLogarithmicScale", vtkInstantiatorvtkImageLogarithmicScaleNew);
  vtkInstantiator::UnRegisterInstantiator("vtkImageLogic", vtkInstantiatorvtkImageLogicNew);
  vtkInstantiator::UnRegisterInstantiator("vtkImageLuminance", vtkInstantiatorvtkImageLuminanceNew);
  vtkInstantiator::UnRegisterInstantiator("vtkImageMagnify", vtkInstantiatorvtkImageMagnifyNew);
  vtkInstantiator::UnRegisterInstantiator("vtkImageMagnitude", vtkInstantiatorvtkImageMagnitudeNew);
  vtkInstantiator::UnRegisterInstantiator("vtkImageMandelbrotSource", vtkInstantiatorvtkImageMandelbrotSourceNew);
  vtkInstantiator::UnRegisterInstantiator("vtkImageMapToColors", vtkInstantiatorvtkImageMapToColorsNew);
  vtkInstantiator::UnRegisterInstantiator("vtkImageMapToRGBA", vtkInstantiatorvtkImageMapToRGBANew);
  vtkInstantiator::UnRegisterInstantiator("vtkImageMapToWindowLevelColors", vtkInstantiatorvtkImageMapToWindowLevelColorsNew);
  vtkInstantiator::UnRegisterInstantiator("vtkImageMask", vtkInstantiatorvtkImageMaskNew);
  vtkInstantiator::UnRegisterInstantiator("vtkImageMaskBits", vtkInstantiatorvtkImageMaskBitsNew);
  vtkInstantiator::UnRegisterInstantiator("vtkImageMathematics", vtkInstantiatorvtkImageMathematicsNew);
  vtkInstantiator::UnRegisterInstantiator("vtkImageMedian3D", vtkInstantiatorvtkImageMedian3DNew);
  vtkInstantiator::UnRegisterInstantiator("vtkImageMirrorPad", vtkInstantiatorvtkImageMirrorPadNew);
  vtkInstantiator::UnRegisterInstantiator("vtkImageNoiseSource", vtkInstantiatorvtkImageNoiseSourceNew);
  vtkInstantiator::UnRegisterInstantiator("vtkImageNonMaximumSuppression", vtkInstantiatorvtkImageNonMaximumSuppressionNew);
  vtkInstantiator::UnRegisterInstantiator("vtkImageNormalize", vtkInstantiatorvtkImageNormalizeNew);
  vtkInstantiator::UnRegisterInstantiator("vtkImageOpenClose3D", vtkInstantiatorvtkImageOpenClose3DNew);
  vtkInstantiator::UnRegisterInstantiator("vtkImagePermute", vtkInstantiatorvtkImagePermuteNew);
  vtkInstantiator::UnRegisterInstantiator("vtkImageSlab", vtkInstantiatorvtkImageSlabNew);
  vtkInstantiator::UnRegisterInstantiator("vtkImageQuantizeRGBToIndex", vtkInstantiatorvtkImageQuantizeRGBToIndexNew);
  vtkInstantiator::UnRegisterInstantiator("vtkImageRFFT", vtkInstantiatorvtkImageRFFTNew);
  vtkInstantiator::UnRegisterInstantiator("vtkImageRGBToHSI", vtkInstantiatorvtkImageRGBToHSINew);
  vtkInstantiator::UnRegisterInstantiator("vtkImageRGBToHSV", vtkInstantiatorvtkImageRGBToHSVNew);
  vtkInstantiator::UnRegisterInstantiator("vtkImageRange3D", vtkInstantiatorvtkImageRange3DNew);
  vtkInstantiator::UnRegisterInstantiator("vtkImageRectilinearWipe", vtkInstantiatorvtkImageRectilinearWipeNew);
  vtkInstantiator::UnRegisterInstantiator("vtkImageResample", vtkInstantiatorvtkImageResampleNew);
  vtkInstantiator::UnRegisterInstantiator("vtkImageReslice", vtkInstantiatorvtkImageResliceNew);
  vtkInstantiator::UnRegisterInstantiator("vtkImageSeedConnectivity", vtkInstantiatorvtkImageSeedConnectivityNew);
  vtkInstantiator::UnRegisterInstantiator("vtkImageSeparableConvolution", vtkInstantiatorvtkImageSeparableConvolutionNew);
  vtkInstantiator::UnRegisterInstantiator("vtkImageShiftScale", vtkInstantiatorvtkImageShiftScaleNew);
  vtkInstantiator::UnRegisterInstantiator("vtkImageShrink3D", vtkInstantiatorvtkImageShrink3DNew);
  vtkInstantiator::UnRegisterInstantiator("vtkImageSinusoidSource", vtkInstantiatorvtkImageSinusoidSourceNew);
  vtkInstantiator::UnRegisterInstantiator("vtkImageSkeleton2D", vtkInstantiatorvtkImageSkeleton2DNew);
  vtkInstantiator::UnRegisterInstantiator("vtkImageSobel2D", vtkInstantiatorvtkImageSobel2DNew);
  vtkInstantiator::UnRegisterInstantiator("vtkImageSobel3D", vtkInstantiatorvtkImageSobel3DNew);
  vtkInstantiator::UnRegisterInstantiator("vtkImageStencil", vtkInstantiatorvtkImageStencilNew);
  vtkInstantiator::UnRegisterInstantiator("vtkImageStencilToImage", vtkInstantiatorvtkImageStencilToImageNew);
  vtkInstantiator::UnRegisterInstantiator("vtkImageStencilAlgorithm", vtkInstantiatorvtkImageStencilAlgorithmNew);
  vtkInstantiator::UnRegisterInstantiator("vtkImageStencilData", vtkInstantiatorvtkImageStencilDataNew);
  vtkInstantiator::UnRegisterInstantiator("vtkImageStencilSource", vtkInstantiatorvtkImageStencilSourceNew);
  vtkInstantiator::UnRegisterInstantiator("vtkImageThreshold", vtkInstantiatorvtkImageThresholdNew);
  vtkInstantiator::UnRegisterInstantiator("vtkImageToImageStencil", vtkInstantiatorvtkImageToImageStencilNew);
  vtkInstantiator::UnRegisterInstantiator("vtkImageTranslateExtent", vtkInstantiatorvtkImageTranslateExtentNew);
  vtkInstantiator::UnRegisterInstantiator("vtkImageVariance3D", vtkInstantiatorvtkImageVariance3DNew);
  vtkInstantiator::UnRegisterInstantiator("vtkImageWrapPad", vtkInstantiatorvtkImageWrapPadNew);
  vtkInstantiator::UnRegisterInstantiator("vtkImageWeightedSum", vtkInstantiatorvtkImageWeightedSumNew);
  vtkInstantiator::UnRegisterInstantiator("vtkImplicitFunctionToImageStencil", vtkInstantiatorvtkImplicitFunctionToImageStencilNew);
  vtkInstantiator::UnRegisterInstantiator("vtkLassoStencilSource", vtkInstantiatorvtkLassoStencilSourceNew);
  vtkInstantiator::UnRegisterInstantiator("vtkPointLoad", vtkInstantiatorvtkPointLoadNew);
  vtkInstantiator::UnRegisterInstantiator("vtkROIStencilSource", vtkInstantiatorvtkROIStencilSourceNew);
  vtkInstantiator::UnRegisterInstantiator("vtkRTAnalyticSource", vtkInstantiatorvtkRTAnalyticSourceNew);
  vtkInstantiator::UnRegisterInstantiator("vtkSampleFunction", vtkInstantiatorvtkSampleFunctionNew);
  vtkInstantiator::UnRegisterInstantiator("vtkShepardMethod", vtkInstantiatorvtkShepardMethodNew);
  vtkInstantiator::UnRegisterInstantiator("vtkSimpleImageFilterExample", vtkInstantiatorvtkSimpleImageFilterExampleNew);
  vtkInstantiator::UnRegisterInstantiator("vtkSurfaceReconstructionFilter", vtkInstantiatorvtkSurfaceReconstructionFilterNew);
  vtkInstantiator::UnRegisterInstantiator("vtkTriangularTexture", vtkInstantiatorvtkTriangularTextureNew);
  vtkInstantiator::UnRegisterInstantiator("vtkVoxelModeller", vtkInstantiatorvtkVoxelModellerNew);

  
}

vtkImagingInstantiator::vtkImagingInstantiator()
{
  if(++vtkImagingInstantiator::Count == 1)
    { 
    vtkImagingInstantiator::ClassInitialize(); 
    }
}

vtkImagingInstantiator::~vtkImagingInstantiator()
{
  if(--vtkImagingInstantiator::Count == 0)
    { 
    vtkImagingInstantiator::ClassFinalize(); 
    }
}

// Number of translation units that include this class's header.
// Purposely not initialized.  Default is static initialization to 0.
unsigned int vtkImagingInstantiator::Count;
