#include "vtkCommonInstantiator.h"
  
extern vtkObject* vtkInstantiatorvtkAmoebaMinimizerNew();
extern vtkObject* vtkInstantiatorvtkAnimationCueNew();
extern vtkObject* vtkInstantiatorvtkAnimationSceneNew();
extern vtkObject* vtkInstantiatorvtkAssemblyNodeNew();
extern vtkObject* vtkInstantiatorvtkAssemblyPathNew();
extern vtkObject* vtkInstantiatorvtkAssemblyPathsNew();
extern vtkObject* vtkInstantiatorvtkBitArrayNew();
extern vtkObject* vtkInstantiatorvtkBitArrayIteratorNew();
extern vtkObject* vtkInstantiatorvtkBoxNew();
extern vtkObject* vtkInstantiatorvtkBoxMuellerRandomSequenceNew();
extern vtkObject* vtkInstantiatorvtkByteSwapNew();
extern vtkObject* vtkInstantiatorvtkCharArrayNew();
extern vtkObject* vtkInstantiatorvtkClientSocketNew();
extern vtkObject* vtkInstantiatorvtkCollectionNew();
extern vtkObject* vtkInstantiatorvtkCollectionIteratorNew();
extern vtkObject* vtkInstantiatorvtkConditionVariableNew();
extern vtkObject* vtkInstantiatorvtkContourValuesNew();
extern vtkObject* vtkInstantiatorvtkCriticalSectionNew();
extern vtkObject* vtkInstantiatorvtkCylindricalTransformNew();
extern vtkObject* vtkInstantiatorvtkDataArrayCollectionNew();
extern vtkObject* vtkInstantiatorvtkDataArrayCollectionIteratorNew();
extern vtkObject* vtkInstantiatorvtkDataArraySelectionNew();
extern vtkObject* vtkInstantiatorvtkDebugLeaksNew();
extern vtkObject* vtkInstantiatorvtkDirectoryNew();
extern vtkObject* vtkInstantiatorvtkDoubleArrayNew();
extern vtkObject* vtkInstantiatorvtkDynamicLoaderNew();
extern vtkObject* vtkInstantiatorvtkEdgeTableNew();
extern vtkObject* vtkInstantiatorvtkExtentSplitterNew();
extern vtkObject* vtkInstantiatorvtkExtentTranslatorNew();
extern vtkObject* vtkInstantiatorvtkFastNumericConversionNew();
extern vtkObject* vtkInstantiatorvtkFileOutputWindowNew();
extern vtkObject* vtkInstantiatorvtkFloatArrayNew();
extern vtkObject* vtkInstantiatorvtkFunctionParserNew();
extern vtkObject* vtkInstantiatorvtkGarbageCollectorNew();
extern vtkObject* vtkInstantiatorvtkGeneralTransformNew();
extern vtkObject* vtkInstantiatorvtkHeapNew();
extern vtkObject* vtkInstantiatorvtkIdListNew();
extern vtkObject* vtkInstantiatorvtkIdListCollectionNew();
extern vtkObject* vtkInstantiatorvtkIdTypeArrayNew();
extern vtkObject* vtkInstantiatorvtkIdentityTransformNew();
extern vtkObject* vtkInstantiatorvtkImplicitFunctionCollectionNew();
extern vtkObject* vtkInstantiatorvtkInformationNew();
extern vtkObject* vtkInstantiatorvtkInformationIteratorNew();
extern vtkObject* vtkInstantiatorvtkInformationVectorNew();
extern vtkObject* vtkInstantiatorvtkInstantiatorNew();
extern vtkObject* vtkInstantiatorvtkIntArrayNew();
extern vtkObject* vtkInstantiatorvtkLogLookupTableNew();
extern vtkObject* vtkInstantiatorvtkLongArrayNew();
extern vtkObject* vtkInstantiatorvtkLookupTableNew();
extern vtkObject* vtkInstantiatorvtkLookupTableWithEnablingNew();
extern vtkObject* vtkInstantiatorvtkMathNew();
extern vtkObject* vtkInstantiatorvtkMatrix3x3New();
extern vtkObject* vtkInstantiatorvtkMatrix4x4New();
extern vtkObject* vtkInstantiatorvtkMatrixToHomogeneousTransformNew();
extern vtkObject* vtkInstantiatorvtkMatrixToLinearTransformNew();
extern vtkObject* vtkInstantiatorvtkMinimalStandardRandomSequenceNew();
extern vtkObject* vtkInstantiatorvtkMultiThreaderNew();
extern vtkObject* vtkInstantiatorvtkMutexLockNew();
extern vtkObject* vtkInstantiatorvtkObjectNew();
extern vtkObject* vtkInstantiatorvtkObjectFactoryCollectionNew();
extern vtkObject* vtkInstantiatorvtkOnePieceExtentTranslatorNew();
extern vtkObject* vtkInstantiatorvtkOutputWindowNew();
extern vtkObject* vtkInstantiatorvtkParametricBoyNew();
extern vtkObject* vtkInstantiatorvtkParametricConicSpiralNew();
extern vtkObject* vtkInstantiatorvtkParametricCrossCapNew();
extern vtkObject* vtkInstantiatorvtkParametricDiniNew();
extern vtkObject* vtkInstantiatorvtkParametricEllipsoidNew();
extern vtkObject* vtkInstantiatorvtkParametricEnneperNew();
extern vtkObject* vtkInstantiatorvtkParametricFigure8KleinNew();
extern vtkObject* vtkInstantiatorvtkParametricKleinNew();
extern vtkObject* vtkInstantiatorvtkParametricMobiusNew();
extern vtkObject* vtkInstantiatorvtkParametricRandomHillsNew();
extern vtkObject* vtkInstantiatorvtkParametricRomanNew();
extern vtkObject* vtkInstantiatorvtkParametricSuperEllipsoidNew();
extern vtkObject* vtkInstantiatorvtkParametricSuperToroidNew();
extern vtkObject* vtkInstantiatorvtkParametricTorusNew();
extern vtkObject* vtkInstantiatorvtkPerspectiveTransformNew();
extern vtkObject* vtkInstantiatorvtkPlaneNew();
extern vtkObject* vtkInstantiatorvtkPlaneCollectionNew();
extern vtkObject* vtkInstantiatorvtkPlanesNew();
extern vtkObject* vtkInstantiatorvtkPointsNew();
extern vtkObject* vtkInstantiatorvtkPoints2DNew();
extern vtkObject* vtkInstantiatorvtkPolynomialSolversUnivariateNew();
extern vtkObject* vtkInstantiatorvtkPriorityQueueNew();
extern vtkObject* vtkInstantiatorvtkPropCollectionNew();
extern vtkObject* vtkInstantiatorvtkProperty2DNew();
extern vtkObject* vtkInstantiatorvtkQuadratureSchemeDefinitionNew();
extern vtkObject* vtkInstantiatorvtkQuadricNew();
extern vtkObject* vtkInstantiatorvtkReferenceCountNew();
extern vtkObject* vtkInstantiatorvtkRungeKutta2New();
extern vtkObject* vtkInstantiatorvtkRungeKutta4New();
extern vtkObject* vtkInstantiatorvtkRungeKutta45New();
extern vtkObject* vtkInstantiatorvtkServerSocketNew();
extern vtkObject* vtkInstantiatorvtkShortArrayNew();
extern vtkObject* vtkInstantiatorvtkSignedCharArrayNew();
extern vtkObject* vtkInstantiatorvtkSocketCollectionNew();
extern vtkObject* vtkInstantiatorvtkSortDataArrayNew();
extern vtkObject* vtkInstantiatorvtkSphericalTransformNew();
extern vtkObject* vtkInstantiatorvtkStringArrayNew();
extern vtkObject* vtkInstantiatorvtkStructuredExtentNew();
extern vtkObject* vtkInstantiatorvtkStructuredVisibilityConstraintNew();
extern vtkObject* vtkInstantiatorvtkTableExtentTranslatorNew();
extern vtkObject* vtkInstantiatorvtkTensorNew();
extern vtkObject* vtkInstantiatorvtkThreadMessagerNew();
extern vtkObject* vtkInstantiatorvtkTimePointUtilityNew();
extern vtkObject* vtkInstantiatorvtkTimerLogNew();
extern vtkObject* vtkInstantiatorvtkTransform2DNew();
extern vtkObject* vtkInstantiatorvtkTransformNew();
extern vtkObject* vtkInstantiatorvtkTransformCollectionNew();
extern vtkObject* vtkInstantiatorvtkUnicodeStringArrayNew();
extern vtkObject* vtkInstantiatorvtkUnsignedCharArrayNew();
extern vtkObject* vtkInstantiatorvtkUnsignedIntArrayNew();
extern vtkObject* vtkInstantiatorvtkUnsignedLongArrayNew();
extern vtkObject* vtkInstantiatorvtkUnsignedShortArrayNew();
extern vtkObject* vtkInstantiatorvtkVersionNew();
extern vtkObject* vtkInstantiatorvtkVoidArrayNew();
extern vtkObject* vtkInstantiatorvtkWindowLevelLookupTableNew();
extern vtkObject* vtkInstantiatorvtkXMLDataElementNew();
extern vtkObject* vtkInstantiatorvtkXMLFileOutputWindowNew();
extern vtkObject* vtkInstantiatorvtkLongLongArrayNew();
extern vtkObject* vtkInstantiatorvtkUnsignedLongLongArrayNew();
extern vtkObject* vtkInstantiatorvtkTypeInt8ArrayNew();
extern vtkObject* vtkInstantiatorvtkTypeInt16ArrayNew();
extern vtkObject* vtkInstantiatorvtkTypeInt32ArrayNew();
extern vtkObject* vtkInstantiatorvtkTypeInt64ArrayNew();
extern vtkObject* vtkInstantiatorvtkTypeUInt8ArrayNew();
extern vtkObject* vtkInstantiatorvtkTypeUInt16ArrayNew();
extern vtkObject* vtkInstantiatorvtkTypeUInt32ArrayNew();
extern vtkObject* vtkInstantiatorvtkTypeUInt64ArrayNew();
extern vtkObject* vtkInstantiatorvtkTypeFloat32ArrayNew();
extern vtkObject* vtkInstantiatorvtkTypeFloat64ArrayNew();


  
void vtkCommonInstantiator::ClassInitialize()
{
  
  vtkInstantiator::RegisterInstantiator("vtkAmoebaMinimizer", vtkInstantiatorvtkAmoebaMinimizerNew);
  vtkInstantiator::RegisterInstantiator("vtkAnimationCue", vtkInstantiatorvtkAnimationCueNew);
  vtkInstantiator::RegisterInstantiator("vtkAnimationScene", vtkInstantiatorvtkAnimationSceneNew);
  vtkInstantiator::RegisterInstantiator("vtkAssemblyNode", vtkInstantiatorvtkAssemblyNodeNew);
  vtkInstantiator::RegisterInstantiator("vtkAssemblyPath", vtkInstantiatorvtkAssemblyPathNew);
  vtkInstantiator::RegisterInstantiator("vtkAssemblyPaths", vtkInstantiatorvtkAssemblyPathsNew);
  vtkInstantiator::RegisterInstantiator("vtkBitArray", vtkInstantiatorvtkBitArrayNew);
  vtkInstantiator::RegisterInstantiator("vtkBitArrayIterator", vtkInstantiatorvtkBitArrayIteratorNew);
  vtkInstantiator::RegisterInstantiator("vtkBox", vtkInstantiatorvtkBoxNew);
  vtkInstantiator::RegisterInstantiator("vtkBoxMuellerRandomSequence", vtkInstantiatorvtkBoxMuellerRandomSequenceNew);
  vtkInstantiator::RegisterInstantiator("vtkByteSwap", vtkInstantiatorvtkByteSwapNew);
  vtkInstantiator::RegisterInstantiator("vtkCharArray", vtkInstantiatorvtkCharArrayNew);
  vtkInstantiator::RegisterInstantiator("vtkClientSocket", vtkInstantiatorvtkClientSocketNew);
  vtkInstantiator::RegisterInstantiator("vtkCollection", vtkInstantiatorvtkCollectionNew);
  vtkInstantiator::RegisterInstantiator("vtkCollectionIterator", vtkInstantiatorvtkCollectionIteratorNew);
  vtkInstantiator::RegisterInstantiator("vtkConditionVariable", vtkInstantiatorvtkConditionVariableNew);
  vtkInstantiator::RegisterInstantiator("vtkContourValues", vtkInstantiatorvtkContourValuesNew);
  vtkInstantiator::RegisterInstantiator("vtkCriticalSection", vtkInstantiatorvtkCriticalSectionNew);
  vtkInstantiator::RegisterInstantiator("vtkCylindricalTransform", vtkInstantiatorvtkCylindricalTransformNew);
  vtkInstantiator::RegisterInstantiator("vtkDataArrayCollection", vtkInstantiatorvtkDataArrayCollectionNew);
  vtkInstantiator::RegisterInstantiator("vtkDataArrayCollectionIterator", vtkInstantiatorvtkDataArrayCollectionIteratorNew);
  vtkInstantiator::RegisterInstantiator("vtkDataArraySelection", vtkInstantiatorvtkDataArraySelectionNew);
  vtkInstantiator::RegisterInstantiator("vtkDebugLeaks", vtkInstantiatorvtkDebugLeaksNew);
  vtkInstantiator::RegisterInstantiator("vtkDirectory", vtkInstantiatorvtkDirectoryNew);
  vtkInstantiator::RegisterInstantiator("vtkDoubleArray", vtkInstantiatorvtkDoubleArrayNew);
  vtkInstantiator::RegisterInstantiator("vtkDynamicLoader", vtkInstantiatorvtkDynamicLoaderNew);
  vtkInstantiator::RegisterInstantiator("vtkEdgeTable", vtkInstantiatorvtkEdgeTableNew);
  vtkInstantiator::RegisterInstantiator("vtkExtentSplitter", vtkInstantiatorvtkExtentSplitterNew);
  vtkInstantiator::RegisterInstantiator("vtkExtentTranslator", vtkInstantiatorvtkExtentTranslatorNew);
  vtkInstantiator::RegisterInstantiator("vtkFastNumericConversion", vtkInstantiatorvtkFastNumericConversionNew);
  vtkInstantiator::RegisterInstantiator("vtkFileOutputWindow", vtkInstantiatorvtkFileOutputWindowNew);
  vtkInstantiator::RegisterInstantiator("vtkFloatArray", vtkInstantiatorvtkFloatArrayNew);
  vtkInstantiator::RegisterInstantiator("vtkFunctionParser", vtkInstantiatorvtkFunctionParserNew);
  vtkInstantiator::RegisterInstantiator("vtkGarbageCollector", vtkInstantiatorvtkGarbageCollectorNew);
  vtkInstantiator::RegisterInstantiator("vtkGeneralTransform", vtkInstantiatorvtkGeneralTransformNew);
  vtkInstantiator::RegisterInstantiator("vtkHeap", vtkInstantiatorvtkHeapNew);
  vtkInstantiator::RegisterInstantiator("vtkIdList", vtkInstantiatorvtkIdListNew);
  vtkInstantiator::RegisterInstantiator("vtkIdListCollection", vtkInstantiatorvtkIdListCollectionNew);
  vtkInstantiator::RegisterInstantiator("vtkIdTypeArray", vtkInstantiatorvtkIdTypeArrayNew);
  vtkInstantiator::RegisterInstantiator("vtkIdentityTransform", vtkInstantiatorvtkIdentityTransformNew);
  vtkInstantiator::RegisterInstantiator("vtkImplicitFunctionCollection", vtkInstantiatorvtkImplicitFunctionCollectionNew);
  vtkInstantiator::RegisterInstantiator("vtkInformation", vtkInstantiatorvtkInformationNew);
  vtkInstantiator::RegisterInstantiator("vtkInformationIterator", vtkInstantiatorvtkInformationIteratorNew);
  vtkInstantiator::RegisterInstantiator("vtkInformationVector", vtkInstantiatorvtkInformationVectorNew);
  vtkInstantiator::RegisterInstantiator("vtkInstantiator", vtkInstantiatorvtkInstantiatorNew);
  vtkInstantiator::RegisterInstantiator("vtkIntArray", vtkInstantiatorvtkIntArrayNew);
  vtkInstantiator::RegisterInstantiator("vtkLogLookupTable", vtkInstantiatorvtkLogLookupTableNew);
  vtkInstantiator::RegisterInstantiator("vtkLongArray", vtkInstantiatorvtkLongArrayNew);
  vtkInstantiator::RegisterInstantiator("vtkLookupTable", vtkInstantiatorvtkLookupTableNew);
  vtkInstantiator::RegisterInstantiator("vtkLookupTableWithEnabling", vtkInstantiatorvtkLookupTableWithEnablingNew);
  vtkInstantiator::RegisterInstantiator("vtkMath", vtkInstantiatorvtkMathNew);
  vtkInstantiator::RegisterInstantiator("vtkMatrix3x3", vtkInstantiatorvtkMatrix3x3New);
  vtkInstantiator::RegisterInstantiator("vtkMatrix4x4", vtkInstantiatorvtkMatrix4x4New);
  vtkInstantiator::RegisterInstantiator("vtkMatrixToHomogeneousTransform", vtkInstantiatorvtkMatrixToHomogeneousTransformNew);
  vtkInstantiator::RegisterInstantiator("vtkMatrixToLinearTransform", vtkInstantiatorvtkMatrixToLinearTransformNew);
  vtkInstantiator::RegisterInstantiator("vtkMinimalStandardRandomSequence", vtkInstantiatorvtkMinimalStandardRandomSequenceNew);
  vtkInstantiator::RegisterInstantiator("vtkMultiThreader", vtkInstantiatorvtkMultiThreaderNew);
  vtkInstantiator::RegisterInstantiator("vtkMutexLock", vtkInstantiatorvtkMutexLockNew);
  vtkInstantiator::RegisterInstantiator("vtkObject", vtkInstantiatorvtkObjectNew);
  vtkInstantiator::RegisterInstantiator("vtkObjectFactoryCollection", vtkInstantiatorvtkObjectFactoryCollectionNew);
  vtkInstantiator::RegisterInstantiator("vtkOnePieceExtentTranslator", vtkInstantiatorvtkOnePieceExtentTranslatorNew);
  vtkInstantiator::RegisterInstantiator("vtkOutputWindow", vtkInstantiatorvtkOutputWindowNew);
  vtkInstantiator::RegisterInstantiator("vtkParametricBoy", vtkInstantiatorvtkParametricBoyNew);
  vtkInstantiator::RegisterInstantiator("vtkParametricConicSpiral", vtkInstantiatorvtkParametricConicSpiralNew);
  vtkInstantiator::RegisterInstantiator("vtkParametricCrossCap", vtkInstantiatorvtkParametricCrossCapNew);
  vtkInstantiator::RegisterInstantiator("vtkParametricDini", vtkInstantiatorvtkParametricDiniNew);
  vtkInstantiator::RegisterInstantiator("vtkParametricEllipsoid", vtkInstantiatorvtkParametricEllipsoidNew);
  vtkInstantiator::RegisterInstantiator("vtkParametricEnneper", vtkInstantiatorvtkParametricEnneperNew);
  vtkInstantiator::RegisterInstantiator("vtkParametricFigure8Klein", vtkInstantiatorvtkParametricFigure8KleinNew);
  vtkInstantiator::RegisterInstantiator("vtkParametricKlein", vtkInstantiatorvtkParametricKleinNew);
  vtkInstantiator::RegisterInstantiator("vtkParametricMobius", vtkInstantiatorvtkParametricMobiusNew);
  vtkInstantiator::RegisterInstantiator("vtkParametricRandomHills", vtkInstantiatorvtkParametricRandomHillsNew);
  vtkInstantiator::RegisterInstantiator("vtkParametricRoman", vtkInstantiatorvtkParametricRomanNew);
  vtkInstantiator::RegisterInstantiator("vtkParametricSuperEllipsoid", vtkInstantiatorvtkParametricSuperEllipsoidNew);
  vtkInstantiator::RegisterInstantiator("vtkParametricSuperToroid", vtkInstantiatorvtkParametricSuperToroidNew);
  vtkInstantiator::RegisterInstantiator("vtkParametricTorus", vtkInstantiatorvtkParametricTorusNew);
  vtkInstantiator::RegisterInstantiator("vtkPerspectiveTransform", vtkInstantiatorvtkPerspectiveTransformNew);
  vtkInstantiator::RegisterInstantiator("vtkPlane", vtkInstantiatorvtkPlaneNew);
  vtkInstantiator::RegisterInstantiator("vtkPlaneCollection", vtkInstantiatorvtkPlaneCollectionNew);
  vtkInstantiator::RegisterInstantiator("vtkPlanes", vtkInstantiatorvtkPlanesNew);
  vtkInstantiator::RegisterInstantiator("vtkPoints", vtkInstantiatorvtkPointsNew);
  vtkInstantiator::RegisterInstantiator("vtkPoints2D", vtkInstantiatorvtkPoints2DNew);
  vtkInstantiator::RegisterInstantiator("vtkPolynomialSolversUnivariate", vtkInstantiatorvtkPolynomialSolversUnivariateNew);
  vtkInstantiator::RegisterInstantiator("vtkPriorityQueue", vtkInstantiatorvtkPriorityQueueNew);
  vtkInstantiator::RegisterInstantiator("vtkPropCollection", vtkInstantiatorvtkPropCollectionNew);
  vtkInstantiator::RegisterInstantiator("vtkProperty2D", vtkInstantiatorvtkProperty2DNew);
  vtkInstantiator::RegisterInstantiator("vtkQuadratureSchemeDefinition", vtkInstantiatorvtkQuadratureSchemeDefinitionNew);
  vtkInstantiator::RegisterInstantiator("vtkQuadric", vtkInstantiatorvtkQuadricNew);
  vtkInstantiator::RegisterInstantiator("vtkReferenceCount", vtkInstantiatorvtkReferenceCountNew);
  vtkInstantiator::RegisterInstantiator("vtkRungeKutta2", vtkInstantiatorvtkRungeKutta2New);
  vtkInstantiator::RegisterInstantiator("vtkRungeKutta4", vtkInstantiatorvtkRungeKutta4New);
  vtkInstantiator::RegisterInstantiator("vtkRungeKutta45", vtkInstantiatorvtkRungeKutta45New);
  vtkInstantiator::RegisterInstantiator("vtkServerSocket", vtkInstantiatorvtkServerSocketNew);
  vtkInstantiator::RegisterInstantiator("vtkShortArray", vtkInstantiatorvtkShortArrayNew);
  vtkInstantiator::RegisterInstantiator("vtkSignedCharArray", vtkInstantiatorvtkSignedCharArrayNew);
  vtkInstantiator::RegisterInstantiator("vtkSocketCollection", vtkInstantiatorvtkSocketCollectionNew);
  vtkInstantiator::RegisterInstantiator("vtkSortDataArray", vtkInstantiatorvtkSortDataArrayNew);
  vtkInstantiator::RegisterInstantiator("vtkSphericalTransform", vtkInstantiatorvtkSphericalTransformNew);
  vtkInstantiator::RegisterInstantiator("vtkStringArray", vtkInstantiatorvtkStringArrayNew);
  vtkInstantiator::RegisterInstantiator("vtkStructuredExtent", vtkInstantiatorvtkStructuredExtentNew);
  vtkInstantiator::RegisterInstantiator("vtkStructuredVisibilityConstraint", vtkInstantiatorvtkStructuredVisibilityConstraintNew);
  vtkInstantiator::RegisterInstantiator("vtkTableExtentTranslator", vtkInstantiatorvtkTableExtentTranslatorNew);
  vtkInstantiator::RegisterInstantiator("vtkTensor", vtkInstantiatorvtkTensorNew);
  vtkInstantiator::RegisterInstantiator("vtkThreadMessager", vtkInstantiatorvtkThreadMessagerNew);
  vtkInstantiator::RegisterInstantiator("vtkTimePointUtility", vtkInstantiatorvtkTimePointUtilityNew);
  vtkInstantiator::RegisterInstantiator("vtkTimerLog", vtkInstantiatorvtkTimerLogNew);
  vtkInstantiator::RegisterInstantiator("vtkTransform2D", vtkInstantiatorvtkTransform2DNew);
  vtkInstantiator::RegisterInstantiator("vtkTransform", vtkInstantiatorvtkTransformNew);
  vtkInstantiator::RegisterInstantiator("vtkTransformCollection", vtkInstantiatorvtkTransformCollectionNew);
  vtkInstantiator::RegisterInstantiator("vtkUnicodeStringArray", vtkInstantiatorvtkUnicodeStringArrayNew);
  vtkInstantiator::RegisterInstantiator("vtkUnsignedCharArray", vtkInstantiatorvtkUnsignedCharArrayNew);
  vtkInstantiator::RegisterInstantiator("vtkUnsignedIntArray", vtkInstantiatorvtkUnsignedIntArrayNew);
  vtkInstantiator::RegisterInstantiator("vtkUnsignedLongArray", vtkInstantiatorvtkUnsignedLongArrayNew);
  vtkInstantiator::RegisterInstantiator("vtkUnsignedShortArray", vtkInstantiatorvtkUnsignedShortArrayNew);
  vtkInstantiator::RegisterInstantiator("vtkVersion", vtkInstantiatorvtkVersionNew);
  vtkInstantiator::RegisterInstantiator("vtkVoidArray", vtkInstantiatorvtkVoidArrayNew);
  vtkInstantiator::RegisterInstantiator("vtkWindowLevelLookupTable", vtkInstantiatorvtkWindowLevelLookupTableNew);
  vtkInstantiator::RegisterInstantiator("vtkXMLDataElement", vtkInstantiatorvtkXMLDataElementNew);
  vtkInstantiator::RegisterInstantiator("vtkXMLFileOutputWindow", vtkInstantiatorvtkXMLFileOutputWindowNew);
  vtkInstantiator::RegisterInstantiator("vtkLongLongArray", vtkInstantiatorvtkLongLongArrayNew);
  vtkInstantiator::RegisterInstantiator("vtkUnsignedLongLongArray", vtkInstantiatorvtkUnsignedLongLongArrayNew);
  vtkInstantiator::RegisterInstantiator("vtkTypeInt8Array", vtkInstantiatorvtkTypeInt8ArrayNew);
  vtkInstantiator::RegisterInstantiator("vtkTypeInt16Array", vtkInstantiatorvtkTypeInt16ArrayNew);
  vtkInstantiator::RegisterInstantiator("vtkTypeInt32Array", vtkInstantiatorvtkTypeInt32ArrayNew);
  vtkInstantiator::RegisterInstantiator("vtkTypeInt64Array", vtkInstantiatorvtkTypeInt64ArrayNew);
  vtkInstantiator::RegisterInstantiator("vtkTypeUInt8Array", vtkInstantiatorvtkTypeUInt8ArrayNew);
  vtkInstantiator::RegisterInstantiator("vtkTypeUInt16Array", vtkInstantiatorvtkTypeUInt16ArrayNew);
  vtkInstantiator::RegisterInstantiator("vtkTypeUInt32Array", vtkInstantiatorvtkTypeUInt32ArrayNew);
  vtkInstantiator::RegisterInstantiator("vtkTypeUInt64Array", vtkInstantiatorvtkTypeUInt64ArrayNew);
  vtkInstantiator::RegisterInstantiator("vtkTypeFloat32Array", vtkInstantiatorvtkTypeFloat32ArrayNew);
  vtkInstantiator::RegisterInstantiator("vtkTypeFloat64Array", vtkInstantiatorvtkTypeFloat64ArrayNew);

  
}
          
void vtkCommonInstantiator::ClassFinalize()
{ 

  vtkInstantiator::UnRegisterInstantiator("vtkAmoebaMinimizer", vtkInstantiatorvtkAmoebaMinimizerNew);
  vtkInstantiator::UnRegisterInstantiator("vtkAnimationCue", vtkInstantiatorvtkAnimationCueNew);
  vtkInstantiator::UnRegisterInstantiator("vtkAnimationScene", vtkInstantiatorvtkAnimationSceneNew);
  vtkInstantiator::UnRegisterInstantiator("vtkAssemblyNode", vtkInstantiatorvtkAssemblyNodeNew);
  vtkInstantiator::UnRegisterInstantiator("vtkAssemblyPath", vtkInstantiatorvtkAssemblyPathNew);
  vtkInstantiator::UnRegisterInstantiator("vtkAssemblyPaths", vtkInstantiatorvtkAssemblyPathsNew);
  vtkInstantiator::UnRegisterInstantiator("vtkBitArray", vtkInstantiatorvtkBitArrayNew);
  vtkInstantiator::UnRegisterInstantiator("vtkBitArrayIterator", vtkInstantiatorvtkBitArrayIteratorNew);
  vtkInstantiator::UnRegisterInstantiator("vtkBox", vtkInstantiatorvtkBoxNew);
  vtkInstantiator::UnRegisterInstantiator("vtkBoxMuellerRandomSequence", vtkInstantiatorvtkBoxMuellerRandomSequenceNew);
  vtkInstantiator::UnRegisterInstantiator("vtkByteSwap", vtkInstantiatorvtkByteSwapNew);
  vtkInstantiator::UnRegisterInstantiator("vtkCharArray", vtkInstantiatorvtkCharArrayNew);
  vtkInstantiator::UnRegisterInstantiator("vtkClientSocket", vtkInstantiatorvtkClientSocketNew);
  vtkInstantiator::UnRegisterInstantiator("vtkCollection", vtkInstantiatorvtkCollectionNew);
  vtkInstantiator::UnRegisterInstantiator("vtkCollectionIterator", vtkInstantiatorvtkCollectionIteratorNew);
  vtkInstantiator::UnRegisterInstantiator("vtkConditionVariable", vtkInstantiatorvtkConditionVariableNew);
  vtkInstantiator::UnRegisterInstantiator("vtkContourValues", vtkInstantiatorvtkContourValuesNew);
  vtkInstantiator::UnRegisterInstantiator("vtkCriticalSection", vtkInstantiatorvtkCriticalSectionNew);
  vtkInstantiator::UnRegisterInstantiator("vtkCylindricalTransform", vtkInstantiatorvtkCylindricalTransformNew);
  vtkInstantiator::UnRegisterInstantiator("vtkDataArrayCollection", vtkInstantiatorvtkDataArrayCollectionNew);
  vtkInstantiator::UnRegisterInstantiator("vtkDataArrayCollectionIterator", vtkInstantiatorvtkDataArrayCollectionIteratorNew);
  vtkInstantiator::UnRegisterInstantiator("vtkDataArraySelection", vtkInstantiatorvtkDataArraySelectionNew);
  vtkInstantiator::UnRegisterInstantiator("vtkDebugLeaks", vtkInstantiatorvtkDebugLeaksNew);
  vtkInstantiator::UnRegisterInstantiator("vtkDirectory", vtkInstantiatorvtkDirectoryNew);
  vtkInstantiator::UnRegisterInstantiator("vtkDoubleArray", vtkInstantiatorvtkDoubleArrayNew);
  vtkInstantiator::UnRegisterInstantiator("vtkDynamicLoader", vtkInstantiatorvtkDynamicLoaderNew);
  vtkInstantiator::UnRegisterInstantiator("vtkEdgeTable", vtkInstantiatorvtkEdgeTableNew);
  vtkInstantiator::UnRegisterInstantiator("vtkExtentSplitter", vtkInstantiatorvtkExtentSplitterNew);
  vtkInstantiator::UnRegisterInstantiator("vtkExtentTranslator", vtkInstantiatorvtkExtentTranslatorNew);
  vtkInstantiator::UnRegisterInstantiator("vtkFastNumericConversion", vtkInstantiatorvtkFastNumericConversionNew);
  vtkInstantiator::UnRegisterInstantiator("vtkFileOutputWindow", vtkInstantiatorvtkFileOutputWindowNew);
  vtkInstantiator::UnRegisterInstantiator("vtkFloatArray", vtkInstantiatorvtkFloatArrayNew);
  vtkInstantiator::UnRegisterInstantiator("vtkFunctionParser", vtkInstantiatorvtkFunctionParserNew);
  vtkInstantiator::UnRegisterInstantiator("vtkGarbageCollector", vtkInstantiatorvtkGarbageCollectorNew);
  vtkInstantiator::UnRegisterInstantiator("vtkGeneralTransform", vtkInstantiatorvtkGeneralTransformNew);
  vtkInstantiator::UnRegisterInstantiator("vtkHeap", vtkInstantiatorvtkHeapNew);
  vtkInstantiator::UnRegisterInstantiator("vtkIdList", vtkInstantiatorvtkIdListNew);
  vtkInstantiator::UnRegisterInstantiator("vtkIdListCollection", vtkInstantiatorvtkIdListCollectionNew);
  vtkInstantiator::UnRegisterInstantiator("vtkIdTypeArray", vtkInstantiatorvtkIdTypeArrayNew);
  vtkInstantiator::UnRegisterInstantiator("vtkIdentityTransform", vtkInstantiatorvtkIdentityTransformNew);
  vtkInstantiator::UnRegisterInstantiator("vtkImplicitFunctionCollection", vtkInstantiatorvtkImplicitFunctionCollectionNew);
  vtkInstantiator::UnRegisterInstantiator("vtkInformation", vtkInstantiatorvtkInformationNew);
  vtkInstantiator::UnRegisterInstantiator("vtkInformationIterator", vtkInstantiatorvtkInformationIteratorNew);
  vtkInstantiator::UnRegisterInstantiator("vtkInformationVector", vtkInstantiatorvtkInformationVectorNew);
  vtkInstantiator::UnRegisterInstantiator("vtkInstantiator", vtkInstantiatorvtkInstantiatorNew);
  vtkInstantiator::UnRegisterInstantiator("vtkIntArray", vtkInstantiatorvtkIntArrayNew);
  vtkInstantiator::UnRegisterInstantiator("vtkLogLookupTable", vtkInstantiatorvtkLogLookupTableNew);
  vtkInstantiator::UnRegisterInstantiator("vtkLongArray", vtkInstantiatorvtkLongArrayNew);
  vtkInstantiator::UnRegisterInstantiator("vtkLookupTable", vtkInstantiatorvtkLookupTableNew);
  vtkInstantiator::UnRegisterInstantiator("vtkLookupTableWithEnabling", vtkInstantiatorvtkLookupTableWithEnablingNew);
  vtkInstantiator::UnRegisterInstantiator("vtkMath", vtkInstantiatorvtkMathNew);
  vtkInstantiator::UnRegisterInstantiator("vtkMatrix3x3", vtkInstantiatorvtkMatrix3x3New);
  vtkInstantiator::UnRegisterInstantiator("vtkMatrix4x4", vtkInstantiatorvtkMatrix4x4New);
  vtkInstantiator::UnRegisterInstantiator("vtkMatrixToHomogeneousTransform", vtkInstantiatorvtkMatrixToHomogeneousTransformNew);
  vtkInstantiator::UnRegisterInstantiator("vtkMatrixToLinearTransform", vtkInstantiatorvtkMatrixToLinearTransformNew);
  vtkInstantiator::UnRegisterInstantiator("vtkMinimalStandardRandomSequence", vtkInstantiatorvtkMinimalStandardRandomSequenceNew);
  vtkInstantiator::UnRegisterInstantiator("vtkMultiThreader", vtkInstantiatorvtkMultiThreaderNew);
  vtkInstantiator::UnRegisterInstantiator("vtkMutexLock", vtkInstantiatorvtkMutexLockNew);
  vtkInstantiator::UnRegisterInstantiator("vtkObject", vtkInstantiatorvtkObjectNew);
  vtkInstantiator::UnRegisterInstantiator("vtkObjectFactoryCollection", vtkInstantiatorvtkObjectFactoryCollectionNew);
  vtkInstantiator::UnRegisterInstantiator("vtkOnePieceExtentTranslator", vtkInstantiatorvtkOnePieceExtentTranslatorNew);
  vtkInstantiator::UnRegisterInstantiator("vtkOutputWindow", vtkInstantiatorvtkOutputWindowNew);
  vtkInstantiator::UnRegisterInstantiator("vtkParametricBoy", vtkInstantiatorvtkParametricBoyNew);
  vtkInstantiator::UnRegisterInstantiator("vtkParametricConicSpiral", vtkInstantiatorvtkParametricConicSpiralNew);
  vtkInstantiator::UnRegisterInstantiator("vtkParametricCrossCap", vtkInstantiatorvtkParametricCrossCapNew);
  vtkInstantiator::UnRegisterInstantiator("vtkParametricDini", vtkInstantiatorvtkParametricDiniNew);
  vtkInstantiator::UnRegisterInstantiator("vtkParametricEllipsoid", vtkInstantiatorvtkParametricEllipsoidNew);
  vtkInstantiator::UnRegisterInstantiator("vtkParametricEnneper", vtkInstantiatorvtkParametricEnneperNew);
  vtkInstantiator::UnRegisterInstantiator("vtkParametricFigure8Klein", vtkInstantiatorvtkParametricFigure8KleinNew);
  vtkInstantiator::UnRegisterInstantiator("vtkParametricKlein", vtkInstantiatorvtkParametricKleinNew);
  vtkInstantiator::UnRegisterInstantiator("vtkParametricMobius", vtkInstantiatorvtkParametricMobiusNew);
  vtkInstantiator::UnRegisterInstantiator("vtkParametricRandomHills", vtkInstantiatorvtkParametricRandomHillsNew);
  vtkInstantiator::UnRegisterInstantiator("vtkParametricRoman", vtkInstantiatorvtkParametricRomanNew);
  vtkInstantiator::UnRegisterInstantiator("vtkParametricSuperEllipsoid", vtkInstantiatorvtkParametricSuperEllipsoidNew);
  vtkInstantiator::UnRegisterInstantiator("vtkParametricSuperToroid", vtkInstantiatorvtkParametricSuperToroidNew);
  vtkInstantiator::UnRegisterInstantiator("vtkParametricTorus", vtkInstantiatorvtkParametricTorusNew);
  vtkInstantiator::UnRegisterInstantiator("vtkPerspectiveTransform", vtkInstantiatorvtkPerspectiveTransformNew);
  vtkInstantiator::UnRegisterInstantiator("vtkPlane", vtkInstantiatorvtkPlaneNew);
  vtkInstantiator::UnRegisterInstantiator("vtkPlaneCollection", vtkInstantiatorvtkPlaneCollectionNew);
  vtkInstantiator::UnRegisterInstantiator("vtkPlanes", vtkInstantiatorvtkPlanesNew);
  vtkInstantiator::UnRegisterInstantiator("vtkPoints", vtkInstantiatorvtkPointsNew);
  vtkInstantiator::UnRegisterInstantiator("vtkPoints2D", vtkInstantiatorvtkPoints2DNew);
  vtkInstantiator::UnRegisterInstantiator("vtkPolynomialSolversUnivariate", vtkInstantiatorvtkPolynomialSolversUnivariateNew);
  vtkInstantiator::UnRegisterInstantiator("vtkPriorityQueue", vtkInstantiatorvtkPriorityQueueNew);
  vtkInstantiator::UnRegisterInstantiator("vtkPropCollection", vtkInstantiatorvtkPropCollectionNew);
  vtkInstantiator::UnRegisterInstantiator("vtkProperty2D", vtkInstantiatorvtkProperty2DNew);
  vtkInstantiator::UnRegisterInstantiator("vtkQuadratureSchemeDefinition", vtkInstantiatorvtkQuadratureSchemeDefinitionNew);
  vtkInstantiator::UnRegisterInstantiator("vtkQuadric", vtkInstantiatorvtkQuadricNew);
  vtkInstantiator::UnRegisterInstantiator("vtkReferenceCount", vtkInstantiatorvtkReferenceCountNew);
  vtkInstantiator::UnRegisterInstantiator("vtkRungeKutta2", vtkInstantiatorvtkRungeKutta2New);
  vtkInstantiator::UnRegisterInstantiator("vtkRungeKutta4", vtkInstantiatorvtkRungeKutta4New);
  vtkInstantiator::UnRegisterInstantiator("vtkRungeKutta45", vtkInstantiatorvtkRungeKutta45New);
  vtkInstantiator::UnRegisterInstantiator("vtkServerSocket", vtkInstantiatorvtkServerSocketNew);
  vtkInstantiator::UnRegisterInstantiator("vtkShortArray", vtkInstantiatorvtkShortArrayNew);
  vtkInstantiator::UnRegisterInstantiator("vtkSignedCharArray", vtkInstantiatorvtkSignedCharArrayNew);
  vtkInstantiator::UnRegisterInstantiator("vtkSocketCollection", vtkInstantiatorvtkSocketCollectionNew);
  vtkInstantiator::UnRegisterInstantiator("vtkSortDataArray", vtkInstantiatorvtkSortDataArrayNew);
  vtkInstantiator::UnRegisterInstantiator("vtkSphericalTransform", vtkInstantiatorvtkSphericalTransformNew);
  vtkInstantiator::UnRegisterInstantiator("vtkStringArray", vtkInstantiatorvtkStringArrayNew);
  vtkInstantiator::UnRegisterInstantiator("vtkStructuredExtent", vtkInstantiatorvtkStructuredExtentNew);
  vtkInstantiator::UnRegisterInstantiator("vtkStructuredVisibilityConstraint", vtkInstantiatorvtkStructuredVisibilityConstraintNew);
  vtkInstantiator::UnRegisterInstantiator("vtkTableExtentTranslator", vtkInstantiatorvtkTableExtentTranslatorNew);
  vtkInstantiator::UnRegisterInstantiator("vtkTensor", vtkInstantiatorvtkTensorNew);
  vtkInstantiator::UnRegisterInstantiator("vtkThreadMessager", vtkInstantiatorvtkThreadMessagerNew);
  vtkInstantiator::UnRegisterInstantiator("vtkTimePointUtility", vtkInstantiatorvtkTimePointUtilityNew);
  vtkInstantiator::UnRegisterInstantiator("vtkTimerLog", vtkInstantiatorvtkTimerLogNew);
  vtkInstantiator::UnRegisterInstantiator("vtkTransform2D", vtkInstantiatorvtkTransform2DNew);
  vtkInstantiator::UnRegisterInstantiator("vtkTransform", vtkInstantiatorvtkTransformNew);
  vtkInstantiator::UnRegisterInstantiator("vtkTransformCollection", vtkInstantiatorvtkTransformCollectionNew);
  vtkInstantiator::UnRegisterInstantiator("vtkUnicodeStringArray", vtkInstantiatorvtkUnicodeStringArrayNew);
  vtkInstantiator::UnRegisterInstantiator("vtkUnsignedCharArray", vtkInstantiatorvtkUnsignedCharArrayNew);
  vtkInstantiator::UnRegisterInstantiator("vtkUnsignedIntArray", vtkInstantiatorvtkUnsignedIntArrayNew);
  vtkInstantiator::UnRegisterInstantiator("vtkUnsignedLongArray", vtkInstantiatorvtkUnsignedLongArrayNew);
  vtkInstantiator::UnRegisterInstantiator("vtkUnsignedShortArray", vtkInstantiatorvtkUnsignedShortArrayNew);
  vtkInstantiator::UnRegisterInstantiator("vtkVersion", vtkInstantiatorvtkVersionNew);
  vtkInstantiator::UnRegisterInstantiator("vtkVoidArray", vtkInstantiatorvtkVoidArrayNew);
  vtkInstantiator::UnRegisterInstantiator("vtkWindowLevelLookupTable", vtkInstantiatorvtkWindowLevelLookupTableNew);
  vtkInstantiator::UnRegisterInstantiator("vtkXMLDataElement", vtkInstantiatorvtkXMLDataElementNew);
  vtkInstantiator::UnRegisterInstantiator("vtkXMLFileOutputWindow", vtkInstantiatorvtkXMLFileOutputWindowNew);
  vtkInstantiator::UnRegisterInstantiator("vtkLongLongArray", vtkInstantiatorvtkLongLongArrayNew);
  vtkInstantiator::UnRegisterInstantiator("vtkUnsignedLongLongArray", vtkInstantiatorvtkUnsignedLongLongArrayNew);
  vtkInstantiator::UnRegisterInstantiator("vtkTypeInt8Array", vtkInstantiatorvtkTypeInt8ArrayNew);
  vtkInstantiator::UnRegisterInstantiator("vtkTypeInt16Array", vtkInstantiatorvtkTypeInt16ArrayNew);
  vtkInstantiator::UnRegisterInstantiator("vtkTypeInt32Array", vtkInstantiatorvtkTypeInt32ArrayNew);
  vtkInstantiator::UnRegisterInstantiator("vtkTypeInt64Array", vtkInstantiatorvtkTypeInt64ArrayNew);
  vtkInstantiator::UnRegisterInstantiator("vtkTypeUInt8Array", vtkInstantiatorvtkTypeUInt8ArrayNew);
  vtkInstantiator::UnRegisterInstantiator("vtkTypeUInt16Array", vtkInstantiatorvtkTypeUInt16ArrayNew);
  vtkInstantiator::UnRegisterInstantiator("vtkTypeUInt32Array", vtkInstantiatorvtkTypeUInt32ArrayNew);
  vtkInstantiator::UnRegisterInstantiator("vtkTypeUInt64Array", vtkInstantiatorvtkTypeUInt64ArrayNew);
  vtkInstantiator::UnRegisterInstantiator("vtkTypeFloat32Array", vtkInstantiatorvtkTypeFloat32ArrayNew);
  vtkInstantiator::UnRegisterInstantiator("vtkTypeFloat64Array", vtkInstantiatorvtkTypeFloat64ArrayNew);

  
}

vtkCommonInstantiator::vtkCommonInstantiator()
{
  if(++vtkCommonInstantiator::Count == 1)
    { 
    vtkCommonInstantiator::ClassInitialize(); 
    }
}

vtkCommonInstantiator::~vtkCommonInstantiator()
{
  if(--vtkCommonInstantiator::Count == 0)
    { 
    vtkCommonInstantiator::ClassFinalize(); 
    }
}

// Number of translation units that include this class's header.
// Purposely not initialized.  Default is static initialization to 0.
unsigned int vtkCommonInstantiator::Count;
