#include "vtkFilteringInstantiator.h"
  
extern vtkObject* vtkInstantiatorvtkActor2DCollectionNew();
extern vtkObject* vtkInstantiatorvtkActor2DNew();
extern vtkObject* vtkInstantiatorvtkAdjacentVertexIteratorNew();
extern vtkObject* vtkInstantiatorvtkAlgorithmNew();
extern vtkObject* vtkInstantiatorvtkAlgorithmOutputNew();
extern vtkObject* vtkInstantiatorvtkAnnotationNew();
extern vtkObject* vtkInstantiatorvtkAnnotationLayersNew();
extern vtkObject* vtkInstantiatorvtkAnnotationLayersAlgorithmNew();
extern vtkObject* vtkInstantiatorvtkAttributesErrorMetricNew();
extern vtkObject* vtkInstantiatorvtkBiQuadraticQuadNew();
extern vtkObject* vtkInstantiatorvtkBiQuadraticQuadraticHexahedronNew();
extern vtkObject* vtkInstantiatorvtkBiQuadraticQuadraticWedgeNew();
extern vtkObject* vtkInstantiatorvtkBiQuadraticTriangleNew();
extern vtkObject* vtkInstantiatorvtkBSPCutsNew();
extern vtkObject* vtkInstantiatorvtkBSPIntersectionsNew();
extern vtkObject* vtkInstantiatorvtkCachedStreamingDemandDrivenPipelineNew();
extern vtkObject* vtkInstantiatorvtkCardinalSplineNew();
extern vtkObject* vtkInstantiatorvtkCastToConcreteNew();
extern vtkObject* vtkInstantiatorvtkCellArrayNew();
extern vtkObject* vtkInstantiatorvtkCellDataNew();
extern vtkObject* vtkInstantiatorvtkCellLinksNew();
extern vtkObject* vtkInstantiatorvtkCellLocatorNew();
extern vtkObject* vtkInstantiatorvtkCellTypesNew();
extern vtkObject* vtkInstantiatorvtkColorTransferFunctionNew();
extern vtkObject* vtkInstantiatorvtkCompositeDataPipelineNew();
extern vtkObject* vtkInstantiatorvtkCompositeDataSetAlgorithmNew();
extern vtkObject* vtkInstantiatorvtkComputingResourcesNew();
extern vtkObject* vtkInstantiatorvtkConeNew();
extern vtkObject* vtkInstantiatorvtkConvexPointSetNew();
extern vtkObject* vtkInstantiatorvtkCoordinateNew();
extern vtkObject* vtkInstantiatorvtkCubicLineNew();
extern vtkObject* vtkInstantiatorvtkCylinderNew();
extern vtkObject* vtkInstantiatorvtkDataObjectAlgorithmNew();
extern vtkObject* vtkInstantiatorvtkDataObjectCollectionNew();
extern vtkObject* vtkInstantiatorvtkDataObjectNew();
extern vtkObject* vtkInstantiatorvtkDataObjectTypesNew();
extern vtkObject* vtkInstantiatorvtkDataSetAlgorithmNew();
extern vtkObject* vtkInstantiatorvtkDataSetAttributesNew();
extern vtkObject* vtkInstantiatorvtkDataSetCollectionNew();
extern vtkObject* vtkInstantiatorvtkDemandDrivenPipelineNew();
extern vtkObject* vtkInstantiatorvtkDirectedAcyclicGraphNew();
extern vtkObject* vtkInstantiatorvtkDirectedGraphAlgorithmNew();
extern vtkObject* vtkInstantiatorvtkDirectedGraphNew();
extern vtkObject* vtkInstantiatorvtkDiscretizableColorTransferFunctionNew();
extern vtkObject* vtkInstantiatorvtkEdgeListIteratorNew();
extern vtkObject* vtkInstantiatorvtkEmptyCellNew();
extern vtkObject* vtkInstantiatorvtkExecutionSchedulerNew();
extern vtkObject* vtkInstantiatorvtkExecutiveCollectionNew();
extern vtkObject* vtkInstantiatorvtkFieldDataNew();
extern vtkObject* vtkInstantiatorvtkGenericAttributeCollectionNew();
extern vtkObject* vtkInstantiatorvtkGenericCellNew();
extern vtkObject* vtkInstantiatorvtkGenericEdgeTableNew();
extern vtkObject* vtkInstantiatorvtkGenericInterpolatedVelocityFieldNew();
extern vtkObject* vtkInstantiatorvtkGeometricErrorMetricNew();
extern vtkObject* vtkInstantiatorvtkGraphAlgorithmNew();
extern vtkObject* vtkInstantiatorvtkGraphEdgeNew();
extern vtkObject* vtkInstantiatorvtkGraphInternalsNew();
extern vtkObject* vtkInstantiatorvtkHexagonalPrismNew();
extern vtkObject* vtkInstantiatorvtkHexahedronNew();
extern vtkObject* vtkInstantiatorvtkHierarchicalBoxDataIteratorNew();
extern vtkObject* vtkInstantiatorvtkHierarchicalBoxDataSetAlgorithmNew();
extern vtkObject* vtkInstantiatorvtkHierarchicalBoxDataSetNew();
extern vtkObject* vtkInstantiatorvtkHyperOctreeNew();
extern vtkObject* vtkInstantiatorvtkImageDataNew();
extern vtkObject* vtkInstantiatorvtkImageToStructuredPointsNew();
extern vtkObject* vtkInstantiatorvtkImplicitBooleanNew();
extern vtkObject* vtkInstantiatorvtkImplicitDataSetNew();
extern vtkObject* vtkInstantiatorvtkImplicitHaloNew();
extern vtkObject* vtkInstantiatorvtkImplicitSelectionLoopNew();
extern vtkObject* vtkInstantiatorvtkImplicitSumNew();
extern vtkObject* vtkInstantiatorvtkImplicitVolumeNew();
extern vtkObject* vtkInstantiatorvtkImplicitWindowFunctionNew();
extern vtkObject* vtkInstantiatorvtkIncrementalOctreeNodeNew();
extern vtkObject* vtkInstantiatorvtkIncrementalOctreePointLocatorNew();
extern vtkObject* vtkInstantiatorvtkInEdgeIteratorNew();
extern vtkObject* vtkInstantiatorvtkInterpolatedVelocityFieldNew();
extern vtkObject* vtkInstantiatorvtkKdNodeNew();
extern vtkObject* vtkInstantiatorvtkKdTreeNew();
extern vtkObject* vtkInstantiatorvtkKdTreePointLocatorNew();
extern vtkObject* vtkInstantiatorvtkKochanekSplineNew();
extern vtkObject* vtkInstantiatorvtkLineNew();
extern vtkObject* vtkInstantiatorvtkMeanValueCoordinatesInterpolatorNew();
extern vtkObject* vtkInstantiatorvtkMergePointsNew();
extern vtkObject* vtkInstantiatorvtkMultiBlockDataSetAlgorithmNew();
extern vtkObject* vtkInstantiatorvtkMultiBlockDataSetNew();
extern vtkObject* vtkInstantiatorvtkMultiPieceDataSetNew();
extern vtkObject* vtkInstantiatorvtkMutableDirectedGraphNew();
extern vtkObject* vtkInstantiatorvtkMutableUndirectedGraphNew();
extern vtkObject* vtkInstantiatorvtkNonMergingPointLocatorNew();
extern vtkObject* vtkInstantiatorvtkOctreePointLocatorNew();
extern vtkObject* vtkInstantiatorvtkOctreePointLocatorNodeNew();
extern vtkObject* vtkInstantiatorvtkOrderedTriangulatorNew();
extern vtkObject* vtkInstantiatorvtkOutEdgeIteratorNew();
extern vtkObject* vtkInstantiatorvtkParametricSplineNew();
extern vtkObject* vtkInstantiatorvtkPassInputTypeAlgorithmNew();
extern vtkObject* vtkInstantiatorvtkPentagonalPrismNew();
extern vtkObject* vtkInstantiatorvtkPerlinNoiseNew();
extern vtkObject* vtkInstantiatorvtkPiecewiseFunctionAlgorithmNew();
extern vtkObject* vtkInstantiatorvtkPiecewiseFunctionNew();
extern vtkObject* vtkInstantiatorvtkPiecewiseFunctionShiftScaleNew();
extern vtkObject* vtkInstantiatorvtkPixelNew();
extern vtkObject* vtkInstantiatorvtkPlanesIntersectionNew();
extern vtkObject* vtkInstantiatorvtkPointDataNew();
extern vtkObject* vtkInstantiatorvtkPointLocatorNew();
extern vtkObject* vtkInstantiatorvtkPointSetAlgorithmNew();
extern vtkObject* vtkInstantiatorvtkPointsProjectedHullNew();
extern vtkObject* vtkInstantiatorvtkPolyDataAlgorithmNew();
extern vtkObject* vtkInstantiatorvtkPolyDataCollectionNew();
extern vtkObject* vtkInstantiatorvtkPolyDataNew();
extern vtkObject* vtkInstantiatorvtkPolygonNew();
extern vtkObject* vtkInstantiatorvtkPolyhedronNew();
extern vtkObject* vtkInstantiatorvtkPolyLineNew();
extern vtkObject* vtkInstantiatorvtkPolyVertexNew();
extern vtkObject* vtkInstantiatorvtkPropAssemblyNew();
extern vtkObject* vtkInstantiatorvtkPyramidNew();
extern vtkObject* vtkInstantiatorvtkQuadNew();
extern vtkObject* vtkInstantiatorvtkQuadraticEdgeNew();
extern vtkObject* vtkInstantiatorvtkQuadraticHexahedronNew();
extern vtkObject* vtkInstantiatorvtkQuadraticLinearQuadNew();
extern vtkObject* vtkInstantiatorvtkQuadraticLinearWedgeNew();
extern vtkObject* vtkInstantiatorvtkQuadraticPyramidNew();
extern vtkObject* vtkInstantiatorvtkQuadraticQuadNew();
extern vtkObject* vtkInstantiatorvtkQuadraticTetraNew();
extern vtkObject* vtkInstantiatorvtkQuadraticTriangleNew();
extern vtkObject* vtkInstantiatorvtkQuadraticWedgeNew();
extern vtkObject* vtkInstantiatorvtkRectilinearGridAlgorithmNew();
extern vtkObject* vtkInstantiatorvtkRectilinearGridNew();
extern vtkObject* vtkInstantiatorvtkReebGraphNew();
extern vtkObject* vtkInstantiatorvtkReebGraphSimplificationMetricNew();
extern vtkObject* vtkInstantiatorvtkSelectionAlgorithmNew();
extern vtkObject* vtkInstantiatorvtkSelectionNew();
extern vtkObject* vtkInstantiatorvtkSelectionNodeNew();
extern vtkObject* vtkInstantiatorvtkSimpleCellTessellatorNew();
extern vtkObject* vtkInstantiatorvtkSimpleScalarTreeNew();
extern vtkObject* vtkInstantiatorvtkSmoothErrorMetricNew();
extern vtkObject* vtkInstantiatorvtkSphereNew();
extern vtkObject* vtkInstantiatorvtkStreamingDemandDrivenPipelineNew();
extern vtkObject* vtkInstantiatorvtkStructuredGridAlgorithmNew();
extern vtkObject* vtkInstantiatorvtkStructuredGridNew();
extern vtkObject* vtkInstantiatorvtkStructuredPointsCollectionNew();
extern vtkObject* vtkInstantiatorvtkStructuredPointsNew();
extern vtkObject* vtkInstantiatorvtkSuperquadricNew();
extern vtkObject* vtkInstantiatorvtkTableAlgorithmNew();
extern vtkObject* vtkInstantiatorvtkTableNew();
extern vtkObject* vtkInstantiatorvtkTemporalDataSetAlgorithmNew();
extern vtkObject* vtkInstantiatorvtkTemporalDataSetNew();
extern vtkObject* vtkInstantiatorvtkTetraNew();
extern vtkObject* vtkInstantiatorvtkThreadedStreamingPipelineNew();
extern vtkObject* vtkInstantiatorvtkTreeAlgorithmNew();
extern vtkObject* vtkInstantiatorvtkTreeNew();
extern vtkObject* vtkInstantiatorvtkTreeBFSIteratorNew();
extern vtkObject* vtkInstantiatorvtkTreeDFSIteratorNew();
extern vtkObject* vtkInstantiatorvtkTriangleNew();
extern vtkObject* vtkInstantiatorvtkTriangleStripNew();
extern vtkObject* vtkInstantiatorvtkTriQuadraticHexahedronNew();
extern vtkObject* vtkInstantiatorvtkTrivialProducerNew();
extern vtkObject* vtkInstantiatorvtkUndirectedGraphAlgorithmNew();
extern vtkObject* vtkInstantiatorvtkUndirectedGraphNew();
extern vtkObject* vtkInstantiatorvtkUniformGridNew();
extern vtkObject* vtkInstantiatorvtkUnstructuredGridAlgorithmNew();
extern vtkObject* vtkInstantiatorvtkUnstructuredGridNew();
extern vtkObject* vtkInstantiatorvtkVertexNew();
extern vtkObject* vtkInstantiatorvtkVertexListIteratorNew();
extern vtkObject* vtkInstantiatorvtkViewDependentErrorMetricNew();
extern vtkObject* vtkInstantiatorvtkVoxelNew();
extern vtkObject* vtkInstantiatorvtkWedgeNew();
extern vtkObject* vtkInstantiatorvtkArrayDataNew();
extern vtkObject* vtkInstantiatorvtkArrayDataAlgorithmNew();


  
void vtkFilteringInstantiator::ClassInitialize()
{
  
  vtkInstantiator::RegisterInstantiator("vtkActor2DCollection", vtkInstantiatorvtkActor2DCollectionNew);
  vtkInstantiator::RegisterInstantiator("vtkActor2D", vtkInstantiatorvtkActor2DNew);
  vtkInstantiator::RegisterInstantiator("vtkAdjacentVertexIterator", vtkInstantiatorvtkAdjacentVertexIteratorNew);
  vtkInstantiator::RegisterInstantiator("vtkAlgorithm", vtkInstantiatorvtkAlgorithmNew);
  vtkInstantiator::RegisterInstantiator("vtkAlgorithmOutput", vtkInstantiatorvtkAlgorithmOutputNew);
  vtkInstantiator::RegisterInstantiator("vtkAnnotation", vtkInstantiatorvtkAnnotationNew);
  vtkInstantiator::RegisterInstantiator("vtkAnnotationLayers", vtkInstantiatorvtkAnnotationLayersNew);
  vtkInstantiator::RegisterInstantiator("vtkAnnotationLayersAlgorithm", vtkInstantiatorvtkAnnotationLayersAlgorithmNew);
  vtkInstantiator::RegisterInstantiator("vtkAttributesErrorMetric", vtkInstantiatorvtkAttributesErrorMetricNew);
  vtkInstantiator::RegisterInstantiator("vtkBiQuadraticQuad", vtkInstantiatorvtkBiQuadraticQuadNew);
  vtkInstantiator::RegisterInstantiator("vtkBiQuadraticQuadraticHexahedron", vtkInstantiatorvtkBiQuadraticQuadraticHexahedronNew);
  vtkInstantiator::RegisterInstantiator("vtkBiQuadraticQuadraticWedge", vtkInstantiatorvtkBiQuadraticQuadraticWedgeNew);
  vtkInstantiator::RegisterInstantiator("vtkBiQuadraticTriangle", vtkInstantiatorvtkBiQuadraticTriangleNew);
  vtkInstantiator::RegisterInstantiator("vtkBSPCuts", vtkInstantiatorvtkBSPCutsNew);
  vtkInstantiator::RegisterInstantiator("vtkBSPIntersections", vtkInstantiatorvtkBSPIntersectionsNew);
  vtkInstantiator::RegisterInstantiator("vtkCachedStreamingDemandDrivenPipeline", vtkInstantiatorvtkCachedStreamingDemandDrivenPipelineNew);
  vtkInstantiator::RegisterInstantiator("vtkCardinalSpline", vtkInstantiatorvtkCardinalSplineNew);
  vtkInstantiator::RegisterInstantiator("vtkCastToConcrete", vtkInstantiatorvtkCastToConcreteNew);
  vtkInstantiator::RegisterInstantiator("vtkCellArray", vtkInstantiatorvtkCellArrayNew);
  vtkInstantiator::RegisterInstantiator("vtkCellData", vtkInstantiatorvtkCellDataNew);
  vtkInstantiator::RegisterInstantiator("vtkCellLinks", vtkInstantiatorvtkCellLinksNew);
  vtkInstantiator::RegisterInstantiator("vtkCellLocator", vtkInstantiatorvtkCellLocatorNew);
  vtkInstantiator::RegisterInstantiator("vtkCellTypes", vtkInstantiatorvtkCellTypesNew);
  vtkInstantiator::RegisterInstantiator("vtkColorTransferFunction", vtkInstantiatorvtkColorTransferFunctionNew);
  vtkInstantiator::RegisterInstantiator("vtkCompositeDataPipeline", vtkInstantiatorvtkCompositeDataPipelineNew);
  vtkInstantiator::RegisterInstantiator("vtkCompositeDataSetAlgorithm", vtkInstantiatorvtkCompositeDataSetAlgorithmNew);
  vtkInstantiator::RegisterInstantiator("vtkComputingResources", vtkInstantiatorvtkComputingResourcesNew);
  vtkInstantiator::RegisterInstantiator("vtkCone", vtkInstantiatorvtkConeNew);
  vtkInstantiator::RegisterInstantiator("vtkConvexPointSet", vtkInstantiatorvtkConvexPointSetNew);
  vtkInstantiator::RegisterInstantiator("vtkCoordinate", vtkInstantiatorvtkCoordinateNew);
  vtkInstantiator::RegisterInstantiator("vtkCubicLine", vtkInstantiatorvtkCubicLineNew);
  vtkInstantiator::RegisterInstantiator("vtkCylinder", vtkInstantiatorvtkCylinderNew);
  vtkInstantiator::RegisterInstantiator("vtkDataObjectAlgorithm", vtkInstantiatorvtkDataObjectAlgorithmNew);
  vtkInstantiator::RegisterInstantiator("vtkDataObjectCollection", vtkInstantiatorvtkDataObjectCollectionNew);
  vtkInstantiator::RegisterInstantiator("vtkDataObject", vtkInstantiatorvtkDataObjectNew);
  vtkInstantiator::RegisterInstantiator("vtkDataObjectTypes", vtkInstantiatorvtkDataObjectTypesNew);
  vtkInstantiator::RegisterInstantiator("vtkDataSetAlgorithm", vtkInstantiatorvtkDataSetAlgorithmNew);
  vtkInstantiator::RegisterInstantiator("vtkDataSetAttributes", vtkInstantiatorvtkDataSetAttributesNew);
  vtkInstantiator::RegisterInstantiator("vtkDataSetCollection", vtkInstantiatorvtkDataSetCollectionNew);
  vtkInstantiator::RegisterInstantiator("vtkDemandDrivenPipeline", vtkInstantiatorvtkDemandDrivenPipelineNew);
  vtkInstantiator::RegisterInstantiator("vtkDirectedAcyclicGraph", vtkInstantiatorvtkDirectedAcyclicGraphNew);
  vtkInstantiator::RegisterInstantiator("vtkDirectedGraphAlgorithm", vtkInstantiatorvtkDirectedGraphAlgorithmNew);
  vtkInstantiator::RegisterInstantiator("vtkDirectedGraph", vtkInstantiatorvtkDirectedGraphNew);
  vtkInstantiator::RegisterInstantiator("vtkDiscretizableColorTransferFunction", vtkInstantiatorvtkDiscretizableColorTransferFunctionNew);
  vtkInstantiator::RegisterInstantiator("vtkEdgeListIterator", vtkInstantiatorvtkEdgeListIteratorNew);
  vtkInstantiator::RegisterInstantiator("vtkEmptyCell", vtkInstantiatorvtkEmptyCellNew);
  vtkInstantiator::RegisterInstantiator("vtkExecutionScheduler", vtkInstantiatorvtkExecutionSchedulerNew);
  vtkInstantiator::RegisterInstantiator("vtkExecutiveCollection", vtkInstantiatorvtkExecutiveCollectionNew);
  vtkInstantiator::RegisterInstantiator("vtkFieldData", vtkInstantiatorvtkFieldDataNew);
  vtkInstantiator::RegisterInstantiator("vtkGenericAttributeCollection", vtkInstantiatorvtkGenericAttributeCollectionNew);
  vtkInstantiator::RegisterInstantiator("vtkGenericCell", vtkInstantiatorvtkGenericCellNew);
  vtkInstantiator::RegisterInstantiator("vtkGenericEdgeTable", vtkInstantiatorvtkGenericEdgeTableNew);
  vtkInstantiator::RegisterInstantiator("vtkGenericInterpolatedVelocityField", vtkInstantiatorvtkGenericInterpolatedVelocityFieldNew);
  vtkInstantiator::RegisterInstantiator("vtkGeometricErrorMetric", vtkInstantiatorvtkGeometricErrorMetricNew);
  vtkInstantiator::RegisterInstantiator("vtkGraphAlgorithm", vtkInstantiatorvtkGraphAlgorithmNew);
  vtkInstantiator::RegisterInstantiator("vtkGraphEdge", vtkInstantiatorvtkGraphEdgeNew);
  vtkInstantiator::RegisterInstantiator("vtkGraphInternals", vtkInstantiatorvtkGraphInternalsNew);
  vtkInstantiator::RegisterInstantiator("vtkHexagonalPrism", vtkInstantiatorvtkHexagonalPrismNew);
  vtkInstantiator::RegisterInstantiator("vtkHexahedron", vtkInstantiatorvtkHexahedronNew);
  vtkInstantiator::RegisterInstantiator("vtkHierarchicalBoxDataIterator", vtkInstantiatorvtkHierarchicalBoxDataIteratorNew);
  vtkInstantiator::RegisterInstantiator("vtkHierarchicalBoxDataSetAlgorithm", vtkInstantiatorvtkHierarchicalBoxDataSetAlgorithmNew);
  vtkInstantiator::RegisterInstantiator("vtkHierarchicalBoxDataSet", vtkInstantiatorvtkHierarchicalBoxDataSetNew);
  vtkInstantiator::RegisterInstantiator("vtkHyperOctree", vtkInstantiatorvtkHyperOctreeNew);
  vtkInstantiator::RegisterInstantiator("vtkImageData", vtkInstantiatorvtkImageDataNew);
  vtkInstantiator::RegisterInstantiator("vtkImageToStructuredPoints", vtkInstantiatorvtkImageToStructuredPointsNew);
  vtkInstantiator::RegisterInstantiator("vtkImplicitBoolean", vtkInstantiatorvtkImplicitBooleanNew);
  vtkInstantiator::RegisterInstantiator("vtkImplicitDataSet", vtkInstantiatorvtkImplicitDataSetNew);
  vtkInstantiator::RegisterInstantiator("vtkImplicitHalo", vtkInstantiatorvtkImplicitHaloNew);
  vtkInstantiator::RegisterInstantiator("vtkImplicitSelectionLoop", vtkInstantiatorvtkImplicitSelectionLoopNew);
  vtkInstantiator::RegisterInstantiator("vtkImplicitSum", vtkInstantiatorvtkImplicitSumNew);
  vtkInstantiator::RegisterInstantiator("vtkImplicitVolume", vtkInstantiatorvtkImplicitVolumeNew);
  vtkInstantiator::RegisterInstantiator("vtkImplicitWindowFunction", vtkInstantiatorvtkImplicitWindowFunctionNew);
  vtkInstantiator::RegisterInstantiator("vtkIncrementalOctreeNode", vtkInstantiatorvtkIncrementalOctreeNodeNew);
  vtkInstantiator::RegisterInstantiator("vtkIncrementalOctreePointLocator", vtkInstantiatorvtkIncrementalOctreePointLocatorNew);
  vtkInstantiator::RegisterInstantiator("vtkInEdgeIterator", vtkInstantiatorvtkInEdgeIteratorNew);
  vtkInstantiator::RegisterInstantiator("vtkInterpolatedVelocityField", vtkInstantiatorvtkInterpolatedVelocityFieldNew);
  vtkInstantiator::RegisterInstantiator("vtkKdNode", vtkInstantiatorvtkKdNodeNew);
  vtkInstantiator::RegisterInstantiator("vtkKdTree", vtkInstantiatorvtkKdTreeNew);
  vtkInstantiator::RegisterInstantiator("vtkKdTreePointLocator", vtkInstantiatorvtkKdTreePointLocatorNew);
  vtkInstantiator::RegisterInstantiator("vtkKochanekSpline", vtkInstantiatorvtkKochanekSplineNew);
  vtkInstantiator::RegisterInstantiator("vtkLine", vtkInstantiatorvtkLineNew);
  vtkInstantiator::RegisterInstantiator("vtkMeanValueCoordinatesInterpolator", vtkInstantiatorvtkMeanValueCoordinatesInterpolatorNew);
  vtkInstantiator::RegisterInstantiator("vtkMergePoints", vtkInstantiatorvtkMergePointsNew);
  vtkInstantiator::RegisterInstantiator("vtkMultiBlockDataSetAlgorithm", vtkInstantiatorvtkMultiBlockDataSetAlgorithmNew);
  vtkInstantiator::RegisterInstantiator("vtkMultiBlockDataSet", vtkInstantiatorvtkMultiBlockDataSetNew);
  vtkInstantiator::RegisterInstantiator("vtkMultiPieceDataSet", vtkInstantiatorvtkMultiPieceDataSetNew);
  vtkInstantiator::RegisterInstantiator("vtkMutableDirectedGraph", vtkInstantiatorvtkMutableDirectedGraphNew);
  vtkInstantiator::RegisterInstantiator("vtkMutableUndirectedGraph", vtkInstantiatorvtkMutableUndirectedGraphNew);
  vtkInstantiator::RegisterInstantiator("vtkNonMergingPointLocator", vtkInstantiatorvtkNonMergingPointLocatorNew);
  vtkInstantiator::RegisterInstantiator("vtkOctreePointLocator", vtkInstantiatorvtkOctreePointLocatorNew);
  vtkInstantiator::RegisterInstantiator("vtkOctreePointLocatorNode", vtkInstantiatorvtkOctreePointLocatorNodeNew);
  vtkInstantiator::RegisterInstantiator("vtkOrderedTriangulator", vtkInstantiatorvtkOrderedTriangulatorNew);
  vtkInstantiator::RegisterInstantiator("vtkOutEdgeIterator", vtkInstantiatorvtkOutEdgeIteratorNew);
  vtkInstantiator::RegisterInstantiator("vtkParametricSpline", vtkInstantiatorvtkParametricSplineNew);
  vtkInstantiator::RegisterInstantiator("vtkPassInputTypeAlgorithm", vtkInstantiatorvtkPassInputTypeAlgorithmNew);
  vtkInstantiator::RegisterInstantiator("vtkPentagonalPrism", vtkInstantiatorvtkPentagonalPrismNew);
  vtkInstantiator::RegisterInstantiator("vtkPerlinNoise", vtkInstantiatorvtkPerlinNoiseNew);
  vtkInstantiator::RegisterInstantiator("vtkPiecewiseFunctionAlgorithm", vtkInstantiatorvtkPiecewiseFunctionAlgorithmNew);
  vtkInstantiator::RegisterInstantiator("vtkPiecewiseFunction", vtkInstantiatorvtkPiecewiseFunctionNew);
  vtkInstantiator::RegisterInstantiator("vtkPiecewiseFunctionShiftScale", vtkInstantiatorvtkPiecewiseFunctionShiftScaleNew);
  vtkInstantiator::RegisterInstantiator("vtkPixel", vtkInstantiatorvtkPixelNew);
  vtkInstantiator::RegisterInstantiator("vtkPlanesIntersection", vtkInstantiatorvtkPlanesIntersectionNew);
  vtkInstantiator::RegisterInstantiator("vtkPointData", vtkInstantiatorvtkPointDataNew);
  vtkInstantiator::RegisterInstantiator("vtkPointLocator", vtkInstantiatorvtkPointLocatorNew);
  vtkInstantiator::RegisterInstantiator("vtkPointSetAlgorithm", vtkInstantiatorvtkPointSetAlgorithmNew);
  vtkInstantiator::RegisterInstantiator("vtkPointsProjectedHull", vtkInstantiatorvtkPointsProjectedHullNew);
  vtkInstantiator::RegisterInstantiator("vtkPolyDataAlgorithm", vtkInstantiatorvtkPolyDataAlgorithmNew);
  vtkInstantiator::RegisterInstantiator("vtkPolyDataCollection", vtkInstantiatorvtkPolyDataCollectionNew);
  vtkInstantiator::RegisterInstantiator("vtkPolyData", vtkInstantiatorvtkPolyDataNew);
  vtkInstantiator::RegisterInstantiator("vtkPolygon", vtkInstantiatorvtkPolygonNew);
  vtkInstantiator::RegisterInstantiator("vtkPolyhedron", vtkInstantiatorvtkPolyhedronNew);
  vtkInstantiator::RegisterInstantiator("vtkPolyLine", vtkInstantiatorvtkPolyLineNew);
  vtkInstantiator::RegisterInstantiator("vtkPolyVertex", vtkInstantiatorvtkPolyVertexNew);
  vtkInstantiator::RegisterInstantiator("vtkPropAssembly", vtkInstantiatorvtkPropAssemblyNew);
  vtkInstantiator::RegisterInstantiator("vtkPyramid", vtkInstantiatorvtkPyramidNew);
  vtkInstantiator::RegisterInstantiator("vtkQuad", vtkInstantiatorvtkQuadNew);
  vtkInstantiator::RegisterInstantiator("vtkQuadraticEdge", vtkInstantiatorvtkQuadraticEdgeNew);
  vtkInstantiator::RegisterInstantiator("vtkQuadraticHexahedron", vtkInstantiatorvtkQuadraticHexahedronNew);
  vtkInstantiator::RegisterInstantiator("vtkQuadraticLinearQuad", vtkInstantiatorvtkQuadraticLinearQuadNew);
  vtkInstantiator::RegisterInstantiator("vtkQuadraticLinearWedge", vtkInstantiatorvtkQuadraticLinearWedgeNew);
  vtkInstantiator::RegisterInstantiator("vtkQuadraticPyramid", vtkInstantiatorvtkQuadraticPyramidNew);
  vtkInstantiator::RegisterInstantiator("vtkQuadraticQuad", vtkInstantiatorvtkQuadraticQuadNew);
  vtkInstantiator::RegisterInstantiator("vtkQuadraticTetra", vtkInstantiatorvtkQuadraticTetraNew);
  vtkInstantiator::RegisterInstantiator("vtkQuadraticTriangle", vtkInstantiatorvtkQuadraticTriangleNew);
  vtkInstantiator::RegisterInstantiator("vtkQuadraticWedge", vtkInstantiatorvtkQuadraticWedgeNew);
  vtkInstantiator::RegisterInstantiator("vtkRectilinearGridAlgorithm", vtkInstantiatorvtkRectilinearGridAlgorithmNew);
  vtkInstantiator::RegisterInstantiator("vtkRectilinearGrid", vtkInstantiatorvtkRectilinearGridNew);
  vtkInstantiator::RegisterInstantiator("vtkReebGraph", vtkInstantiatorvtkReebGraphNew);
  vtkInstantiator::RegisterInstantiator("vtkReebGraphSimplificationMetric", vtkInstantiatorvtkReebGraphSimplificationMetricNew);
  vtkInstantiator::RegisterInstantiator("vtkSelectionAlgorithm", vtkInstantiatorvtkSelectionAlgorithmNew);
  vtkInstantiator::RegisterInstantiator("vtkSelection", vtkInstantiatorvtkSelectionNew);
  vtkInstantiator::RegisterInstantiator("vtkSelectionNode", vtkInstantiatorvtkSelectionNodeNew);
  vtkInstantiator::RegisterInstantiator("vtkSimpleCellTessellator", vtkInstantiatorvtkSimpleCellTessellatorNew);
  vtkInstantiator::RegisterInstantiator("vtkSimpleScalarTree", vtkInstantiatorvtkSimpleScalarTreeNew);
  vtkInstantiator::RegisterInstantiator("vtkSmoothErrorMetric", vtkInstantiatorvtkSmoothErrorMetricNew);
  vtkInstantiator::RegisterInstantiator("vtkSphere", vtkInstantiatorvtkSphereNew);
  vtkInstantiator::RegisterInstantiator("vtkStreamingDemandDrivenPipeline", vtkInstantiatorvtkStreamingDemandDrivenPipelineNew);
  vtkInstantiator::RegisterInstantiator("vtkStructuredGridAlgorithm", vtkInstantiatorvtkStructuredGridAlgorithmNew);
  vtkInstantiator::RegisterInstantiator("vtkStructuredGrid", vtkInstantiatorvtkStructuredGridNew);
  vtkInstantiator::RegisterInstantiator("vtkStructuredPointsCollection", vtkInstantiatorvtkStructuredPointsCollectionNew);
  vtkInstantiator::RegisterInstantiator("vtkStructuredPoints", vtkInstantiatorvtkStructuredPointsNew);
  vtkInstantiator::RegisterInstantiator("vtkSuperquadric", vtkInstantiatorvtkSuperquadricNew);
  vtkInstantiator::RegisterInstantiator("vtkTableAlgorithm", vtkInstantiatorvtkTableAlgorithmNew);
  vtkInstantiator::RegisterInstantiator("vtkTable", vtkInstantiatorvtkTableNew);
  vtkInstantiator::RegisterInstantiator("vtkTemporalDataSetAlgorithm", vtkInstantiatorvtkTemporalDataSetAlgorithmNew);
  vtkInstantiator::RegisterInstantiator("vtkTemporalDataSet", vtkInstantiatorvtkTemporalDataSetNew);
  vtkInstantiator::RegisterInstantiator("vtkTetra", vtkInstantiatorvtkTetraNew);
  vtkInstantiator::RegisterInstantiator("vtkThreadedStreamingPipeline", vtkInstantiatorvtkThreadedStreamingPipelineNew);
  vtkInstantiator::RegisterInstantiator("vtkTreeAlgorithm", vtkInstantiatorvtkTreeAlgorithmNew);
  vtkInstantiator::RegisterInstantiator("vtkTree", vtkInstantiatorvtkTreeNew);
  vtkInstantiator::RegisterInstantiator("vtkTreeBFSIterator", vtkInstantiatorvtkTreeBFSIteratorNew);
  vtkInstantiator::RegisterInstantiator("vtkTreeDFSIterator", vtkInstantiatorvtkTreeDFSIteratorNew);
  vtkInstantiator::RegisterInstantiator("vtkTriangle", vtkInstantiatorvtkTriangleNew);
  vtkInstantiator::RegisterInstantiator("vtkTriangleStrip", vtkInstantiatorvtkTriangleStripNew);
  vtkInstantiator::RegisterInstantiator("vtkTriQuadraticHexahedron", vtkInstantiatorvtkTriQuadraticHexahedronNew);
  vtkInstantiator::RegisterInstantiator("vtkTrivialProducer", vtkInstantiatorvtkTrivialProducerNew);
  vtkInstantiator::RegisterInstantiator("vtkUndirectedGraphAlgorithm", vtkInstantiatorvtkUndirectedGraphAlgorithmNew);
  vtkInstantiator::RegisterInstantiator("vtkUndirectedGraph", vtkInstantiatorvtkUndirectedGraphNew);
  vtkInstantiator::RegisterInstantiator("vtkUniformGrid", vtkInstantiatorvtkUniformGridNew);
  vtkInstantiator::RegisterInstantiator("vtkUnstructuredGridAlgorithm", vtkInstantiatorvtkUnstructuredGridAlgorithmNew);
  vtkInstantiator::RegisterInstantiator("vtkUnstructuredGrid", vtkInstantiatorvtkUnstructuredGridNew);
  vtkInstantiator::RegisterInstantiator("vtkVertex", vtkInstantiatorvtkVertexNew);
  vtkInstantiator::RegisterInstantiator("vtkVertexListIterator", vtkInstantiatorvtkVertexListIteratorNew);
  vtkInstantiator::RegisterInstantiator("vtkViewDependentErrorMetric", vtkInstantiatorvtkViewDependentErrorMetricNew);
  vtkInstantiator::RegisterInstantiator("vtkVoxel", vtkInstantiatorvtkVoxelNew);
  vtkInstantiator::RegisterInstantiator("vtkWedge", vtkInstantiatorvtkWedgeNew);
  vtkInstantiator::RegisterInstantiator("vtkArrayData", vtkInstantiatorvtkArrayDataNew);
  vtkInstantiator::RegisterInstantiator("vtkArrayDataAlgorithm", vtkInstantiatorvtkArrayDataAlgorithmNew);

  
}
          
void vtkFilteringInstantiator::ClassFinalize()
{ 

  vtkInstantiator::UnRegisterInstantiator("vtkActor2DCollection", vtkInstantiatorvtkActor2DCollectionNew);
  vtkInstantiator::UnRegisterInstantiator("vtkActor2D", vtkInstantiatorvtkActor2DNew);
  vtkInstantiator::UnRegisterInstantiator("vtkAdjacentVertexIterator", vtkInstantiatorvtkAdjacentVertexIteratorNew);
  vtkInstantiator::UnRegisterInstantiator("vtkAlgorithm", vtkInstantiatorvtkAlgorithmNew);
  vtkInstantiator::UnRegisterInstantiator("vtkAlgorithmOutput", vtkInstantiatorvtkAlgorithmOutputNew);
  vtkInstantiator::UnRegisterInstantiator("vtkAnnotation", vtkInstantiatorvtkAnnotationNew);
  vtkInstantiator::UnRegisterInstantiator("vtkAnnotationLayers", vtkInstantiatorvtkAnnotationLayersNew);
  vtkInstantiator::UnRegisterInstantiator("vtkAnnotationLayersAlgorithm", vtkInstantiatorvtkAnnotationLayersAlgorithmNew);
  vtkInstantiator::UnRegisterInstantiator("vtkAttributesErrorMetric", vtkInstantiatorvtkAttributesErrorMetricNew);
  vtkInstantiator::UnRegisterInstantiator("vtkBiQuadraticQuad", vtkInstantiatorvtkBiQuadraticQuadNew);
  vtkInstantiator::UnRegisterInstantiator("vtkBiQuadraticQuadraticHexahedron", vtkInstantiatorvtkBiQuadraticQuadraticHexahedronNew);
  vtkInstantiator::UnRegisterInstantiator("vtkBiQuadraticQuadraticWedge", vtkInstantiatorvtkBiQuadraticQuadraticWedgeNew);
  vtkInstantiator::UnRegisterInstantiator("vtkBiQuadraticTriangle", vtkInstantiatorvtkBiQuadraticTriangleNew);
  vtkInstantiator::UnRegisterInstantiator("vtkBSPCuts", vtkInstantiatorvtkBSPCutsNew);
  vtkInstantiator::UnRegisterInstantiator("vtkBSPIntersections", vtkInstantiatorvtkBSPIntersectionsNew);
  vtkInstantiator::UnRegisterInstantiator("vtkCachedStreamingDemandDrivenPipeline", vtkInstantiatorvtkCachedStreamingDemandDrivenPipelineNew);
  vtkInstantiator::UnRegisterInstantiator("vtkCardinalSpline", vtkInstantiatorvtkCardinalSplineNew);
  vtkInstantiator::UnRegisterInstantiator("vtkCastToConcrete", vtkInstantiatorvtkCastToConcreteNew);
  vtkInstantiator::UnRegisterInstantiator("vtkCellArray", vtkInstantiatorvtkCellArrayNew);
  vtkInstantiator::UnRegisterInstantiator("vtkCellData", vtkInstantiatorvtkCellDataNew);
  vtkInstantiator::UnRegisterInstantiator("vtkCellLinks", vtkInstantiatorvtkCellLinksNew);
  vtkInstantiator::UnRegisterInstantiator("vtkCellLocator", vtkInstantiatorvtkCellLocatorNew);
  vtkInstantiator::UnRegisterInstantiator("vtkCellTypes", vtkInstantiatorvtkCellTypesNew);
  vtkInstantiator::UnRegisterInstantiator("vtkColorTransferFunction", vtkInstantiatorvtkColorTransferFunctionNew);
  vtkInstantiator::UnRegisterInstantiator("vtkCompositeDataPipeline", vtkInstantiatorvtkCompositeDataPipelineNew);
  vtkInstantiator::UnRegisterInstantiator("vtkCompositeDataSetAlgorithm", vtkInstantiatorvtkCompositeDataSetAlgorithmNew);
  vtkInstantiator::UnRegisterInstantiator("vtkComputingResources", vtkInstantiatorvtkComputingResourcesNew);
  vtkInstantiator::UnRegisterInstantiator("vtkCone", vtkInstantiatorvtkConeNew);
  vtkInstantiator::UnRegisterInstantiator("vtkConvexPointSet", vtkInstantiatorvtkConvexPointSetNew);
  vtkInstantiator::UnRegisterInstantiator("vtkCoordinate", vtkInstantiatorvtkCoordinateNew);
  vtkInstantiator::UnRegisterInstantiator("vtkCubicLine", vtkInstantiatorvtkCubicLineNew);
  vtkInstantiator::UnRegisterInstantiator("vtkCylinder", vtkInstantiatorvtkCylinderNew);
  vtkInstantiator::UnRegisterInstantiator("vtkDataObjectAlgorithm", vtkInstantiatorvtkDataObjectAlgorithmNew);
  vtkInstantiator::UnRegisterInstantiator("vtkDataObjectCollection", vtkInstantiatorvtkDataObjectCollectionNew);
  vtkInstantiator::UnRegisterInstantiator("vtkDataObject", vtkInstantiatorvtkDataObjectNew);
  vtkInstantiator::UnRegisterInstantiator("vtkDataObjectTypes", vtkInstantiatorvtkDataObjectTypesNew);
  vtkInstantiator::UnRegisterInstantiator("vtkDataSetAlgorithm", vtkInstantiatorvtkDataSetAlgorithmNew);
  vtkInstantiator::UnRegisterInstantiator("vtkDataSetAttributes", vtkInstantiatorvtkDataSetAttributesNew);
  vtkInstantiator::UnRegisterInstantiator("vtkDataSetCollection", vtkInstantiatorvtkDataSetCollectionNew);
  vtkInstantiator::UnRegisterInstantiator("vtkDemandDrivenPipeline", vtkInstantiatorvtkDemandDrivenPipelineNew);
  vtkInstantiator::UnRegisterInstantiator("vtkDirectedAcyclicGraph", vtkInstantiatorvtkDirectedAcyclicGraphNew);
  vtkInstantiator::UnRegisterInstantiator("vtkDirectedGraphAlgorithm", vtkInstantiatorvtkDirectedGraphAlgorithmNew);
  vtkInstantiator::UnRegisterInstantiator("vtkDirectedGraph", vtkInstantiatorvtkDirectedGraphNew);
  vtkInstantiator::UnRegisterInstantiator("vtkDiscretizableColorTransferFunction", vtkInstantiatorvtkDiscretizableColorTransferFunctionNew);
  vtkInstantiator::UnRegisterInstantiator("vtkEdgeListIterator", vtkInstantiatorvtkEdgeListIteratorNew);
  vtkInstantiator::UnRegisterInstantiator("vtkEmptyCell", vtkInstantiatorvtkEmptyCellNew);
  vtkInstantiator::UnRegisterInstantiator("vtkExecutionScheduler", vtkInstantiatorvtkExecutionSchedulerNew);
  vtkInstantiator::UnRegisterInstantiator("vtkExecutiveCollection", vtkInstantiatorvtkExecutiveCollectionNew);
  vtkInstantiator::UnRegisterInstantiator("vtkFieldData", vtkInstantiatorvtkFieldDataNew);
  vtkInstantiator::UnRegisterInstantiator("vtkGenericAttributeCollection", vtkInstantiatorvtkGenericAttributeCollectionNew);
  vtkInstantiator::UnRegisterInstantiator("vtkGenericCell", vtkInstantiatorvtkGenericCellNew);
  vtkInstantiator::UnRegisterInstantiator("vtkGenericEdgeTable", vtkInstantiatorvtkGenericEdgeTableNew);
  vtkInstantiator::UnRegisterInstantiator("vtkGenericInterpolatedVelocityField", vtkInstantiatorvtkGenericInterpolatedVelocityFieldNew);
  vtkInstantiator::UnRegisterInstantiator("vtkGeometricErrorMetric", vtkInstantiatorvtkGeometricErrorMetricNew);
  vtkInstantiator::UnRegisterInstantiator("vtkGraphAlgorithm", vtkInstantiatorvtkGraphAlgorithmNew);
  vtkInstantiator::UnRegisterInstantiator("vtkGraphEdge", vtkInstantiatorvtkGraphEdgeNew);
  vtkInstantiator::UnRegisterInstantiator("vtkGraphInternals", vtkInstantiatorvtkGraphInternalsNew);
  vtkInstantiator::UnRegisterInstantiator("vtkHexagonalPrism", vtkInstantiatorvtkHexagonalPrismNew);
  vtkInstantiator::UnRegisterInstantiator("vtkHexahedron", vtkInstantiatorvtkHexahedronNew);
  vtkInstantiator::UnRegisterInstantiator("vtkHierarchicalBoxDataIterator", vtkInstantiatorvtkHierarchicalBoxDataIteratorNew);
  vtkInstantiator::UnRegisterInstantiator("vtkHierarchicalBoxDataSetAlgorithm", vtkInstantiatorvtkHierarchicalBoxDataSetAlgorithmNew);
  vtkInstantiator::UnRegisterInstantiator("vtkHierarchicalBoxDataSet", vtkInstantiatorvtkHierarchicalBoxDataSetNew);
  vtkInstantiator::UnRegisterInstantiator("vtkHyperOctree", vtkInstantiatorvtkHyperOctreeNew);
  vtkInstantiator::UnRegisterInstantiator("vtkImageData", vtkInstantiatorvtkImageDataNew);
  vtkInstantiator::UnRegisterInstantiator("vtkImageToStructuredPoints", vtkInstantiatorvtkImageToStructuredPointsNew);
  vtkInstantiator::UnRegisterInstantiator("vtkImplicitBoolean", vtkInstantiatorvtkImplicitBooleanNew);
  vtkInstantiator::UnRegisterInstantiator("vtkImplicitDataSet", vtkInstantiatorvtkImplicitDataSetNew);
  vtkInstantiator::UnRegisterInstantiator("vtkImplicitHalo", vtkInstantiatorvtkImplicitHaloNew);
  vtkInstantiator::UnRegisterInstantiator("vtkImplicitSelectionLoop", vtkInstantiatorvtkImplicitSelectionLoopNew);
  vtkInstantiator::UnRegisterInstantiator("vtkImplicitSum", vtkInstantiatorvtkImplicitSumNew);
  vtkInstantiator::UnRegisterInstantiator("vtkImplicitVolume", vtkInstantiatorvtkImplicitVolumeNew);
  vtkInstantiator::UnRegisterInstantiator("vtkImplicitWindowFunction", vtkInstantiatorvtkImplicitWindowFunctionNew);
  vtkInstantiator::UnRegisterInstantiator("vtkIncrementalOctreeNode", vtkInstantiatorvtkIncrementalOctreeNodeNew);
  vtkInstantiator::UnRegisterInstantiator("vtkIncrementalOctreePointLocator", vtkInstantiatorvtkIncrementalOctreePointLocatorNew);
  vtkInstantiator::UnRegisterInstantiator("vtkInEdgeIterator", vtkInstantiatorvtkInEdgeIteratorNew);
  vtkInstantiator::UnRegisterInstantiator("vtkInterpolatedVelocityField", vtkInstantiatorvtkInterpolatedVelocityFieldNew);
  vtkInstantiator::UnRegisterInstantiator("vtkKdNode", vtkInstantiatorvtkKdNodeNew);
  vtkInstantiator::UnRegisterInstantiator("vtkKdTree", vtkInstantiatorvtkKdTreeNew);
  vtkInstantiator::UnRegisterInstantiator("vtkKdTreePointLocator", vtkInstantiatorvtkKdTreePointLocatorNew);
  vtkInstantiator::UnRegisterInstantiator("vtkKochanekSpline", vtkInstantiatorvtkKochanekSplineNew);
  vtkInstantiator::UnRegisterInstantiator("vtkLine", vtkInstantiatorvtkLineNew);
  vtkInstantiator::UnRegisterInstantiator("vtkMeanValueCoordinatesInterpolator", vtkInstantiatorvtkMeanValueCoordinatesInterpolatorNew);
  vtkInstantiator::UnRegisterInstantiator("vtkMergePoints", vtkInstantiatorvtkMergePointsNew);
  vtkInstantiator::UnRegisterInstantiator("vtkMultiBlockDataSetAlgorithm", vtkInstantiatorvtkMultiBlockDataSetAlgorithmNew);
  vtkInstantiator::UnRegisterInstantiator("vtkMultiBlockDataSet", vtkInstantiatorvtkMultiBlockDataSetNew);
  vtkInstantiator::UnRegisterInstantiator("vtkMultiPieceDataSet", vtkInstantiatorvtkMultiPieceDataSetNew);
  vtkInstantiator::UnRegisterInstantiator("vtkMutableDirectedGraph", vtkInstantiatorvtkMutableDirectedGraphNew);
  vtkInstantiator::UnRegisterInstantiator("vtkMutableUndirectedGraph", vtkInstantiatorvtkMutableUndirectedGraphNew);
  vtkInstantiator::UnRegisterInstantiator("vtkNonMergingPointLocator", vtkInstantiatorvtkNonMergingPointLocatorNew);
  vtkInstantiator::UnRegisterInstantiator("vtkOctreePointLocator", vtkInstantiatorvtkOctreePointLocatorNew);
  vtkInstantiator::UnRegisterInstantiator("vtkOctreePointLocatorNode", vtkInstantiatorvtkOctreePointLocatorNodeNew);
  vtkInstantiator::UnRegisterInstantiator("vtkOrderedTriangulator", vtkInstantiatorvtkOrderedTriangulatorNew);
  vtkInstantiator::UnRegisterInstantiator("vtkOutEdgeIterator", vtkInstantiatorvtkOutEdgeIteratorNew);
  vtkInstantiator::UnRegisterInstantiator("vtkParametricSpline", vtkInstantiatorvtkParametricSplineNew);
  vtkInstantiator::UnRegisterInstantiator("vtkPassInputTypeAlgorithm", vtkInstantiatorvtkPassInputTypeAlgorithmNew);
  vtkInstantiator::UnRegisterInstantiator("vtkPentagonalPrism", vtkInstantiatorvtkPentagonalPrismNew);
  vtkInstantiator::UnRegisterInstantiator("vtkPerlinNoise", vtkInstantiatorvtkPerlinNoiseNew);
  vtkInstantiator::UnRegisterInstantiator("vtkPiecewiseFunctionAlgorithm", vtkInstantiatorvtkPiecewiseFunctionAlgorithmNew);
  vtkInstantiator::UnRegisterInstantiator("vtkPiecewiseFunction", vtkInstantiatorvtkPiecewiseFunctionNew);
  vtkInstantiator::UnRegisterInstantiator("vtkPiecewiseFunctionShiftScale", vtkInstantiatorvtkPiecewiseFunctionShiftScaleNew);
  vtkInstantiator::UnRegisterInstantiator("vtkPixel", vtkInstantiatorvtkPixelNew);
  vtkInstantiator::UnRegisterInstantiator("vtkPlanesIntersection", vtkInstantiatorvtkPlanesIntersectionNew);
  vtkInstantiator::UnRegisterInstantiator("vtkPointData", vtkInstantiatorvtkPointDataNew);
  vtkInstantiator::UnRegisterInstantiator("vtkPointLocator", vtkInstantiatorvtkPointLocatorNew);
  vtkInstantiator::UnRegisterInstantiator("vtkPointSetAlgorithm", vtkInstantiatorvtkPointSetAlgorithmNew);
  vtkInstantiator::UnRegisterInstantiator("vtkPointsProjectedHull", vtkInstantiatorvtkPointsProjectedHullNew);
  vtkInstantiator::UnRegisterInstantiator("vtkPolyDataAlgorithm", vtkInstantiatorvtkPolyDataAlgorithmNew);
  vtkInstantiator::UnRegisterInstantiator("vtkPolyDataCollection", vtkInstantiatorvtkPolyDataCollectionNew);
  vtkInstantiator::UnRegisterInstantiator("vtkPolyData", vtkInstantiatorvtkPolyDataNew);
  vtkInstantiator::UnRegisterInstantiator("vtkPolygon", vtkInstantiatorvtkPolygonNew);
  vtkInstantiator::UnRegisterInstantiator("vtkPolyhedron", vtkInstantiatorvtkPolyhedronNew);
  vtkInstantiator::UnRegisterInstantiator("vtkPolyLine", vtkInstantiatorvtkPolyLineNew);
  vtkInstantiator::UnRegisterInstantiator("vtkPolyVertex", vtkInstantiatorvtkPolyVertexNew);
  vtkInstantiator::UnRegisterInstantiator("vtkPropAssembly", vtkInstantiatorvtkPropAssemblyNew);
  vtkInstantiator::UnRegisterInstantiator("vtkPyramid", vtkInstantiatorvtkPyramidNew);
  vtkInstantiator::UnRegisterInstantiator("vtkQuad", vtkInstantiatorvtkQuadNew);
  vtkInstantiator::UnRegisterInstantiator("vtkQuadraticEdge", vtkInstantiatorvtkQuadraticEdgeNew);
  vtkInstantiator::UnRegisterInstantiator("vtkQuadraticHexahedron", vtkInstantiatorvtkQuadraticHexahedronNew);
  vtkInstantiator::UnRegisterInstantiator("vtkQuadraticLinearQuad", vtkInstantiatorvtkQuadraticLinearQuadNew);
  vtkInstantiator::UnRegisterInstantiator("vtkQuadraticLinearWedge", vtkInstantiatorvtkQuadraticLinearWedgeNew);
  vtkInstantiator::UnRegisterInstantiator("vtkQuadraticPyramid", vtkInstantiatorvtkQuadraticPyramidNew);
  vtkInstantiator::UnRegisterInstantiator("vtkQuadraticQuad", vtkInstantiatorvtkQuadraticQuadNew);
  vtkInstantiator::UnRegisterInstantiator("vtkQuadraticTetra", vtkInstantiatorvtkQuadraticTetraNew);
  vtkInstantiator::UnRegisterInstantiator("vtkQuadraticTriangle", vtkInstantiatorvtkQuadraticTriangleNew);
  vtkInstantiator::UnRegisterInstantiator("vtkQuadraticWedge", vtkInstantiatorvtkQuadraticWedgeNew);
  vtkInstantiator::UnRegisterInstantiator("vtkRectilinearGridAlgorithm", vtkInstantiatorvtkRectilinearGridAlgorithmNew);
  vtkInstantiator::UnRegisterInstantiator("vtkRectilinearGrid", vtkInstantiatorvtkRectilinearGridNew);
  vtkInstantiator::UnRegisterInstantiator("vtkReebGraph", vtkInstantiatorvtkReebGraphNew);
  vtkInstantiator::UnRegisterInstantiator("vtkReebGraphSimplificationMetric", vtkInstantiatorvtkReebGraphSimplificationMetricNew);
  vtkInstantiator::UnRegisterInstantiator("vtkSelectionAlgorithm", vtkInstantiatorvtkSelectionAlgorithmNew);
  vtkInstantiator::UnRegisterInstantiator("vtkSelection", vtkInstantiatorvtkSelectionNew);
  vtkInstantiator::UnRegisterInstantiator("vtkSelectionNode", vtkInstantiatorvtkSelectionNodeNew);
  vtkInstantiator::UnRegisterInstantiator("vtkSimpleCellTessellator", vtkInstantiatorvtkSimpleCellTessellatorNew);
  vtkInstantiator::UnRegisterInstantiator("vtkSimpleScalarTree", vtkInstantiatorvtkSimpleScalarTreeNew);
  vtkInstantiator::UnRegisterInstantiator("vtkSmoothErrorMetric", vtkInstantiatorvtkSmoothErrorMetricNew);
  vtkInstantiator::UnRegisterInstantiator("vtkSphere", vtkInstantiatorvtkSphereNew);
  vtkInstantiator::UnRegisterInstantiator("vtkStreamingDemandDrivenPipeline", vtkInstantiatorvtkStreamingDemandDrivenPipelineNew);
  vtkInstantiator::UnRegisterInstantiator("vtkStructuredGridAlgorithm", vtkInstantiatorvtkStructuredGridAlgorithmNew);
  vtkInstantiator::UnRegisterInstantiator("vtkStructuredGrid", vtkInstantiatorvtkStructuredGridNew);
  vtkInstantiator::UnRegisterInstantiator("vtkStructuredPointsCollection", vtkInstantiatorvtkStructuredPointsCollectionNew);
  vtkInstantiator::UnRegisterInstantiator("vtkStructuredPoints", vtkInstantiatorvtkStructuredPointsNew);
  vtkInstantiator::UnRegisterInstantiator("vtkSuperquadric", vtkInstantiatorvtkSuperquadricNew);
  vtkInstantiator::UnRegisterInstantiator("vtkTableAlgorithm", vtkInstantiatorvtkTableAlgorithmNew);
  vtkInstantiator::UnRegisterInstantiator("vtkTable", vtkInstantiatorvtkTableNew);
  vtkInstantiator::UnRegisterInstantiator("vtkTemporalDataSetAlgorithm", vtkInstantiatorvtkTemporalDataSetAlgorithmNew);
  vtkInstantiator::UnRegisterInstantiator("vtkTemporalDataSet", vtkInstantiatorvtkTemporalDataSetNew);
  vtkInstantiator::UnRegisterInstantiator("vtkTetra", vtkInstantiatorvtkTetraNew);
  vtkInstantiator::UnRegisterInstantiator("vtkThreadedStreamingPipeline", vtkInstantiatorvtkThreadedStreamingPipelineNew);
  vtkInstantiator::UnRegisterInstantiator("vtkTreeAlgorithm", vtkInstantiatorvtkTreeAlgorithmNew);
  vtkInstantiator::UnRegisterInstantiator("vtkTree", vtkInstantiatorvtkTreeNew);
  vtkInstantiator::UnRegisterInstantiator("vtkTreeBFSIterator", vtkInstantiatorvtkTreeBFSIteratorNew);
  vtkInstantiator::UnRegisterInstantiator("vtkTreeDFSIterator", vtkInstantiatorvtkTreeDFSIteratorNew);
  vtkInstantiator::UnRegisterInstantiator("vtkTriangle", vtkInstantiatorvtkTriangleNew);
  vtkInstantiator::UnRegisterInstantiator("vtkTriangleStrip", vtkInstantiatorvtkTriangleStripNew);
  vtkInstantiator::UnRegisterInstantiator("vtkTriQuadraticHexahedron", vtkInstantiatorvtkTriQuadraticHexahedronNew);
  vtkInstantiator::UnRegisterInstantiator("vtkTrivialProducer", vtkInstantiatorvtkTrivialProducerNew);
  vtkInstantiator::UnRegisterInstantiator("vtkUndirectedGraphAlgorithm", vtkInstantiatorvtkUndirectedGraphAlgorithmNew);
  vtkInstantiator::UnRegisterInstantiator("vtkUndirectedGraph", vtkInstantiatorvtkUndirectedGraphNew);
  vtkInstantiator::UnRegisterInstantiator("vtkUniformGrid", vtkInstantiatorvtkUniformGridNew);
  vtkInstantiator::UnRegisterInstantiator("vtkUnstructuredGridAlgorithm", vtkInstantiatorvtkUnstructuredGridAlgorithmNew);
  vtkInstantiator::UnRegisterInstantiator("vtkUnstructuredGrid", vtkInstantiatorvtkUnstructuredGridNew);
  vtkInstantiator::UnRegisterInstantiator("vtkVertex", vtkInstantiatorvtkVertexNew);
  vtkInstantiator::UnRegisterInstantiator("vtkVertexListIterator", vtkInstantiatorvtkVertexListIteratorNew);
  vtkInstantiator::UnRegisterInstantiator("vtkViewDependentErrorMetric", vtkInstantiatorvtkViewDependentErrorMetricNew);
  vtkInstantiator::UnRegisterInstantiator("vtkVoxel", vtkInstantiatorvtkVoxelNew);
  vtkInstantiator::UnRegisterInstantiator("vtkWedge", vtkInstantiatorvtkWedgeNew);
  vtkInstantiator::UnRegisterInstantiator("vtkArrayData", vtkInstantiatorvtkArrayDataNew);
  vtkInstantiator::UnRegisterInstantiator("vtkArrayDataAlgorithm", vtkInstantiatorvtkArrayDataAlgorithmNew);

  
}

vtkFilteringInstantiator::vtkFilteringInstantiator()
{
  if(++vtkFilteringInstantiator::Count == 1)
    { 
    vtkFilteringInstantiator::ClassInitialize(); 
    }
}

vtkFilteringInstantiator::~vtkFilteringInstantiator()
{
  if(--vtkFilteringInstantiator::Count == 0)
    { 
    vtkFilteringInstantiator::ClassFinalize(); 
    }
}

// Number of translation units that include this class's header.
// Purposely not initialized.  Default is static initialization to 0.
unsigned int vtkFilteringInstantiator::Count;
