# CMake generated Testfile for 
# Source directory: /home/chris/crimson/petsc/vtk/vtk-v5.8.0/Common/Testing/Cxx
# Build directory: /home/chris/crimson/petsc/vtk/vtk-v5.8.0/Common/Testing/Cxx
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(TestObjectFactory "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/bin/CommonCxxTests" "TestObjectFactory")
add_test(otherArrays "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/bin/CommonCxxTests" "otherArrays")
add_test(otherTimerLog "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/bin/CommonCxxTests" "otherTimerLog")
add_test(otherLookupTable "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/bin/CommonCxxTests" "otherLookupTable")
add_test(otherLookupTableWithEnabling "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/bin/CommonCxxTests" "otherLookupTableWithEnabling")
add_test(otherByteSwap "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/bin/CommonCxxTests" "otherByteSwap")
add_test(otherStringArray "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/bin/CommonCxxTests" "otherStringArray")
add_test(TestAmoebaMinimizer "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/bin/CommonCxxTests" "TestAmoebaMinimizer")
add_test(TestArrayLookup "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/bin/CommonCxxTests" "TestArrayLookup")
add_test(TestConditionVariable "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/bin/CommonCxxTests" "TestConditionVariable")
set_tests_properties(TestConditionVariable PROPERTIES  RUN_SERIAL "ON")
add_test(TestGarbageCollector "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/bin/CommonCxxTests" "TestGarbageCollector")
add_test(TestDataArray "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/bin/CommonCxxTests" "TestDataArray")
add_test(TestDataArrayComponentNames "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/bin/CommonCxxTests" "TestDataArrayComponentNames")
add_test(TestDirectory "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/bin/CommonCxxTests" "TestDirectory")
add_test(TestFastNumericConversion "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/bin/CommonCxxTests" "TestFastNumericConversion")
add_test(TestMath "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/bin/CommonCxxTests" "TestMath")
add_test(TestMatrix3x3 "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/bin/CommonCxxTests" "TestMatrix3x3")
add_test(TestMinimalStandardRandomSequence "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/bin/CommonCxxTests" "TestMinimalStandardRandomSequence")
add_test(TestNew "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/bin/CommonCxxTests" "TestNew")
add_test(TestObservers "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/bin/CommonCxxTests" "TestObservers")
add_test(TestPolynomialSolversUnivariate "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/bin/CommonCxxTests" "TestPolynomialSolversUnivariate")
add_test(TestSmartPointer "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/bin/CommonCxxTests" "TestSmartPointer")
add_test(TestSortDataArray "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/bin/CommonCxxTests" "TestSortDataArray")
add_test(TestUnicodeStringAPI "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/bin/CommonCxxTests" "TestUnicodeStringAPI")
add_test(TestUnicodeStringArrayAPI "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/bin/CommonCxxTests" "TestUnicodeStringArrayAPI")
add_test(TestVariantComparison "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/bin/CommonCxxTests" "TestVariantComparison")
add_test(TestWeakPointer "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/bin/CommonCxxTests" "TestWeakPointer")
add_test(TestSystemInformation "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/bin/CommonCxxTests" "TestSystemInformation")
add_test(TestCxxFeatures "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/bin/TestCxxFeatures")
add_test(TestInstantiator "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/bin/TestInstantiator")
add_test(Array-TestArrayAPI "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/bin/ArrayCxxTests" "TestArrayAPI")
add_test(Array-TestArrayAPIConvenience "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/bin/ArrayCxxTests" "TestArrayAPIConvenience")
add_test(Array-TestArrayAPIDense "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/bin/ArrayCxxTests" "TestArrayAPIDense")
add_test(Array-TestArrayAPISparse "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/bin/ArrayCxxTests" "TestArrayAPISparse")
add_test(Array-TestArrayBool "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/bin/ArrayCxxTests" "TestArrayBool")
add_test(Array-TestArrayInterpolationDense "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/bin/ArrayCxxTests" "TestArrayInterpolationDense")
add_test(Array-TestArrayNullValues "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/bin/ArrayCxxTests" "TestArrayNullValues")
add_test(Array-TestArrayExtents "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/bin/ArrayCxxTests" "TestArrayExtents")
add_test(Array-TestArrayUserTypes "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/bin/ArrayCxxTests" "TestArrayUserTypes")
add_test(Array-TestArrayVariants "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/bin/ArrayCxxTests" "TestArrayVariants")
add_test(Array-TestArraySize "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/bin/ArrayCxxTests" "TestArraySize")
add_test(Array-TestSparseArrayValidation "/home/chris/crimson/petsc/vtk/vtk-v5.8.0/bin/ArrayCxxTests" "TestSparseArrayValidation")
