#include "vtkInfovisInstantiator.h"
  
extern vtkObject* vtkInstantiatorvtkAddMembershipArrayNew();
extern vtkObject* vtkInstantiatorvtkAppendPointsNew();
extern vtkObject* vtkInstantiatorvtkApplyColorsNew();
extern vtkObject* vtkInstantiatorvtkApplyIconsNew();
extern vtkObject* vtkInstantiatorvtkArcParallelEdgeStrategyNew();
extern vtkObject* vtkInstantiatorvtkAreaLayoutNew();
extern vtkObject* vtkInstantiatorvtkAssignCoordinatesNew();
extern vtkObject* vtkInstantiatorvtkAssignCoordinatesLayoutStrategyNew();
extern vtkObject* vtkInstantiatorvtkBivariateLinearTableThresholdNew();
extern vtkObject* vtkInstantiatorvtkBoxLayoutStrategyNew();
extern vtkObject* vtkInstantiatorvtkChacoGraphReaderNew();
extern vtkObject* vtkInstantiatorvtkCircularLayoutStrategyNew();
extern vtkObject* vtkInstantiatorvtkClustering2DLayoutStrategyNew();
extern vtkObject* vtkInstantiatorvtkCollapseGraphNew();
extern vtkObject* vtkInstantiatorvtkCollapseVerticesByArrayNew();
extern vtkObject* vtkInstantiatorvtkCommunity2DLayoutStrategyNew();
extern vtkObject* vtkInstantiatorvtkConeLayoutStrategyNew();
extern vtkObject* vtkInstantiatorvtkConstrained2DLayoutStrategyNew();
extern vtkObject* vtkInstantiatorvtkContingencyStatisticsNew();
extern vtkObject* vtkInstantiatorvtkCorrelativeStatisticsNew();
extern vtkObject* vtkInstantiatorvtkCosmicTreeLayoutStrategyNew();
extern vtkObject* vtkInstantiatorvtkDataObjectToTableNew();
extern vtkObject* vtkInstantiatorvtkDelimitedTextReaderNew();
extern vtkObject* vtkInstantiatorvtkDescriptiveStatisticsNew();
extern vtkObject* vtkInstantiatorvtkDIMACSGraphReaderNew();
extern vtkObject* vtkInstantiatorvtkDIMACSGraphWriterNew();
extern vtkObject* vtkInstantiatorvtkEdgeCentersNew();
extern vtkObject* vtkInstantiatorvtkEdgeLayoutNew();
extern vtkObject* vtkInstantiatorvtkExpandSelectedGraphNew();
extern vtkObject* vtkInstantiatorvtkExtractSelectedGraphNew();
extern vtkObject* vtkInstantiatorvtkFast2DLayoutStrategyNew();
extern vtkObject* vtkInstantiatorvtkFixedWidthTextReaderNew();
extern vtkObject* vtkInstantiatorvtkForceDirectedLayoutStrategyNew();
extern vtkObject* vtkInstantiatorvtkGenerateIndexArrayNew();
extern vtkObject* vtkInstantiatorvtkGeoEdgeStrategyNew();
extern vtkObject* vtkInstantiatorvtkGeoMathNew();
extern vtkObject* vtkInstantiatorvtkGraphHierarchicalBundleNew();
extern vtkObject* vtkInstantiatorvtkGraphHierarchicalBundleEdgesNew();
extern vtkObject* vtkInstantiatorvtkGraphLayoutNew();
extern vtkObject* vtkInstantiatorvtkGroupLeafVerticesNew();
extern vtkObject* vtkInstantiatorvtkISIReaderNew();
extern vtkObject* vtkInstantiatorvtkKMeansDistanceFunctorNew();
extern vtkObject* vtkInstantiatorvtkKMeansDistanceFunctorCalculatorNew();
extern vtkObject* vtkInstantiatorvtkKMeansStatisticsNew();
extern vtkObject* vtkInstantiatorvtkMergeColumnsNew();
extern vtkObject* vtkInstantiatorvtkMergeGraphsNew();
extern vtkObject* vtkInstantiatorvtkMergeTablesNew();
extern vtkObject* vtkInstantiatorvtkMultiCorrelativeStatisticsNew();
extern vtkObject* vtkInstantiatorvtkMutableGraphHelperNew();
extern vtkObject* vtkInstantiatorvtkNetworkHierarchyNew();
extern vtkObject* vtkInstantiatorvtkOrderStatisticsNew();
extern vtkObject* vtkInstantiatorvtkPassArraysNew();
extern vtkObject* vtkInstantiatorvtkPassThroughNew();
extern vtkObject* vtkInstantiatorvtkPassThroughEdgeStrategyNew();
extern vtkObject* vtkInstantiatorvtkPassThroughLayoutStrategyNew();
extern vtkObject* vtkInstantiatorvtkPerturbCoincidentVerticesNew();
extern vtkObject* vtkInstantiatorvtkPCAStatisticsNew();
extern vtkObject* vtkInstantiatorvtkPruneTreeFilterNew();
extern vtkObject* vtkInstantiatorvtkRISReaderNew();
extern vtkObject* vtkInstantiatorvtkRandomGraphSourceNew();
extern vtkObject* vtkInstantiatorvtkRandomLayoutStrategyNew();
extern vtkObject* vtkInstantiatorvtkRemoveIsolatedVerticesNew();
extern vtkObject* vtkInstantiatorvtkRemoveHiddenDataNew();
extern vtkObject* vtkInstantiatorvtkSCurveSplineNew();
extern vtkObject* vtkInstantiatorvtkSimple2DLayoutStrategyNew();
extern vtkObject* vtkInstantiatorvtkSimple3DCirclesStrategyNew();
extern vtkObject* vtkInstantiatorvtkSliceAndDiceLayoutStrategyNew();
extern vtkObject* vtkInstantiatorvtkSplineGraphEdgesNew();
extern vtkObject* vtkInstantiatorvtkSplitColumnComponentsNew();
extern vtkObject* vtkInstantiatorvtkSquarifyLayoutStrategyNew();
extern vtkObject* vtkInstantiatorvtkSpanTreeLayoutStrategyNew();
extern vtkObject* vtkInstantiatorvtkStackedTreeLayoutStrategyNew();
extern vtkObject* vtkInstantiatorvtkStrahlerMetricNew();
extern vtkObject* vtkInstantiatorvtkStreamGraphNew();
extern vtkObject* vtkInstantiatorvtkStreamingStatisticsNew();
extern vtkObject* vtkInstantiatorvtkStringToCategoryNew();
extern vtkObject* vtkInstantiatorvtkStringToNumericNew();
extern vtkObject* vtkInstantiatorvtkTableToGraphNew();
extern vtkObject* vtkInstantiatorvtkTableToTreeFilterNew();
extern vtkObject* vtkInstantiatorvtkThresholdGraphNew();
extern vtkObject* vtkInstantiatorvtkThresholdTableNew();
extern vtkObject* vtkInstantiatorvtkTransferAttributesNew();
extern vtkObject* vtkInstantiatorvtkTreeFieldAggregatorNew();
extern vtkObject* vtkInstantiatorvtkTreeLayoutStrategyNew();
extern vtkObject* vtkInstantiatorvtkTreeOrbitLayoutStrategyNew();
extern vtkObject* vtkInstantiatorvtkTreeLevelsFilterNew();
extern vtkObject* vtkInstantiatorvtkTreeMapLayoutNew();
extern vtkObject* vtkInstantiatorvtkTreeMapToPolyDataNew();
extern vtkObject* vtkInstantiatorvtkTreeRingToPolyDataNew();
extern vtkObject* vtkInstantiatorvtkTulipReaderNew();
extern vtkObject* vtkInstantiatorvtkAttributeClustering2DLayoutStrategyNew();
extern vtkObject* vtkInstantiatorvtkVertexDegreeNew();
extern vtkObject* vtkInstantiatorvtkXGMLReaderNew();
extern vtkObject* vtkInstantiatorvtkXMLTreeReaderNew();
extern vtkObject* vtkInstantiatorvtkAdjacencyMatrixToEdgeTableNew();
extern vtkObject* vtkInstantiatorvtkArrayNormNew();
extern vtkObject* vtkInstantiatorvtkArrayToTableNew();
extern vtkObject* vtkInstantiatorvtkComputeHistogram2DOutliersNew();
extern vtkObject* vtkInstantiatorvtkDiagonalMatrixSourceNew();
extern vtkObject* vtkInstantiatorvtkDotProductSimilarityNew();
extern vtkObject* vtkInstantiatorvtkExtractArrayNew();
extern vtkObject* vtkInstantiatorvtkExtractHistogram2DNew();
extern vtkObject* vtkInstantiatorvtkMatricizeArrayNew();
extern vtkObject* vtkInstantiatorvtkNormalizeMatrixVectorsNew();
extern vtkObject* vtkInstantiatorvtkPairwiseExtractHistogram2DNew();
extern vtkObject* vtkInstantiatorvtkSparseArrayToTableNew();
extern vtkObject* vtkInstantiatorvtkTableToArrayNew();
extern vtkObject* vtkInstantiatorvtkTableToSparseArrayNew();
extern vtkObject* vtkInstantiatorvtkTransposeMatrixNew();
extern vtkObject* vtkInstantiatorvtkSQLDatabaseGraphSourceNew();
extern vtkObject* vtkInstantiatorvtkSQLDatabaseTableSourceNew();
extern vtkObject* vtkInstantiatorvtkSQLGraphReaderNew();
extern vtkObject* vtkInstantiatorvtkStringToTimePointNew();
extern vtkObject* vtkInstantiatorvtkTimePointToStringNew();


  
void vtkInfovisInstantiator::ClassInitialize()
{
  
  vtkInstantiator::RegisterInstantiator("vtkAddMembershipArray", vtkInstantiatorvtkAddMembershipArrayNew);
  vtkInstantiator::RegisterInstantiator("vtkAppendPoints", vtkInstantiatorvtkAppendPointsNew);
  vtkInstantiator::RegisterInstantiator("vtkApplyColors", vtkInstantiatorvtkApplyColorsNew);
  vtkInstantiator::RegisterInstantiator("vtkApplyIcons", vtkInstantiatorvtkApplyIconsNew);
  vtkInstantiator::RegisterInstantiator("vtkArcParallelEdgeStrategy", vtkInstantiatorvtkArcParallelEdgeStrategyNew);
  vtkInstantiator::RegisterInstantiator("vtkAreaLayout", vtkInstantiatorvtkAreaLayoutNew);
  vtkInstantiator::RegisterInstantiator("vtkAssignCoordinates", vtkInstantiatorvtkAssignCoordinatesNew);
  vtkInstantiator::RegisterInstantiator("vtkAssignCoordinatesLayoutStrategy", vtkInstantiatorvtkAssignCoordinatesLayoutStrategyNew);
  vtkInstantiator::RegisterInstantiator("vtkBivariateLinearTableThreshold", vtkInstantiatorvtkBivariateLinearTableThresholdNew);
  vtkInstantiator::RegisterInstantiator("vtkBoxLayoutStrategy", vtkInstantiatorvtkBoxLayoutStrategyNew);
  vtkInstantiator::RegisterInstantiator("vtkChacoGraphReader", vtkInstantiatorvtkChacoGraphReaderNew);
  vtkInstantiator::RegisterInstantiator("vtkCircularLayoutStrategy", vtkInstantiatorvtkCircularLayoutStrategyNew);
  vtkInstantiator::RegisterInstantiator("vtkClustering2DLayoutStrategy", vtkInstantiatorvtkClustering2DLayoutStrategyNew);
  vtkInstantiator::RegisterInstantiator("vtkCollapseGraph", vtkInstantiatorvtkCollapseGraphNew);
  vtkInstantiator::RegisterInstantiator("vtkCollapseVerticesByArray", vtkInstantiatorvtkCollapseVerticesByArrayNew);
  vtkInstantiator::RegisterInstantiator("vtkCommunity2DLayoutStrategy", vtkInstantiatorvtkCommunity2DLayoutStrategyNew);
  vtkInstantiator::RegisterInstantiator("vtkConeLayoutStrategy", vtkInstantiatorvtkConeLayoutStrategyNew);
  vtkInstantiator::RegisterInstantiator("vtkConstrained2DLayoutStrategy", vtkInstantiatorvtkConstrained2DLayoutStrategyNew);
  vtkInstantiator::RegisterInstantiator("vtkContingencyStatistics", vtkInstantiatorvtkContingencyStatisticsNew);
  vtkInstantiator::RegisterInstantiator("vtkCorrelativeStatistics", vtkInstantiatorvtkCorrelativeStatisticsNew);
  vtkInstantiator::RegisterInstantiator("vtkCosmicTreeLayoutStrategy", vtkInstantiatorvtkCosmicTreeLayoutStrategyNew);
  vtkInstantiator::RegisterInstantiator("vtkDataObjectToTable", vtkInstantiatorvtkDataObjectToTableNew);
  vtkInstantiator::RegisterInstantiator("vtkDelimitedTextReader", vtkInstantiatorvtkDelimitedTextReaderNew);
  vtkInstantiator::RegisterInstantiator("vtkDescriptiveStatistics", vtkInstantiatorvtkDescriptiveStatisticsNew);
  vtkInstantiator::RegisterInstantiator("vtkDIMACSGraphReader", vtkInstantiatorvtkDIMACSGraphReaderNew);
  vtkInstantiator::RegisterInstantiator("vtkDIMACSGraphWriter", vtkInstantiatorvtkDIMACSGraphWriterNew);
  vtkInstantiator::RegisterInstantiator("vtkEdgeCenters", vtkInstantiatorvtkEdgeCentersNew);
  vtkInstantiator::RegisterInstantiator("vtkEdgeLayout", vtkInstantiatorvtkEdgeLayoutNew);
  vtkInstantiator::RegisterInstantiator("vtkExpandSelectedGraph", vtkInstantiatorvtkExpandSelectedGraphNew);
  vtkInstantiator::RegisterInstantiator("vtkExtractSelectedGraph", vtkInstantiatorvtkExtractSelectedGraphNew);
  vtkInstantiator::RegisterInstantiator("vtkFast2DLayoutStrategy", vtkInstantiatorvtkFast2DLayoutStrategyNew);
  vtkInstantiator::RegisterInstantiator("vtkFixedWidthTextReader", vtkInstantiatorvtkFixedWidthTextReaderNew);
  vtkInstantiator::RegisterInstantiator("vtkForceDirectedLayoutStrategy", vtkInstantiatorvtkForceDirectedLayoutStrategyNew);
  vtkInstantiator::RegisterInstantiator("vtkGenerateIndexArray", vtkInstantiatorvtkGenerateIndexArrayNew);
  vtkInstantiator::RegisterInstantiator("vtkGeoEdgeStrategy", vtkInstantiatorvtkGeoEdgeStrategyNew);
  vtkInstantiator::RegisterInstantiator("vtkGeoMath", vtkInstantiatorvtkGeoMathNew);
  vtkInstantiator::RegisterInstantiator("vtkGraphHierarchicalBundle", vtkInstantiatorvtkGraphHierarchicalBundleNew);
  vtkInstantiator::RegisterInstantiator("vtkGraphHierarchicalBundleEdges", vtkInstantiatorvtkGraphHierarchicalBundleEdgesNew);
  vtkInstantiator::RegisterInstantiator("vtkGraphLayout", vtkInstantiatorvtkGraphLayoutNew);
  vtkInstantiator::RegisterInstantiator("vtkGroupLeafVertices", vtkInstantiatorvtkGroupLeafVerticesNew);
  vtkInstantiator::RegisterInstantiator("vtkISIReader", vtkInstantiatorvtkISIReaderNew);
  vtkInstantiator::RegisterInstantiator("vtkKMeansDistanceFunctor", vtkInstantiatorvtkKMeansDistanceFunctorNew);
  vtkInstantiator::RegisterInstantiator("vtkKMeansDistanceFunctorCalculator", vtkInstantiatorvtkKMeansDistanceFunctorCalculatorNew);
  vtkInstantiator::RegisterInstantiator("vtkKMeansStatistics", vtkInstantiatorvtkKMeansStatisticsNew);
  vtkInstantiator::RegisterInstantiator("vtkMergeColumns", vtkInstantiatorvtkMergeColumnsNew);
  vtkInstantiator::RegisterInstantiator("vtkMergeGraphs", vtkInstantiatorvtkMergeGraphsNew);
  vtkInstantiator::RegisterInstantiator("vtkMergeTables", vtkInstantiatorvtkMergeTablesNew);
  vtkInstantiator::RegisterInstantiator("vtkMultiCorrelativeStatistics", vtkInstantiatorvtkMultiCorrelativeStatisticsNew);
  vtkInstantiator::RegisterInstantiator("vtkMutableGraphHelper", vtkInstantiatorvtkMutableGraphHelperNew);
  vtkInstantiator::RegisterInstantiator("vtkNetworkHierarchy", vtkInstantiatorvtkNetworkHierarchyNew);
  vtkInstantiator::RegisterInstantiator("vtkOrderStatistics", vtkInstantiatorvtkOrderStatisticsNew);
  vtkInstantiator::RegisterInstantiator("vtkPassArrays", vtkInstantiatorvtkPassArraysNew);
  vtkInstantiator::RegisterInstantiator("vtkPassThrough", vtkInstantiatorvtkPassThroughNew);
  vtkInstantiator::RegisterInstantiator("vtkPassThroughEdgeStrategy", vtkInstantiatorvtkPassThroughEdgeStrategyNew);
  vtkInstantiator::RegisterInstantiator("vtkPassThroughLayoutStrategy", vtkInstantiatorvtkPassThroughLayoutStrategyNew);
  vtkInstantiator::RegisterInstantiator("vtkPerturbCoincidentVertices", vtkInstantiatorvtkPerturbCoincidentVerticesNew);
  vtkInstantiator::RegisterInstantiator("vtkPCAStatistics", vtkInstantiatorvtkPCAStatisticsNew);
  vtkInstantiator::RegisterInstantiator("vtkPruneTreeFilter", vtkInstantiatorvtkPruneTreeFilterNew);
  vtkInstantiator::RegisterInstantiator("vtkRISReader", vtkInstantiatorvtkRISReaderNew);
  vtkInstantiator::RegisterInstantiator("vtkRandomGraphSource", vtkInstantiatorvtkRandomGraphSourceNew);
  vtkInstantiator::RegisterInstantiator("vtkRandomLayoutStrategy", vtkInstantiatorvtkRandomLayoutStrategyNew);
  vtkInstantiator::RegisterInstantiator("vtkRemoveIsolatedVertices", vtkInstantiatorvtkRemoveIsolatedVerticesNew);
  vtkInstantiator::RegisterInstantiator("vtkRemoveHiddenData", vtkInstantiatorvtkRemoveHiddenDataNew);
  vtkInstantiator::RegisterInstantiator("vtkSCurveSpline", vtkInstantiatorvtkSCurveSplineNew);
  vtkInstantiator::RegisterInstantiator("vtkSimple2DLayoutStrategy", vtkInstantiatorvtkSimple2DLayoutStrategyNew);
  vtkInstantiator::RegisterInstantiator("vtkSimple3DCirclesStrategy", vtkInstantiatorvtkSimple3DCirclesStrategyNew);
  vtkInstantiator::RegisterInstantiator("vtkSliceAndDiceLayoutStrategy", vtkInstantiatorvtkSliceAndDiceLayoutStrategyNew);
  vtkInstantiator::RegisterInstantiator("vtkSplineGraphEdges", vtkInstantiatorvtkSplineGraphEdgesNew);
  vtkInstantiator::RegisterInstantiator("vtkSplitColumnComponents", vtkInstantiatorvtkSplitColumnComponentsNew);
  vtkInstantiator::RegisterInstantiator("vtkSquarifyLayoutStrategy", vtkInstantiatorvtkSquarifyLayoutStrategyNew);
  vtkInstantiator::RegisterInstantiator("vtkSpanTreeLayoutStrategy", vtkInstantiatorvtkSpanTreeLayoutStrategyNew);
  vtkInstantiator::RegisterInstantiator("vtkStackedTreeLayoutStrategy", vtkInstantiatorvtkStackedTreeLayoutStrategyNew);
  vtkInstantiator::RegisterInstantiator("vtkStrahlerMetric", vtkInstantiatorvtkStrahlerMetricNew);
  vtkInstantiator::RegisterInstantiator("vtkStreamGraph", vtkInstantiatorvtkStreamGraphNew);
  vtkInstantiator::RegisterInstantiator("vtkStreamingStatistics", vtkInstantiatorvtkStreamingStatisticsNew);
  vtkInstantiator::RegisterInstantiator("vtkStringToCategory", vtkInstantiatorvtkStringToCategoryNew);
  vtkInstantiator::RegisterInstantiator("vtkStringToNumeric", vtkInstantiatorvtkStringToNumericNew);
  vtkInstantiator::RegisterInstantiator("vtkTableToGraph", vtkInstantiatorvtkTableToGraphNew);
  vtkInstantiator::RegisterInstantiator("vtkTableToTreeFilter", vtkInstantiatorvtkTableToTreeFilterNew);
  vtkInstantiator::RegisterInstantiator("vtkThresholdGraph", vtkInstantiatorvtkThresholdGraphNew);
  vtkInstantiator::RegisterInstantiator("vtkThresholdTable", vtkInstantiatorvtkThresholdTableNew);
  vtkInstantiator::RegisterInstantiator("vtkTransferAttributes", vtkInstantiatorvtkTransferAttributesNew);
  vtkInstantiator::RegisterInstantiator("vtkTreeFieldAggregator", vtkInstantiatorvtkTreeFieldAggregatorNew);
  vtkInstantiator::RegisterInstantiator("vtkTreeLayoutStrategy", vtkInstantiatorvtkTreeLayoutStrategyNew);
  vtkInstantiator::RegisterInstantiator("vtkTreeOrbitLayoutStrategy", vtkInstantiatorvtkTreeOrbitLayoutStrategyNew);
  vtkInstantiator::RegisterInstantiator("vtkTreeLevelsFilter", vtkInstantiatorvtkTreeLevelsFilterNew);
  vtkInstantiator::RegisterInstantiator("vtkTreeMapLayout", vtkInstantiatorvtkTreeMapLayoutNew);
  vtkInstantiator::RegisterInstantiator("vtkTreeMapToPolyData", vtkInstantiatorvtkTreeMapToPolyDataNew);
  vtkInstantiator::RegisterInstantiator("vtkTreeRingToPolyData", vtkInstantiatorvtkTreeRingToPolyDataNew);
  vtkInstantiator::RegisterInstantiator("vtkTulipReader", vtkInstantiatorvtkTulipReaderNew);
  vtkInstantiator::RegisterInstantiator("vtkAttributeClustering2DLayoutStrategy", vtkInstantiatorvtkAttributeClustering2DLayoutStrategyNew);
  vtkInstantiator::RegisterInstantiator("vtkVertexDegree", vtkInstantiatorvtkVertexDegreeNew);
  vtkInstantiator::RegisterInstantiator("vtkXGMLReader", vtkInstantiatorvtkXGMLReaderNew);
  vtkInstantiator::RegisterInstantiator("vtkXMLTreeReader", vtkInstantiatorvtkXMLTreeReaderNew);
  vtkInstantiator::RegisterInstantiator("vtkAdjacencyMatrixToEdgeTable", vtkInstantiatorvtkAdjacencyMatrixToEdgeTableNew);
  vtkInstantiator::RegisterInstantiator("vtkArrayNorm", vtkInstantiatorvtkArrayNormNew);
  vtkInstantiator::RegisterInstantiator("vtkArrayToTable", vtkInstantiatorvtkArrayToTableNew);
  vtkInstantiator::RegisterInstantiator("vtkComputeHistogram2DOutliers", vtkInstantiatorvtkComputeHistogram2DOutliersNew);
  vtkInstantiator::RegisterInstantiator("vtkDiagonalMatrixSource", vtkInstantiatorvtkDiagonalMatrixSourceNew);
  vtkInstantiator::RegisterInstantiator("vtkDotProductSimilarity", vtkInstantiatorvtkDotProductSimilarityNew);
  vtkInstantiator::RegisterInstantiator("vtkExtractArray", vtkInstantiatorvtkExtractArrayNew);
  vtkInstantiator::RegisterInstantiator("vtkExtractHistogram2D", vtkInstantiatorvtkExtractHistogram2DNew);
  vtkInstantiator::RegisterInstantiator("vtkMatricizeArray", vtkInstantiatorvtkMatricizeArrayNew);
  vtkInstantiator::RegisterInstantiator("vtkNormalizeMatrixVectors", vtkInstantiatorvtkNormalizeMatrixVectorsNew);
  vtkInstantiator::RegisterInstantiator("vtkPairwiseExtractHistogram2D", vtkInstantiatorvtkPairwiseExtractHistogram2DNew);
  vtkInstantiator::RegisterInstantiator("vtkSparseArrayToTable", vtkInstantiatorvtkSparseArrayToTableNew);
  vtkInstantiator::RegisterInstantiator("vtkTableToArray", vtkInstantiatorvtkTableToArrayNew);
  vtkInstantiator::RegisterInstantiator("vtkTableToSparseArray", vtkInstantiatorvtkTableToSparseArrayNew);
  vtkInstantiator::RegisterInstantiator("vtkTransposeMatrix", vtkInstantiatorvtkTransposeMatrixNew);
  vtkInstantiator::RegisterInstantiator("vtkSQLDatabaseGraphSource", vtkInstantiatorvtkSQLDatabaseGraphSourceNew);
  vtkInstantiator::RegisterInstantiator("vtkSQLDatabaseTableSource", vtkInstantiatorvtkSQLDatabaseTableSourceNew);
  vtkInstantiator::RegisterInstantiator("vtkSQLGraphReader", vtkInstantiatorvtkSQLGraphReaderNew);
  vtkInstantiator::RegisterInstantiator("vtkStringToTimePoint", vtkInstantiatorvtkStringToTimePointNew);
  vtkInstantiator::RegisterInstantiator("vtkTimePointToString", vtkInstantiatorvtkTimePointToStringNew);

  
}
          
void vtkInfovisInstantiator::ClassFinalize()
{ 

  vtkInstantiator::UnRegisterInstantiator("vtkAddMembershipArray", vtkInstantiatorvtkAddMembershipArrayNew);
  vtkInstantiator::UnRegisterInstantiator("vtkAppendPoints", vtkInstantiatorvtkAppendPointsNew);
  vtkInstantiator::UnRegisterInstantiator("vtkApplyColors", vtkInstantiatorvtkApplyColorsNew);
  vtkInstantiator::UnRegisterInstantiator("vtkApplyIcons", vtkInstantiatorvtkApplyIconsNew);
  vtkInstantiator::UnRegisterInstantiator("vtkArcParallelEdgeStrategy", vtkInstantiatorvtkArcParallelEdgeStrategyNew);
  vtkInstantiator::UnRegisterInstantiator("vtkAreaLayout", vtkInstantiatorvtkAreaLayoutNew);
  vtkInstantiator::UnRegisterInstantiator("vtkAssignCoordinates", vtkInstantiatorvtkAssignCoordinatesNew);
  vtkInstantiator::UnRegisterInstantiator("vtkAssignCoordinatesLayoutStrategy", vtkInstantiatorvtkAssignCoordinatesLayoutStrategyNew);
  vtkInstantiator::UnRegisterInstantiator("vtkBivariateLinearTableThreshold", vtkInstantiatorvtkBivariateLinearTableThresholdNew);
  vtkInstantiator::UnRegisterInstantiator("vtkBoxLayoutStrategy", vtkInstantiatorvtkBoxLayoutStrategyNew);
  vtkInstantiator::UnRegisterInstantiator("vtkChacoGraphReader", vtkInstantiatorvtkChacoGraphReaderNew);
  vtkInstantiator::UnRegisterInstantiator("vtkCircularLayoutStrategy", vtkInstantiatorvtkCircularLayoutStrategyNew);
  vtkInstantiator::UnRegisterInstantiator("vtkClustering2DLayoutStrategy", vtkInstantiatorvtkClustering2DLayoutStrategyNew);
  vtkInstantiator::UnRegisterInstantiator("vtkCollapseGraph", vtkInstantiatorvtkCollapseGraphNew);
  vtkInstantiator::UnRegisterInstantiator("vtkCollapseVerticesByArray", vtkInstantiatorvtkCollapseVerticesByArrayNew);
  vtkInstantiator::UnRegisterInstantiator("vtkCommunity2DLayoutStrategy", vtkInstantiatorvtkCommunity2DLayoutStrategyNew);
  vtkInstantiator::UnRegisterInstantiator("vtkConeLayoutStrategy", vtkInstantiatorvtkConeLayoutStrategyNew);
  vtkInstantiator::UnRegisterInstantiator("vtkConstrained2DLayoutStrategy", vtkInstantiatorvtkConstrained2DLayoutStrategyNew);
  vtkInstantiator::UnRegisterInstantiator("vtkContingencyStatistics", vtkInstantiatorvtkContingencyStatisticsNew);
  vtkInstantiator::UnRegisterInstantiator("vtkCorrelativeStatistics", vtkInstantiatorvtkCorrelativeStatisticsNew);
  vtkInstantiator::UnRegisterInstantiator("vtkCosmicTreeLayoutStrategy", vtkInstantiatorvtkCosmicTreeLayoutStrategyNew);
  vtkInstantiator::UnRegisterInstantiator("vtkDataObjectToTable", vtkInstantiatorvtkDataObjectToTableNew);
  vtkInstantiator::UnRegisterInstantiator("vtkDelimitedTextReader", vtkInstantiatorvtkDelimitedTextReaderNew);
  vtkInstantiator::UnRegisterInstantiator("vtkDescriptiveStatistics", vtkInstantiatorvtkDescriptiveStatisticsNew);
  vtkInstantiator::UnRegisterInstantiator("vtkDIMACSGraphReader", vtkInstantiatorvtkDIMACSGraphReaderNew);
  vtkInstantiator::UnRegisterInstantiator("vtkDIMACSGraphWriter", vtkInstantiatorvtkDIMACSGraphWriterNew);
  vtkInstantiator::UnRegisterInstantiator("vtkEdgeCenters", vtkInstantiatorvtkEdgeCentersNew);
  vtkInstantiator::UnRegisterInstantiator("vtkEdgeLayout", vtkInstantiatorvtkEdgeLayoutNew);
  vtkInstantiator::UnRegisterInstantiator("vtkExpandSelectedGraph", vtkInstantiatorvtkExpandSelectedGraphNew);
  vtkInstantiator::UnRegisterInstantiator("vtkExtractSelectedGraph", vtkInstantiatorvtkExtractSelectedGraphNew);
  vtkInstantiator::UnRegisterInstantiator("vtkFast2DLayoutStrategy", vtkInstantiatorvtkFast2DLayoutStrategyNew);
  vtkInstantiator::UnRegisterInstantiator("vtkFixedWidthTextReader", vtkInstantiatorvtkFixedWidthTextReaderNew);
  vtkInstantiator::UnRegisterInstantiator("vtkForceDirectedLayoutStrategy", vtkInstantiatorvtkForceDirectedLayoutStrategyNew);
  vtkInstantiator::UnRegisterInstantiator("vtkGenerateIndexArray", vtkInstantiatorvtkGenerateIndexArrayNew);
  vtkInstantiator::UnRegisterInstantiator("vtkGeoEdgeStrategy", vtkInstantiatorvtkGeoEdgeStrategyNew);
  vtkInstantiator::UnRegisterInstantiator("vtkGeoMath", vtkInstantiatorvtkGeoMathNew);
  vtkInstantiator::UnRegisterInstantiator("vtkGraphHierarchicalBundle", vtkInstantiatorvtkGraphHierarchicalBundleNew);
  vtkInstantiator::UnRegisterInstantiator("vtkGraphHierarchicalBundleEdges", vtkInstantiatorvtkGraphHierarchicalBundleEdgesNew);
  vtkInstantiator::UnRegisterInstantiator("vtkGraphLayout", vtkInstantiatorvtkGraphLayoutNew);
  vtkInstantiator::UnRegisterInstantiator("vtkGroupLeafVertices", vtkInstantiatorvtkGroupLeafVerticesNew);
  vtkInstantiator::UnRegisterInstantiator("vtkISIReader", vtkInstantiatorvtkISIReaderNew);
  vtkInstantiator::UnRegisterInstantiator("vtkKMeansDistanceFunctor", vtkInstantiatorvtkKMeansDistanceFunctorNew);
  vtkInstantiator::UnRegisterInstantiator("vtkKMeansDistanceFunctorCalculator", vtkInstantiatorvtkKMeansDistanceFunctorCalculatorNew);
  vtkInstantiator::UnRegisterInstantiator("vtkKMeansStatistics", vtkInstantiatorvtkKMeansStatisticsNew);
  vtkInstantiator::UnRegisterInstantiator("vtkMergeColumns", vtkInstantiatorvtkMergeColumnsNew);
  vtkInstantiator::UnRegisterInstantiator("vtkMergeGraphs", vtkInstantiatorvtkMergeGraphsNew);
  vtkInstantiator::UnRegisterInstantiator("vtkMergeTables", vtkInstantiatorvtkMergeTablesNew);
  vtkInstantiator::UnRegisterInstantiator("vtkMultiCorrelativeStatistics", vtkInstantiatorvtkMultiCorrelativeStatisticsNew);
  vtkInstantiator::UnRegisterInstantiator("vtkMutableGraphHelper", vtkInstantiatorvtkMutableGraphHelperNew);
  vtkInstantiator::UnRegisterInstantiator("vtkNetworkHierarchy", vtkInstantiatorvtkNetworkHierarchyNew);
  vtkInstantiator::UnRegisterInstantiator("vtkOrderStatistics", vtkInstantiatorvtkOrderStatisticsNew);
  vtkInstantiator::UnRegisterInstantiator("vtkPassArrays", vtkInstantiatorvtkPassArraysNew);
  vtkInstantiator::UnRegisterInstantiator("vtkPassThrough", vtkInstantiatorvtkPassThroughNew);
  vtkInstantiator::UnRegisterInstantiator("vtkPassThroughEdgeStrategy", vtkInstantiatorvtkPassThroughEdgeStrategyNew);
  vtkInstantiator::UnRegisterInstantiator("vtkPassThroughLayoutStrategy", vtkInstantiatorvtkPassThroughLayoutStrategyNew);
  vtkInstantiator::UnRegisterInstantiator("vtkPerturbCoincidentVertices", vtkInstantiatorvtkPerturbCoincidentVerticesNew);
  vtkInstantiator::UnRegisterInstantiator("vtkPCAStatistics", vtkInstantiatorvtkPCAStatisticsNew);
  vtkInstantiator::UnRegisterInstantiator("vtkPruneTreeFilter", vtkInstantiatorvtkPruneTreeFilterNew);
  vtkInstantiator::UnRegisterInstantiator("vtkRISReader", vtkInstantiatorvtkRISReaderNew);
  vtkInstantiator::UnRegisterInstantiator("vtkRandomGraphSource", vtkInstantiatorvtkRandomGraphSourceNew);
  vtkInstantiator::UnRegisterInstantiator("vtkRandomLayoutStrategy", vtkInstantiatorvtkRandomLayoutStrategyNew);
  vtkInstantiator::UnRegisterInstantiator("vtkRemoveIsolatedVertices", vtkInstantiatorvtkRemoveIsolatedVerticesNew);
  vtkInstantiator::UnRegisterInstantiator("vtkRemoveHiddenData", vtkInstantiatorvtkRemoveHiddenDataNew);
  vtkInstantiator::UnRegisterInstantiator("vtkSCurveSpline", vtkInstantiatorvtkSCurveSplineNew);
  vtkInstantiator::UnRegisterInstantiator("vtkSimple2DLayoutStrategy", vtkInstantiatorvtkSimple2DLayoutStrategyNew);
  vtkInstantiator::UnRegisterInstantiator("vtkSimple3DCirclesStrategy", vtkInstantiatorvtkSimple3DCirclesStrategyNew);
  vtkInstantiator::UnRegisterInstantiator("vtkSliceAndDiceLayoutStrategy", vtkInstantiatorvtkSliceAndDiceLayoutStrategyNew);
  vtkInstantiator::UnRegisterInstantiator("vtkSplineGraphEdges", vtkInstantiatorvtkSplineGraphEdgesNew);
  vtkInstantiator::UnRegisterInstantiator("vtkSplitColumnComponents", vtkInstantiatorvtkSplitColumnComponentsNew);
  vtkInstantiator::UnRegisterInstantiator("vtkSquarifyLayoutStrategy", vtkInstantiatorvtkSquarifyLayoutStrategyNew);
  vtkInstantiator::UnRegisterInstantiator("vtkSpanTreeLayoutStrategy", vtkInstantiatorvtkSpanTreeLayoutStrategyNew);
  vtkInstantiator::UnRegisterInstantiator("vtkStackedTreeLayoutStrategy", vtkInstantiatorvtkStackedTreeLayoutStrategyNew);
  vtkInstantiator::UnRegisterInstantiator("vtkStrahlerMetric", vtkInstantiatorvtkStrahlerMetricNew);
  vtkInstantiator::UnRegisterInstantiator("vtkStreamGraph", vtkInstantiatorvtkStreamGraphNew);
  vtkInstantiator::UnRegisterInstantiator("vtkStreamingStatistics", vtkInstantiatorvtkStreamingStatisticsNew);
  vtkInstantiator::UnRegisterInstantiator("vtkStringToCategory", vtkInstantiatorvtkStringToCategoryNew);
  vtkInstantiator::UnRegisterInstantiator("vtkStringToNumeric", vtkInstantiatorvtkStringToNumericNew);
  vtkInstantiator::UnRegisterInstantiator("vtkTableToGraph", vtkInstantiatorvtkTableToGraphNew);
  vtkInstantiator::UnRegisterInstantiator("vtkTableToTreeFilter", vtkInstantiatorvtkTableToTreeFilterNew);
  vtkInstantiator::UnRegisterInstantiator("vtkThresholdGraph", vtkInstantiatorvtkThresholdGraphNew);
  vtkInstantiator::UnRegisterInstantiator("vtkThresholdTable", vtkInstantiatorvtkThresholdTableNew);
  vtkInstantiator::UnRegisterInstantiator("vtkTransferAttributes", vtkInstantiatorvtkTransferAttributesNew);
  vtkInstantiator::UnRegisterInstantiator("vtkTreeFieldAggregator", vtkInstantiatorvtkTreeFieldAggregatorNew);
  vtkInstantiator::UnRegisterInstantiator("vtkTreeLayoutStrategy", vtkInstantiatorvtkTreeLayoutStrategyNew);
  vtkInstantiator::UnRegisterInstantiator("vtkTreeOrbitLayoutStrategy", vtkInstantiatorvtkTreeOrbitLayoutStrategyNew);
  vtkInstantiator::UnRegisterInstantiator("vtkTreeLevelsFilter", vtkInstantiatorvtkTreeLevelsFilterNew);
  vtkInstantiator::UnRegisterInstantiator("vtkTreeMapLayout", vtkInstantiatorvtkTreeMapLayoutNew);
  vtkInstantiator::UnRegisterInstantiator("vtkTreeMapToPolyData", vtkInstantiatorvtkTreeMapToPolyDataNew);
  vtkInstantiator::UnRegisterInstantiator("vtkTreeRingToPolyData", vtkInstantiatorvtkTreeRingToPolyDataNew);
  vtkInstantiator::UnRegisterInstantiator("vtkTulipReader", vtkInstantiatorvtkTulipReaderNew);
  vtkInstantiator::UnRegisterInstantiator("vtkAttributeClustering2DLayoutStrategy", vtkInstantiatorvtkAttributeClustering2DLayoutStrategyNew);
  vtkInstantiator::UnRegisterInstantiator("vtkVertexDegree", vtkInstantiatorvtkVertexDegreeNew);
  vtkInstantiator::UnRegisterInstantiator("vtkXGMLReader", vtkInstantiatorvtkXGMLReaderNew);
  vtkInstantiator::UnRegisterInstantiator("vtkXMLTreeReader", vtkInstantiatorvtkXMLTreeReaderNew);
  vtkInstantiator::UnRegisterInstantiator("vtkAdjacencyMatrixToEdgeTable", vtkInstantiatorvtkAdjacencyMatrixToEdgeTableNew);
  vtkInstantiator::UnRegisterInstantiator("vtkArrayNorm", vtkInstantiatorvtkArrayNormNew);
  vtkInstantiator::UnRegisterInstantiator("vtkArrayToTable", vtkInstantiatorvtkArrayToTableNew);
  vtkInstantiator::UnRegisterInstantiator("vtkComputeHistogram2DOutliers", vtkInstantiatorvtkComputeHistogram2DOutliersNew);
  vtkInstantiator::UnRegisterInstantiator("vtkDiagonalMatrixSource", vtkInstantiatorvtkDiagonalMatrixSourceNew);
  vtkInstantiator::UnRegisterInstantiator("vtkDotProductSimilarity", vtkInstantiatorvtkDotProductSimilarityNew);
  vtkInstantiator::UnRegisterInstantiator("vtkExtractArray", vtkInstantiatorvtkExtractArrayNew);
  vtkInstantiator::UnRegisterInstantiator("vtkExtractHistogram2D", vtkInstantiatorvtkExtractHistogram2DNew);
  vtkInstantiator::UnRegisterInstantiator("vtkMatricizeArray", vtkInstantiatorvtkMatricizeArrayNew);
  vtkInstantiator::UnRegisterInstantiator("vtkNormalizeMatrixVectors", vtkInstantiatorvtkNormalizeMatrixVectorsNew);
  vtkInstantiator::UnRegisterInstantiator("vtkPairwiseExtractHistogram2D", vtkInstantiatorvtkPairwiseExtractHistogram2DNew);
  vtkInstantiator::UnRegisterInstantiator("vtkSparseArrayToTable", vtkInstantiatorvtkSparseArrayToTableNew);
  vtkInstantiator::UnRegisterInstantiator("vtkTableToArray", vtkInstantiatorvtkTableToArrayNew);
  vtkInstantiator::UnRegisterInstantiator("vtkTableToSparseArray", vtkInstantiatorvtkTableToSparseArrayNew);
  vtkInstantiator::UnRegisterInstantiator("vtkTransposeMatrix", vtkInstantiatorvtkTransposeMatrixNew);
  vtkInstantiator::UnRegisterInstantiator("vtkSQLDatabaseGraphSource", vtkInstantiatorvtkSQLDatabaseGraphSourceNew);
  vtkInstantiator::UnRegisterInstantiator("vtkSQLDatabaseTableSource", vtkInstantiatorvtkSQLDatabaseTableSourceNew);
  vtkInstantiator::UnRegisterInstantiator("vtkSQLGraphReader", vtkInstantiatorvtkSQLGraphReaderNew);
  vtkInstantiator::UnRegisterInstantiator("vtkStringToTimePoint", vtkInstantiatorvtkStringToTimePointNew);
  vtkInstantiator::UnRegisterInstantiator("vtkTimePointToString", vtkInstantiatorvtkTimePointToStringNew);

  
}

vtkInfovisInstantiator::vtkInfovisInstantiator()
{
  if(++vtkInfovisInstantiator::Count == 1)
    { 
    vtkInfovisInstantiator::ClassInitialize(); 
    }
}

vtkInfovisInstantiator::~vtkInfovisInstantiator()
{
  if(--vtkInfovisInstantiator::Count == 0)
    { 
    vtkInfovisInstantiator::ClassFinalize(); 
    }
}

// Number of translation units that include this class's header.
// Purposely not initialized.  Default is static initialization to 0.
unsigned int vtkInfovisInstantiator::Count;
